<?php

return [

    // ══════════════════════════════════════════════════════════════
    // SLOT 1 — NAV_COMPLEX (NAV_HAZ) — Fog navigation approaching Dardanelles TSS with dense ferry/fishing traffic
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S01_NAV_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Aegean Star, a 4,800 DWT general cargo coaster (89 metres LOA, beam 13.6 metres, draft 5.2 metres) loaded with 3,600 tonnes of bagged cement bound for Bandirma in the Sea of Marmara. You are approaching the southern entrance of the Dardanelles Strait (Canakkale Bogazi) from the Aegean Sea, currently 4 nautical miles southwest of Mehmetcik Burnu (Cape Helles). Dense advection fog has settled over the area since 0430, reducing visibility to approximately 150 to 200 metres. Your radar displays show extremely heavy traffic: at least 8 merchant vessels are visible within 6 nautical miles on various courses, the Canakkale-Eceabat ferry service is operating its regular 20-minute crossings (3 ferries on the route), and a cluster of 15 to 20 small radar returns consistent with a fishing fleet is positioned directly across the TSS inbound lane approximately 2 nautical miles ahead. The Canakkale VTS (TVAS — Turkish Vessel Traffic Service for the Straits) requires mandatory reporting at the TSS entry waypoint. Your last position report to Canakkale VTS was at the Bozcaada reporting point 45 minutes ago, and VTS acknowledged but gave no specific traffic information for the strait approach area. The current is setting NE at approximately 1.5 knots (the typical Aegean-to-Marmara surface current). Your vessel is equipped with two radars (X-band and S-band), AIS, GPS, ECDIS with updated Turkish ENCs, and VHF. The Chief Officer is on watch with you and one AB is posted as lookout on the bridge wing, but the fog makes visual detection almost impossible beyond 150 metres. The scheduled strait transit was planned for daylight with clear visibility, but your departure from Aliaga was delayed 6 hours by cargo operations. The vessel has no bow thruster and a single controllable-pitch propeller.',
                'your_position'       => 'Wheelhouse, command. Chief Officer operating radar and maintaining ECDIS plot. One AB on the port bridge wing as lookout with VHF handheld. Helmsman on manual steering. Engine room on standby, main engine at full sea speed (12 knots). Bosun and one AB on standby below.',
                'available_resources'  => 'Two radar displays: X-band (3 cm) set at 3 NM range with rain/sea clutter adjusted, S-band (10 cm) at 12 NM range for overview. ECDIS with current Turkish ENC and AIS overlay. AIS Class A transponder. GPS (two independent receivers). VHF radio (Ch 16, Ch 11 for Canakkale VTS, Ch 13 for bridge-to-bridge). Echo sounder. Manual steering engaged. Main engine 3,200 kW, CPP, single rudder. No bow thruster. One anchor ready for letting go (port anchor cleared, 4 shackles in the water). Whistle/horn operational. Navigation lights verified. Fog signal apparatus. IAMSAR Manual Vol III. Turkish Straits passage plan prepared. Company SMS bridge procedures for restricted visibility.',
                'current_conditions'   => 'Visibility 150-200 metres (dense fog), wind calm, sea state 0-1, current 1.5 knots NE, vessel speed 12 knots over ground on course 040°T toward Dardanelles TSS entry. Multiple radar contacts: 8+ merchant vessels within 6 NM, 3 ferries on Canakkale-Eceabat route, fishing fleet of 15-20 vessels across inbound TSS lane 2 NM ahead. Canakkale VTS last contacted 45 minutes ago at Bozcaada reporting point. Strait transit was planned for daylight/clear conditions but vessel departure delayed. Dawn was at 0645, current time 0715. Main engine at full ahead.',
            ],
            'tr' => [
                'situation'           => 'MV Aegean Star\'ın kaptanısınız — 4.800 DWT genel kargo koster (89 m LOA, genişlik 13,6 m, draft 5,2 m), Marmara Denizi\'nde Bandırma\'ya gitmek üzere 3.600 ton torbalı çimento yüklü. Ege Denizi\'nden Çanakkale Boğazı güney girişine yaklaşıyorsunuz, şu anda Mehmetçik Burnu\'nun (Gelibolu) yaklaşık 4 deniz mili güneybatısındasınız. Saat 04:30\'dan beri bölgeye çöken yoğun adveksiyon sisi görüşü yaklaşık 150-200 metreye düşürmüş durumda. Radar ekranlarınız son derece yoğun trafik gösteriyor: 6 deniz mili içinde çeşitli rotalarda en az 8 ticari gemi, düzenli 20 dakikalık seferlerini yapan Çanakkale-Eceabat feribot hattı (rotada 3 feribot) ve yaklaşık 2 deniz mili ileride TSS giriş şeridinin tam karşısında 15-20 küçük radar ekosundan oluşan bir balıkçı filosu görünüyor. Çanakkale VTS (TVAS — Türk Boğazları Gemi Trafik Hizmetleri) TSS giriş noktasında zorunlu rapor istiyor. Son pozisyon raporunuzu 45 dakika önce Bozcaada raporlama noktasında verdiniz, VTS onayladı ancak boğaz yaklaşım bölgesi için özel trafik bilgisi vermedi. Akıntı KD yönünde yaklaşık 1,5 knot (tipik Ege-Marmara yüzey akıntısı). Geminizde iki radar (X-band ve S-band), AIS, GPS, güncel Türk ENC\'li ECDIS ve VHF mevcut. Baş Zabit sizinle birlikte nöbette ve bir AB köprü kanadında gözcü olarak görevli, ancak sis 150 metrenin ötesinde görsel tespiti neredeyse imkansız kılıyor. Planlanan boğaz geçişi gündüz ve açık görüşte yapılacaktı, ancak Aliağa\'dan kalkışınız kargo operasyonları nedeniyle 6 saat gecikti. Gemide baş iticisi yok ve tek kontrol edilebilir adımlı pervane var.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Zabit radar kullanıyor ve ECDIS plotlaması yapıyor. Bir AB iskele köprü kanadında VHF el telsizi ile gözcü. Dümenci manuel dümen başında. Makine dairesi hazır beklemede, ana makine tam deniz hızında (12 knot). Lostromo ve bir AB aşağıda hazır beklemede.',
                'available_resources'  => 'İki radar: X-band (3 cm) 3 NM, S-band (10 cm) 12 NM. Güncel Türk ENC ve AIS örtüşmeli ECDIS. AIS Class A. İki bağımsız GPS alıcısı. VHF (Kanal 16, Kanal 11 Çanakkale VTS, Kanal 13 köprüden köprüye). İskandil. Manuel dümen. Ana makine 3.200 kW, CPP. Baş itici yok. İskele çıpa hazır (4 kilit). Düdük/sis sinyali. Seyir fenerleri doğrulanmış. IAMSAR Cilt III. Türk Boğazları geçiş planı. Şirket SMS kısıtlı görüş prosedürleri.',
                'current_conditions'   => 'Görüş 150-200 m (yoğun sis), rüzgar sakin, deniz durumu 0-1, akıntı 1,5 knot KD, gemi hızı 12 knot yer üstü, rota 040°T TSS girişine doğru. Radar: 6 NM içinde 8+ ticari gemi, 3 feribot, 2 NM ileride 15-20 balıkçı. VTS son temas 45 dk önce. Boğaz geçişi gündüz/açık hava için planlanmıştı, kalkış 6 saat gecikti. Şafak 06:45, şu an 07:15.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Aegean Star — каботажное сухогрузное судно 4 800 DWT (89 м, осадка 5,2 м), 3 600 т цемента, курс на Бандырму. Подходите к южному входу в Дарданеллы со стороны Эгейского моря, 4 мили к ЮЗ от мыса Хеллес. Плотный адвективный туман — видимость 150–200 м. На радаре: 8+ судов в 6 милях, 3 парома Чанаккале–Эджеабат, 15–20 рыбаков перекрывают входную полосу СРД в 2 милях впереди. VTS Чанаккале требует обязательного доклада на входе в СРД. Течение 1,5 уз на СВ. Два радара, AIS, ECDIS, GPS. Транзит планировался на светлое время, но выход задержался на 6 часов.',
                'your_position'       => 'Рубка, командование. Старпом — радар и ECDIS. Матрос — наблюдатель на крыле. Рулевой на ручном. Машина на полном.',
                'available_resources'  => 'X-band и S-band радары, ECDIS с AIS, два GPS, УКВ (каналы 16, 11 VTS, 13), эхолот, CPP 3 200 кВт, один якорь наготове, туманный сигнал.',
                'current_conditions'   => 'Туман 150–200 м, штиль, течение 1,5 уз СВ, скорость 12 уз, курс 040°. Множество контактов на радаре. VTS доклад 45 мин назад.',
            ],
            'az' => [
                'situation'           => 'MV Aegean Star-ın kapitanısınız — 4.800 DWT yük kosteri (89 m, su çəkimi 5,2 m), 3.600 t sement, Bandırmaya gedir. Egey dənizindən Dardanel boğazının cənub girişinə yaxınlaşırsınız. Sıx duman — görmə 150–200 m. Radarda: 6 mil daxilində 8+ gəmi, 3 bərə, 2 mil irəlidə 15–20 balıqçı TSS zolağını kəsir. Çanaqqala VTS məcburi məruzə tələb edir. Axın 1,5 düyün ŞQ. İki radar, AIS, ECDIS, GPS mövcud. Boğaz keçidi gündüz planlanmışdı, amma gəmi 6 saat gecikib.',
                'your_position'       => 'Kapitanlıq körpüsü. Baş zabit — radar/ECDIS. Matros — müşahidəçi. Sükan əl ilə. Maşın hazır.',
                'available_resources'  => 'X-band və S-band radarlar, ECDIS, AIS, iki GPS, VHF (16, 11, 13 kanallar), exolot, CPP 3200 kVt, lövbər hazır, duman siqnalı.',
                'current_conditions'   => 'Duman 150–200 m, sakit, axın 1,5 düyün, sürət 12 düyün, kurs 040°. Çoxlu radar əlaqələri. VTS 45 dəq əvvəl.',
            ],
        ],
        'decision_prompt'      => 'Describe your plan for navigating safely through this dense fog toward the Dardanelles TSS entry. Address: your immediate speed decision and COLREG Rule 19 compliance, how you will manage the fishing fleet blocking the inbound TSS lane, your communication plan with Canakkale VTS and surrounding traffic, your radar plotting strategy for the multiple contacts, and whether you will continue the strait transit or anchor and wait for visibility to improve.',
        'decision_prompt_i18n' => [
            'tr' => 'Bu yoğun siste Çanakkale Boğazı TSS girişine güvenli seyir planınızı açıklayın. Ele alınacak konular: ani hız kararınız ve COLREG Kural 19 uyumu, giriş TSS şeridini kapatan balıkçı filosunu nasıl yöneteceğiniz, Çanakkale VTS ve çevre trafikle iletişim planınız, çoklu kontaklar için radar plotlama stratejiniz ve boğaz geçişine devam mı edeceksiniz yoksa demir atıp görüşün düzelmesini mi bekleyeceksiniz.',
            'ru' => 'Опишите план безопасного плавания в тумане к входу в СРД Дарданелл: решение по скорости и МППСС Правило 19, управление рыбацким флотом на пути, связь с VTS и окружающим трафиком, радарная прокладка, решение о продолжении транзита или якорной стоянке.',
            'az' => 'Sıx dumanda Dardanel TSS girişinə təhlükəsiz seyir planınızı təsvir edin: sürət qərarı və COLREG Qayda 19, balıqçı filosunun idarəsi, VTS və trafiklə əlaqə, radar müşahidəsi, boğaz keçidinə davam və ya lövbərdə gözləmə qərarı.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'fog_navigation_technique',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Maintains full sea speed of 12 knots in 150-metre visibility. No recognition that the vessel is approaching a congested strait entrance in dense fog. No adaptation of navigation routine for restricted visibility. No additional lookout measures beyond the single AB already posted.',
                    '2' => 'Reduces speed somewhat but does not calculate a safe speed considering the vessel stopping distance relative to the visibility range. Posts the fog signal but does not systematically adapt the bridge routine. Radar is monitored but contacts are not plotted or tracked systematically.',
                    '3' => 'Reduces to a safe speed that allows the vessel to stop within the visible distance, taking into account the 1.5-knot current pushing the vessel into the congested area. Sounds the prescribed fog signal (one prolonged blast every 2 minutes per COLREG Rule 35). Activates the second radar for independent monitoring. Posts additional lookout forward. Engages manual steering. Puts engine on standby for immediate response. Systematically plots and tracks all radar contacts with CPA/TCPA assessment.',
                    '4' => 'Comprehensive fog procedure: calculates that at 12 knots the vessel covers 200 metres in 33 seconds — at 150m visibility there is zero reaction margin — and immediately reduces to 5-6 knots. Accounts for the 1.5-knot NE current adding to the effective approach speed. Uses both radars with complementary settings (X-band short range for close contacts, S-band for overview). Activates ARPA/target tracking on priority contacts. Cross-checks radar contacts against AIS data to identify non-AIS vessels (fishing boats). Prepares anchor for immediate letting go. Briefs all bridge team on restricted visibility procedures per SMS.',
                    '5' => 'Expert fog navigation: immediately reduces to bare steerage (3-4 knots through water, accounting for 1.5-knot current gives 5 knots over ground) while assessing whether to proceed at all. Systematically evaluates stopping distance at various speeds against visibility range and traffic density, concluding that safe speed may require stopping the vessel entirely. Both radars optimally configured — X-band at 1.5 NM for immediate collision avoidance with gain/clutter carefully tuned for small wooden fishing vessels, S-band at 6 NM for strategic traffic picture. Every contact tracked with CPA/TCPA, priority contacts plotted on ECDIS. Forward lookout equipped with radio and positioned on forecastle. Sound signals precisely timed per COLREG. Echo sounder running continuously to cross-check position against charted depths. Anchor cleared for emergency use with 4 shackles ready. Full bridge team briefed with specific duties assigned. Considers anchoring in safe water and awaiting visibility improvement rather than entering the congested strait approach in fog.',
                ],
            ],
            [
                'axis'   => 'colreg_rule_19_compliance',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No awareness of COLREG Rule 19 (Conduct in restricted visibility). Treats radar contacts the same as visual contacts. Attempts to apply crossing/overtaking rules meant for vessels in sight of one another. No safe speed consideration.',
                    '2' => 'Aware that fog changes the navigation rules but cannot articulate Rule 19 requirements. Reduces speed but not to a level related to visibility and stopping distance. Makes some radar-based decisions but does not follow the Rule 19 framework of detecting contacts by radar alone.',
                    '3' => 'Properly applies Rule 19: navigates at a safe speed adapted to visibility and traffic density, uses radar effectively to determine if a close-quarters situation is developing, takes avoiding action in ample time if CPA is unsatisfactory, avoids alteration of course to port for a vessel forward of the beam, avoids altering course toward a vessel abeam or abaft the beam. Sounds prescribed fog signals.',
                    '4' => 'Thorough Rule 19 application: demonstrates clear understanding that in restricted visibility all contacts are "radar contacts" and visual rules (Rules 12-18) do not apply. Systematically assesses each contact for CPA/TCPA and takes early, substantial action when CPA is less than a predetermined safe distance (appropriate for coastal waters — 0.5 NM minimum). Recognizes that Rule 19(e) allows speed reduction to bare minimum or stopping the vessel. Documents radar observations and actions taken.',
                    '5' => 'Expert COLREG integration: applies Rule 19 in conjunction with Rule 5 (lookout by all available means), Rule 6 (safe speed — all listed factors considered including traffic density, radar limitations, sea state, proximity to navigation hazards), Rule 7 (risk of collision — uses radar plotting, does not make assumptions on scanty information), and Rule 8 (action to avoid collision — made in ample time, substantial, readily apparent on radar). Recognizes the limitation of radar in detecting small wooden fishing boats and compensates with extreme caution. Understands that the Dardanelles TSS creates additional routing obligations under Rule 10 but that safety of navigation under Rule 2(b) overrides schedule. Applies the "succession of small alterations" prohibition — if course change needed, makes it large enough to be detected by other vessels on radar.',
                ],
            ],
            [
                'axis'   => 'vts_coordination',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No contact with Canakkale VTS since the Bozcaada report 45 minutes ago. Does not recognize the obligation to report before entering the TSS. Proceeds without seeking traffic information from VTS.',
                    '2' => 'Contacts VTS but only to make a routine position report. Does not request traffic information or report the restricted visibility conditions encountered. Does not ask for VTS guidance regarding the fishing fleet or ferry traffic.',
                    '3' => 'Good VTS coordination: contacts Canakkale VTS on Channel 11 to report current position, speed reduction due to fog, and intention to enter the TSS. Requests traffic information for the strait approach area. Reports the fishing fleet position across the inbound lane. Asks about ferry traffic patterns. Updates VTS on any course or speed changes.',
                    '4' => 'Proactive VTS engagement: contacts VTS well before the reporting point to advise of the severe visibility conditions and heavy traffic encountered. Requests detailed traffic information including vessel names/types/positions for all traffic in the approach area. Asks VTS whether any special traffic management measures are in effect for the fog conditions. Requests information on the fishing fleet and whether VTS has been able to contact them. Coordinates with VTS on timing of TSS entry to minimize conflict with ferry crossings. Provides regular position updates.',
                    '5' => 'Expert VTS partnership: treats VTS as a critical navigation resource in these conditions. Establishes a communication plan with VTS for continuous updates. Requests that VTS provide real-time traffic information broadcasts for the approach area. Asks VTS to contact the fishing fleet and request they clear the TSS lane or at least show proper signals. Coordinates with VTS on an optimal TSS entry time that avoids ferry crossing windows. Requests VTS relay information to inbound/outbound traffic about own vessel position and reduced speed. If VTS advises waiting, accepts the recommendation. Offers to provide traffic observations from own radar to assist VTS. Requests pilot boarding coordination through VTS if pilotage is required. Maintains VHF watch on both VTS and bridge-to-bridge channels.',
                ],
            ],
            [
                'axis'   => 'traffic_management_decision',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No plan for the fishing fleet across the TSS lane. No consideration of ferry traffic patterns. Proceeds at speed hoping contacts will clear. No contingency if the approach becomes too dangerous.',
                    '2' => 'Identifies the fishing fleet as a problem but has no specific plan to navigate through or around them. Aware of the ferries but does not integrate their crossing pattern into the passage plan. Has a vague idea of anchoring if things get bad but no defined criteria.',
                    '3' => 'Develops a traffic management plan: tracks all contacts systematically, identifies the fishing fleet cluster and plans a route around it if safe to do so (considering TSS boundaries), times TSS entry to avoid ferry crossing windows if possible, uses VHF Channel 13 to broadcast intentions to nearby traffic, has a clear go/no-go decision point for continuing the transit versus anchoring.',
                    '4' => 'Comprehensive traffic handling: distinguishes between AIS-equipped vessels (merchant traffic, ferries) and non-AIS contacts (likely fishing boats), uses this to assess the true traffic picture. Plans approach route using the ECDIS to identify safe water outside the TSS where anchoring is possible if needed. Calculates ferry crossing intervals and plans TSS entry during a gap. Attempts VHF contact with fishing fleet on Channel 16 and local fishing channels. Establishes clear criteria for aborting the transit (e.g., if CPA with any contact falls below 0.3 NM, or if multiple contacts create an unmanageable situation).',
                    '5' => 'Expert situation management: recognizes that the combination of dense fog, heavy merchant traffic, a fishing fleet across the TSS, and active ferry crossings creates an extraordinarily high-risk situation that may not be manageable at any speed. Considers all options: (a) proceed at minimum safe speed with maximum precautions, (b) anchor in safe water southwest of the TSS entry and wait for visibility, (c) contact VTS to request traffic management assistance. Makes a risk-based decision considering that the delayed departure already put the vessel outside its planned weather window, and rushing through fog to recover schedule creates unacceptable risk. If deciding to anchor, selects a safe anchorage clear of the TSS and traffic, deploys anchor light/shape and fog signal, monitors traffic on radar, and informs VTS of the anchored position. If deciding to proceed, does so only after confirming with VTS that a safe transit window exists.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Maintaining full sea speed (12 knots) in 150-metre visibility in a congested approach to the Dardanelles — grossly unsafe speed under COLREG Rule 6', 'severity' => 'critical'],
            ['flag' => 'No contact with Canakkale VTS before entering the TSS in restricted visibility — violation of mandatory reporting requirements', 'severity' => 'critical'],
            ['flag' => 'No systematic radar plotting of contacts — proceeding blind into multiple-contact situation without CPA/TCPA assessment', 'severity' => 'critical'],
            ['flag' => 'Not sounding the prescribed fog signal (one prolonged blast every 2 minutes) — COLREG Rule 35 violation', 'severity' => 'major'],
            ['flag' => 'No additional lookout posted forward and no bridge team reinforcement for restricted visibility navigation', 'severity' => 'major'],
            ['flag' => 'No consideration of anchoring to wait for visibility improvement when approaching a congested strait in dense fog', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'COLREG 1972 — Rule 5 (Lookout), Rule 6 (Safe Speed), Rule 7 (Risk of Collision), Rule 8 (Action to Avoid Collision), Rule 10 (Traffic Separation Schemes), Rule 19 (Conduct in Restricted Visibility), Rule 35 (Sound Signals in Restricted Visibility)',
            'SOLAS Chapter V Regulation 34 — Safe Navigation and Avoidance of Dangerous Situations',
            'Turkish Straits Maritime Traffic Regulations (Türk Bogazlari Deniz Trafik Düzeni Tüzügü) — mandatory VTS reporting and TSS compliance',
            'IMO Resolution A.857(20) — Guidelines for Vessel Traffic Services',
            'IMO Ships Routeing — Turkish Straits Traffic Separation Schemes',
            'IALA VTS Manual — cooperation between vessels and VTS in restricted visibility',
            'Company SMS — Bridge procedures for restricted visibility navigation',
        ],
        'red_flags_json' => [
            'Maintaining 12 knots in 150-metre visibility approaching a congested strait — zero stopping margin',
            'Not contacting Canakkale VTS before TSS entry in fog — missed critical traffic information',
            'No systematic radar tracking of the 20+ contacts in the approach area — loss of situational awareness',
            'Attempting to navigate through the fishing fleet at speed without plotted CPAs',
            'Not sounding fog signals as required by COLREG Rule 35',
            'Refusing to consider anchoring despite fog, heavy traffic, and delayed schedule already compromising the passage plan',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 2 — CMD_SCALE (COMM_PRESS) — Master authority under charterer/pilot/agent pressure in Marmara Sea
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S02_CMD_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Kocaeli Pride, a 7,500 DWT coastal tanker (108 metres LOA, beam 16.2 metres, draft 7.8 metres) carrying 6,800 tonnes of gas oil in six cargo tanks, approaching Tuzla anchorage in the eastern Sea of Marmara. You are bound for the TUPRAS Izmit refinery terminal in Izmit Bay. The charterer\'s operations coordinator has been calling your satellite phone repeatedly for the past two hours, demanding that you proceed directly to the berth without anchoring — the berth has just become available and there is a 4-hour window before another vessel is scheduled. If you miss this window the next available berth slot is in 3 days, and the charterer has warned of demurrage claims and potential contract termination. Your agent in Izmit confirms the berth is ready but warns that the pilot station at Tuzla is experiencing a 2-hour delay due to a pilot shortage — only two pilots are available for four vessels waiting. The weather is deteriorating: a SW wind has increased to 25 knots and is forecast to reach 35-40 knots by evening with associated sea state 4-5 in the exposed approaches to Izmit Bay. Your Chief Engineer has just reported that the main engine governor is showing intermittent fluctuations — the engine RPM occasionally surges by 15-20 RPM before stabilizing. He assesses it as a governor control unit issue, not dangerous for now, but recommends investigation at the next port. The vessel completed her last PSC inspection 8 months ago with two observations (one related to fire-fighting equipment, now rectified). Your DPA (Designated Person Ashore) last contacted you 4 hours ago and is not aware of the governor issue or the weather deterioration. The vessel has 16 crew members. Your passage through the Izmit Bay approach requires pilot navigation through a channel with restricted width, multiple ferries, and several sharp turns past the Tuzla shipyard area.',
                'your_position'       => 'Wheelhouse, command. Chief Officer preparing for arrival — cargo plan review and mooring plan. Second Officer on bridge watch with helmsman. Chief Engineer in engine room monitoring governor issue. Bosun preparing mooring stations.',
                'available_resources'  => 'Main engine 4,800 kW (governor fluctuation noted), single CPP, bow thruster 350 kW, two radars, ECDIS, AIS, VHF (Ch 16, Ch 12 Izmit VTS, Ch 14 pilot), GPS, echo sounder, satellite phone, email for company/charterer communication, ISGOTT manual, company SMS including Master\'s overriding authority procedures, ISM documentation, cargo monitoring system for all 6 tanks (ullage, temperature, pressure), mooring equipment fore and aft, anchor gear.',
                'current_conditions'   => 'Wind SW 25 knots increasing to 35-40 by evening, sea state 3 building, visibility good (8+ NM), current weak in Marmara. Vessel 12 NM from Tuzla anchorage, speed 11 knots. Pilot delay 2 hours minimum. Charterer demanding direct berthing, berth window 4 hours. Governor intermittent fluctuation (+/- 15-20 RPM). Next PSC-free window uncertain. DPA not yet informed of current situation. 16 crew, all positions manned.',
            ],
            'tr' => [
                'situation'           => 'MV Kocaeli Pride\'ın kaptanısınız — 7.500 DWT kıyı tankeri (108 m LOA, genişlik 16,2 m, draft 7,8 m), altı kargo tankında 6.800 ton motorin taşıyor, Marmara Denizi doğusunda Tuzla demirleme sahasına yaklaşıyorsunuz. İzmit Körfezi\'ndeki TÜPRAŞ İzmit rafineri terminaline gidiyorsunuz. Kiracının operasyon koordinatörü son iki saattir uydu telefonunuzu sürekli arayarak, demir atmadan doğrudan rıhtıma yanaşmanızı talep ediyor — rıhtım yeni boşalmış ve başka bir gemi planlanmadan önce 4 saatlik bir pencere var. Bu pencereyi kaçırırsanız bir sonraki müsait rıhtım 3 gün sonra ve kiracı sürestarya talepleri ile olası sözleşme feshi konusunda uyardı. İzmit\'teki acenteniz rıhtımın hazır olduğunu doğruluyor ancak Tuzla pilot istasyonunda pilot yetersizliği nedeniyle 2 saatlik gecikme olduğunu — dört gemi beklerken yalnızca iki pilotun müsait olduğunu bildiriyor. Hava kötüleşiyor: GB rüzgarı 25 knot\'a yükseldi ve akşama kadar 35-40 knot\'a çıkması ve İzmit Körfezi açık yaklaşımlarında deniz durumu 4-5 bekleniyor. Baş Mühendis az önce ana makine regülatörünün aralıklı dalgalanmalar gösterdiğini bildirdi — motor devri zaman zaman stabilize olmadan önce 15-20 RPM sıçrıyor. Regülatör kontrol ünitesi sorunu olarak değerlendiriyor, şimdilik tehlikeli değil, ancak bir sonraki limanda incelenmesini öneriyor. DPA (Kıyıdaki Atanmış Kişi) sizi en son 4 saat önce aradı ve regülatör sorunuyla hava durumu kötüleşmesinden haberdar değil. Gemide 16 mürettebat var. İzmit Körfezi yaklaşımından geçişiniz, kısıtlı genişlikli kanal, birden fazla feribot ve Tuzla tersane bölgesini geçen birkaç keskin dönüş içeren pilot navigasyonu gerektiriyor.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Zabit varış hazırlığında — kargo planı ve bağlama planı kontrolü. İkinci Zabit köprü nöbetinde dümenci ile. Baş Mühendis makine dairesinde regülatör sorununu izliyor. Lostromo bağlama istasyonlarını hazırlıyor.',
                'available_resources'  => 'Ana makine 4.800 kW (regülatör dalgalanması), tek CPP, baş itici 350 kW, iki radar, ECDIS, AIS, VHF (Kanal 16, 12 İzmit VTS, 14 pilot), GPS, iskandil, uydu telefonu, e-posta, ISGOTT, şirket SMS (kaptanın geçersiz kılma yetkisi prosedürleri dahil), ISM belgeleri, 6 tank için kargo izleme sistemi, bağlama ekipmanları, çıpa donanımı.',
                'current_conditions'   => 'Rüzgar GB 25 knot artarak 35-40 olacak, deniz durumu 3 artıyor, görüş iyi (8+ NM), akıntı zayıf. Tuzla\'ya 12 NM, hız 11 knot. Pilot gecikmesi en az 2 saat. Kiracı direkt yanaşma talep ediyor, rıhtım penceresi 4 saat. Regülatör aralıklı ±15-20 RPM dalgalanma. DPA bilgilendirilmemiş. 16 mürettebat.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан каботажного танкера MV Kocaeli Pride (7 500 DWT, 108 м, осадка 7,8 м), 6 800 т дизтоплива. Подходите к якорной стоянке Тузла в Мраморном море, назначение — терминал НПЗ ТУПРАШ в заливе Измит. Фрахтователь настаивает швартоваться немедленно — окно 4 часа, иначе ожидание 3 дня с демерреджем. Лоцманская задержка 2 часа (нехватка лоцманов). Ветер ЮЗ 25 уз, к вечеру 35–40. Стармех доложил: регулятор ГД даёт скачки ±15–20 об/мин, рекомендует проверку. DPA не уведомлён. 16 членов экипажа. Подход к Измиту — узкий канал с паромами, требуется лоцман.',
                'your_position'       => 'Рубка, командование. Старпом — подготовка к приходу. 2-й помощник на вахте. Стармех — машинное отделение.',
                'available_resources'  => 'ГД 4 800 кВт (дефект регулятора), CPP, носовое подруливающее 350 кВт, два радара, ECDIS, AIS, УКВ, спутниковый телефон, ISGOTT, ISM документация.',
                'current_conditions'   => 'Ветер ЮЗ 25 уз → 35–40, волнение растёт, видимость хорошая. До Тузлы 12 миль. Лоцман +2 ч. Фрахтователь давит. Регулятор нестабилен. DPA не в курсе.',
            ],
            'az' => [
                'situation'           => 'MV Kocaeli Pride-ın kapitanısınız — 7.500 DWT sahil tankeri (108 m, su çəkimi 7,8 m), 6.800 t dizel yanacaq. Mərmərə dənizində Tuzla lövbər sahəsinə yaxınlaşırsınız, İzmit TÜPRAŞ terminalına gedirsiniz. Fraxtçı dərhal rıhtıma yanaşmağı tələb edir — pəncərə 4 saat, əks halda 3 gün gözləmə. Pilot gecikməsi 2 saat. Külək CQ 25 düyün, axşama 35–40. Baş mühəndis regulyator problemini bildirdi (±15–20 RPM). DPA məlumatlandırılmayıb. 16 nəfər ekipaj.',
                'your_position'       => 'Kapitanlıq körpüsü. Baş zabit — gəliş hazırlığı. 2-ci zabit vaxta. Baş mühəndis maşın şöbəsində.',
                'available_resources'  => 'Baş mühərrik 4800 kVt (regulyator problemi), CPP, baş itələyici 350 kVt, iki radar, ECDIS, AIS, VHF, peyk telefonu, ISGOTT, ISM sənədləri.',
                'current_conditions'   => 'Külək CQ 25→35–40 düyün, dalğa artır, görmə yaxşı. Tuzlaya 12 mil. Pilot +2 saat. Fraxtçı təzyiq edir. Regulyator qeyri-sabit. DPA xəbərsiz.',
            ],
        ],
        'decision_prompt'      => 'How will you manage these conflicting pressures and make a safe arrival decision? Address: your response to the charterer\'s demand for immediate berthing, whether you will proceed without waiting for the pilot given the delay, your assessment of the engine governor issue and its implications for a restricted-water transit, the deteriorating weather and its effect on your berthing plan, and how you exercise your authority as Master under ISM Code Section 5.',
        'decision_prompt_i18n' => [
            'tr' => 'Bu çatışan baskıları nasıl yönetecek ve güvenli varış kararını nasıl vereceksiniz? Ele alınacak konular: kiracının anında yanaşma talebine yanıtınız, pilot gecikmesi nedeniyle pilotsuz devam edip etmeyeceğiniz, regülatör sorununun kısıtlı sularda geçiş için değerlendirmesi, kötüleşen havanın yanaşma planına etkisi ve ISM Kod Bölüm 5 kapsamında kaptan olarak yetkilerinizi nasıl kullanacağınız.',
            'ru' => 'Как вы управляете конфликтующими давлениями? Ответ фрахтователю, решение о лоцмане, оценка дефекта регулятора для стеснённых вод, ухудшение погоды, применение полномочий капитана по ISM Код Раздел 5.',
            'az' => 'Ziddiyyətli təzyiqləri necə idarə edəcəksiniz? Fraxtçının tələbinə cavab, pilot gözləmədən davam qərarı, regulyator probleminin dar sularda qiymətləndirilməsi, pisləşən hava, ISM Kod Bölmə 5 üzrə kapitan səlahiyyəti.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'command_authority_exercise',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Yields to charterer pressure without independent assessment. Agrees to bypass pilotage and proceed directly to berth. Does not invoke Master\'s overriding authority. Treats commercial deadline as the primary decision driver.',
                    '2' => 'Shows some resistance to charterer demands but ultimately compromises safety for commercial convenience. Aware of Master\'s authority in principle but does not exercise it decisively. Defers critical decisions to shore management.',
                    '3' => 'Clearly exercises Master\'s overriding authority per ISM Code Section 5. Informs the charterer that the berthing decision will be based on safety assessment, not commercial pressure. Contacts the DPA to report the situation including the governor issue and weather deterioration. Documents the charterer\'s demands and the Master\'s response in the deck log. Makes an independent decision on whether to proceed or anchor.',
                    '4' => 'Strong command presence: formally invokes ISM Code Section 5 in communication with all parties. Sends a written message (email) to the charterer, company, and DPA clearly stating that safety considerations will govern the arrival timeline. Specifies the factors: engine governor uncertainty, weather forecast, pilot delay. Does not negotiate on safety. Instructs the agent to inform the terminal that the vessel will arrive when conditions permit safe berthing. Keeps company fully informed but makes the decision independently as Master.',
                    '5' => 'Expert command authority: proactively manages all stakeholders from a position of informed authority. Before the charterer\'s pressure becomes a confrontation, contacts the DPA and company to explain the full picture — governor issue, weather, pilot delay — and obtains their support for a safety-first approach. Formally responds to the charterer in writing referencing ISM Code Section 5 and SOLAS V Regulation 34.1, stating that the Master will not be pressured into unsafe operations. Simultaneously works constructively to minimize delay: explores whether a pilot can be prioritized, whether an earlier weather window exists, whether the berth window can be extended. Demonstrates that exercising authority is not about refusing commercial needs but about ensuring they are met safely.',
                ],
            ],
            [
                'axis'   => 'safety_risk_assessment',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No assessment of the combined risks: engine governor issue, deteriorating weather, and restricted-water pilotage transit. Treats each factor in isolation or ignores them. Does not recognize the compound risk when multiple factors degrade simultaneously.',
                    '2' => 'Identifies the individual risks but does not assess how they interact. Notes the weather is getting worse and the governor is unreliable but does not consider what happens if the governor fails during the restricted approach to Izmit in high winds.',
                    '3' => 'Conducts a structured risk assessment: evaluates the governor issue with the Chief Engineer to determine if it could cause loss of propulsion during a critical manoeuvre, assesses the weather window (current vs forecast — is there time to berth safely before conditions deteriorate?), evaluates the approach channel requirements (restricted width, turns, traffic) against the vessel\'s current capabilities (questionable governor, single screw, bow thruster only 350 kW). Reaches a risk-based go/no-go decision.',
                    '4' => 'Thorough compound risk assessment: maps out the failure scenarios — governor failure in the narrow approach at Tuzla shipyard bend with 35-knot crosswind, loss of propulsion near ferry routes, inability to maintain course in the Izmit Bay channel with degraded engine control. Considers the consequences: tanker with 6,800t gas oil grounding or colliding in a busy waterway. Assesses the berth approach: wind limits for the terminal, tug availability, and whether berthing is safe even with pilot if conditions deteriorate. Weighs anchoring at Tuzla as a safe option until governor is investigated and weather passes.',
                    '5' => 'Expert risk synthesis: creates a comprehensive picture of the operational envelope. Consults with C/E on specific failure modes of the governor control unit and whether it could cascade to full engine shutdown. Cross-references weather forecast with terminal wind limits and tug specifications. Calculates the timeline: 2-hour pilot delay means arrival at berth in 3+ hours, by which time forecast shows 35+ knots — potentially above terminal limits. Recognizes that proceeding in hope of beating the weather creates escalating risk with no fallback. Identifies that anchoring at Tuzla allows: governor investigation, weather to pass, pilot availability to improve, and a safe berthing in better conditions — potentially only 12-18 hours delay versus the 3-day delay the charterer threatened. Presents this analysis to the company as a reasoned decision.',
                ],
            ],
            [
                'axis'   => 'stakeholder_communication',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No communication with the DPA about the governor issue or weather. Does not inform the company of the charterer\'s pressure. Handles the situation in isolation without support.',
                    '2' => 'Communicates with some parties but not all. May inform the DPA about the weather but not the governor issue. Does not document the charterer\'s demands. Communication is reactive rather than proactive.',
                    '3' => 'Communicates effectively with all key parties: informs DPA of the governor issue, weather deterioration, and charterer pressure. Contacts Izmit VTS for traffic and weather updates. Discusses pilot arrangements with the agent. Responds to the charterer professionally. Logs all communications.',
                    '4' => 'Proactive multi-stakeholder communication: contacts DPA with a comprehensive situation report covering all factors. Requests company guidance while making clear the Master\'s assessment. Sends the charterer a formal response referencing safety obligations. Coordinates with the agent on pilot scheduling and berth window flexibility. Contacts the terminal directly if needed. Ensures all parties have the same factual picture.',
                    '5' => 'Expert communication management: manages information flow strategically. Provides the DPA a full brief immediately — not waiting for the situation to escalate. Asks the company to engage the charterer at the corporate level to resolve the commercial pressure. Simultaneously works with the agent to find operational solutions (earlier pilot, extended berth window, alternative berth). Coordinates with Izmit VTS on the weather situation and any traffic management measures. All communications are documented with timestamps. The result is that all stakeholders are informed, the commercial relationship is preserved where possible, but safety is never compromised.',
                ],
            ],
            [
                'axis'   => 'decision_framework',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No structured decision-making. Reacts to the loudest voice (the charterer) without analyzing the situation. No consideration of alternatives. No documentation.',
                    '2' => 'Makes a decision but cannot articulate the reasoning. Chooses an option without evaluating alternatives. Limited documentation. Does not apply ISM risk assessment procedures.',
                    '3' => 'Structured decision: identifies the options (proceed immediately, wait for pilot, anchor and wait for weather, anchor and investigate governor), evaluates each against safety criteria, selects the safest option that still addresses commercial needs where possible, documents the decision rationale in the deck log.',
                    '4' => 'Formal risk-based decision: uses a structured approach (ISM risk assessment matrix or similar) to evaluate each option. Documents: the hazards identified, the risk level for each option, the mitigation measures available, and the residual risk. Selects the option with acceptable residual risk. Communicates the decision with its rationale to all stakeholders. Sets review points (e.g., reassess in 2 hours when weather update available).',
                    '5' => 'Expert decision architecture: applies a comprehensive decision framework that considers safety, commercial, regulatory, and reputational factors. For each option, maps the best-case, most-likely, and worst-case outcomes. Recognizes that the worst case for proceeding (governor failure in restricted waters with deteriorating weather and a gas oil cargo) is catastrophic and irreversible, while the worst case for waiting (loss of berth window, 3-day delay, demurrage) is commercially painful but recoverable. This asymmetry clearly favours the safe option. Documents everything. Plans for contingencies even within the chosen option. Sets clear triggers for escalation.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Accepting the charterer demand to proceed directly to berth without independent safety assessment of the governor issue and weather', 'severity' => 'critical'],
            ['flag' => 'Proceeding through the restricted Izmit Bay approach without a pilot when pilotage is required and engine reliability is questionable', 'severity' => 'critical'],
            ['flag' => 'Not reporting the main engine governor fault to the DPA and company — ISM Code non-compliance', 'severity' => 'critical'],
            ['flag' => 'No weather assessment before committing to the approach — ignoring a forecast of 35-40 knots', 'severity' => 'major'],
            ['flag' => 'Not documenting the charterer pressure and Master\'s decision rationale in the deck log', 'severity' => 'major'],
            ['flag' => 'Failing to consider anchoring as a safe alternative while the governor is investigated and weather passes', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'ISM Code (International Safety Management Code) — Section 5: Master\'s Responsibility and Authority',
            'SOLAS Chapter V Regulation 34.1 — Master\'s Discretion for Safe Navigation',
            'STCW Code A-VIII/2 — Watchkeeping Principles and Fitness for Duty',
            'Turkish Maritime Pilotage Regulations — compulsory pilotage areas in Izmit Bay',
            'MARPOL Annex I — Tanker operational requirements and pollution prevention',
            'OCIMF/ISGOTT (International Safety Guide for Oil Tankers and Terminals) — terminal approach and berth safety',
            'Company SMS — Master\'s Standing Orders, arrival procedures, and commercial pressure reporting',
        ],
        'red_flags_json' => [
            'Yielding to charterer pressure and bypassing safety assessment to meet a commercial deadline',
            'Proceeding to berth without a pilot in restricted waters with an unreliable engine governor',
            'Not reporting the governor defect to the DPA — the ISM link between ship and shore is broken',
            'Ignoring the deteriorating weather forecast when planning a tanker berthing operation',
            'No documentation of the decision-making process or the commercial pressure received',
            'Treating the 4-hour berth window as an absolute constraint rather than one factor in a risk assessment',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 3 — TECH_DEPTH (ENG_MACH) — ECDIS/GPS failure with suspected jamming in Marmara Sea
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S03_TECH_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Marmara Carrier, a 3,200 DWT coastal cargo vessel (78 metres LOA, beam 12.4 metres, draft 4.8 metres) transiting the Sea of Marmara westbound from Izmit toward the Dardanelles. It is 2230 local time and you are passing north of Marmara Island. Ten minutes ago your primary ECDIS display froze — the chart image is static and no longer updating vessel position or AIS targets. The Second Officer attempted a restart but the system locked in a boot loop. Your backup ECDIS is running but its GPS-derived position has begun jumping erratically — the vessel\'s displayed position shifts by 300 to 800 metres every 30 seconds, placing the vessel alternately on land and in deep water. You suspect GPS interference: the Marmara Sea region has experienced documented GPS jamming incidents, and the military exercise area TURNHOS-N (Turkish naval exercise zone) is active 15 nautical miles to the south. Your AIS display is also affected — other vessels\' AIS positions do not match their radar returns. Some AIS contacts appear 500 metres offset from their actual radar positions. The traffic situation is significant: the Marmara Sea is one of the busiest waterways in Turkey, with heavy east-west traffic (vessels transiting between the Bosphorus and Dardanelles), north-south ferry traffic between the northern and southern Marmara coasts, and local fishing activity. Your radar displays show 14 contacts within 6 nautical miles. The closest is a large merchant vessel 1.2 NM on your port bow on a reciprocal course. Visibility is good (6+ NM) but it is night and visual identification of vessels is limited to navigation lights. Your paper chart portfolio for the Marmara Sea is on board and was last corrected 3 weeks ago.',
                'your_position'       => 'Wheelhouse, command. Second Officer on watch, helmsman on manual steering. Chief Officer called to the bridge when ECDIS failed. One AB on lookout. Engine room unmanned (UMS mode), Chief Engineer on call.',
                'available_resources'  => 'Two radars: X-band at 6 NM range, S-band at 12 NM range — both functioning normally and unaffected by GPS issues. AIS transponder transmitting (but own position data unreliable due to GPS). Backup ECDIS running with erratic GPS input. Paper chart portfolio for Sea of Marmara (corrected 3 weeks ago). Magnetic compass and gyrocompass (both reliable). VHF radio: Ch 16, Ch 11 for Marmara VTS sectors. Echo sounder operational. Parallel index lines set on radar for Marmara Island coast. Radar ARPA/target tracking functional. Binoculars, hand-bearing compass for visual bearings. Spotlight. Navigation lights verified. Log (speed through water). Main engine operating normally.',
                'current_conditions'   => 'Night (2230 local), visibility 6+ NM, wind NW 12 knots, sea state 2, current weak westerly. Primary ECDIS frozen (in boot loop). Backup ECDIS showing erratic GPS positions (300-800m jumps). AIS positions offset from radar by up to 500m. Suspected GPS jamming in the region. 14 radar contacts within 6 NM. Closest contact 1.2 NM on port bow, reciprocal course. Heavy traffic east-west and ferry north-south. Paper charts on board. Radars functioning normally. Vessel speed 10 knots, course 250°T.',
            ],
            'tr' => [
                'situation'           => 'MV Marmara Carrier\'ın kaptanısınız — 3.200 DWT kıyı yük gemisi (78 m LOA, genişlik 12,4 m, draft 4,8 m), İzmit\'ten Çanakkale\'ye batı yönünde Marmara Denizi\'ni transit geçiyor. Yerel saat 22:30 ve Marmara Adası kuzeyinden geçiyorsunuz. On dakika önce birincil ECDIS ekranınız dondu — harita görüntüsü statik ve artık gemi pozisyonunu veya AIS hedeflerini güncellemiyor. İkinci Zabit yeniden başlatmayı denedi ama sistem açılış döngüsüne girdi. Yedek ECDIS çalışıyor ama GPS kaynaklı pozisyon düzensiz sıçramalar yapmaya başladı — gösterilen pozisyon her 30 saniyede 300 ila 800 metre kayıyor, gemiyi alternatif olarak karada veya derin suda gösteriyor. GPS girişimi şüpheleniyorsunuz: Marmara Denizi bölgesi belgelenmiş GPS karıştırma olayları yaşamış ve TURNHOS-N askeri tatbikat alanı 15 deniz mili güneyde aktif. AIS ekranınız da etkilenmiş — diğer gemilerin AIS pozisyonları radar ekolarıyla uyuşmuyor, bazı AIS temaları gerçek radar pozisyonlarından 500 metre kaymış görünüyor. Trafik durumu önemli: Marmara Denizi Türkiye\'nin en yoğun suyollarından biri — yoğun doğu-batı transit trafiği, kuzey-güney feribot trafiği ve yerel balıkçılık. Radarınızda 6 NM içinde 14 temas var. En yakını iskele baş omuzluğunda 1,2 NM\'de ters rotada büyük bir ticari gemi. Görüş iyi (6+ NM) ama gece ve görsel tanımlama seyir fenerleriyle sınırlı. Marmara Denizi kağıt harita portföyünüz gemide ve 3 hafta önce son düzeltmesi yapılmış.',
                'your_position'       => 'Kaptan köprüsü, komuta. İkinci Zabit nöbette, dümenci manuel dümen başında. ECDIS arızasında Baş Zabit köprüye çağrıldı. Bir AB gözcü. Makine dairesi insansız (UMS), Baş Mühendis çağrı üzerine hazır.',
                'available_resources'  => 'İki radar: X-band 6 NM, S-band 12 NM — normal çalışıyor, GPS\'ten etkilenmemiş. AIS vericisi çalışıyor (ama kendi pozisyon verisi güvenilmez). Yedek ECDIS düzensiz GPS girişiyle çalışıyor. Marmara Denizi kağıt harita portföyü (3 hafta önce düzeltilmiş). Manyetik pusula ve cayro pusula (güvenilir). VHF (Kanal 16, Kanal 11 Marmara VTS). İskandil. Radarda paralel indeks çizgileri. Radar ARPA/hedef takibi. Dürbün, el kerteriz pusulası. Spot ışık. Seyir fenerleri. Parakete. Ana makine normal.',
                'current_conditions'   => 'Gece (22:30), görüş 6+ NM, rüzgar KB 12 knot, deniz durumu 2, akıntı zayıf batı. Birincil ECDIS donmuş. Yedek ECDIS düzensiz GPS (300-800m sıçrama). AIS pozisyonları radardan 500m kaymış. GPS karıştırma şüphesi. 6 NM\'de 14 radar teması. En yakın 1,2 NM iskele baş, ters rota. Yoğun trafik. Kağıt haritalar mevcut. Radarlar normal. Hız 10 knot, rota 250°T.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан каботажного судна MV Marmara Carrier (3 200 DWT, 78 м, осадка 4,8 м), следуете на запад по Мраморному морю от Измита к Дарданеллам. 22:30 местного, проходите севернее о. Мармара. Основная ЭКНИС зависла — не обновляется. Резервная ЭКНИС показывает скачки GPS-позиции на 300–800 м каждые 30 сек. Подозрение на GPS-помехи (район военных учений TURNHOS-N активен в 15 милях). AIS-позиции смещены от радарных на 500 м. На радаре 14 контактов в 6 милях, ближайший — 1,2 мили по левому борту, встречный. Радары работают нормально. Бумажные карты на борту (корректура 3 нед. назад). Ночь, видимость 6+ миль.',
                'your_position'       => 'Рубка, командование. 2-й помощник на вахте, рулевой на ручном. Старпом вызван. Матрос — наблюдатель. Машина — безвахтенный режим.',
                'available_resources'  => 'Два радара (X/S-band) — рабочие. AIS (позиция ненадёжна). Резервная ЭКНИС (GPS нестабилен). Бумажные карты. Магнитный и гирокомпас (исправны). УКВ, эхолот, ARPA. Лаг.',
                'current_conditions'   => 'Ночь, видимость хорошая, ветер СЗ 12 уз. Основная ЭКНИС — отказ. GPS — скачки. AIS — смещение. 14 контактов на радаре. Скорость 10 уз, курс 250°.',
            ],
            'az' => [
                'situation'           => 'MV Marmara Carrier-ın kapitanısınız — 3.200 DWT sahil yük gəmisi (78 m, su çəkimi 4,8 m), İzmitdən Çanaqqaləyə Mərmərə dənizini keçir. 22:30, Mərmərə adasının şimalından keçirsiniz. Əsas ECDIS donub — yenilənmir. Ehtiyat ECDIS GPS-dən düzensiz sıçramalar göstərir (300–800 m). TURNHOS-N hərbi təlim zonası 15 mil cənubda aktivdir — GPS müdaxiləsi şübhəsi. AIS pozisiyaları radardan 500 m kənarlaşıb. 6 mil daxilində 14 radar əlaqəsi, ən yaxını 1,2 mil sol tərəfdə əks kurs. Radarlar normal işləyir. Kağız xəritələr var.',
                'your_position'       => 'Kapitanlıq körpüsü. 2-ci zabit vaxta, sükan əl ilə. Baş zabit çağırılıb. Matros müşahidəçi.',
                'available_resources'  => 'İki radar (X/S-band) normal, AIS (pozisiya etibarsız), ehtiyat ECDIS (GPS qeyri-sabit), kağız xəritələr, kompaslar, VHF, exolot, ARPA.',
                'current_conditions'   => 'Gecə, görmə 6+ mil, külək ŞQ 12 düyün. ECDIS nasaz. GPS sıçrayır. AIS fərqli. 14 əlaqə. Sürət 10 düyün, kurs 250°.',
            ],
        ],
        'decision_prompt'      => 'Describe your immediate response to the ECDIS and GPS failures. Address: your actions to recover or work around the failed systems, how you will verify your position using non-GPS methods, your radar navigation strategy for continuing the transit in heavy traffic, whether and how you will notify Marmara VTS and surrounding traffic, and any changes to your passage plan or speed.',
        'decision_prompt_i18n' => [
            'tr' => 'ECDIS ve GPS arızalarına anındaki müdahalenizi açıklayın. Ele alınacak konular: arızalı sistemleri kurtarma veya alternatif yöntemler, GPS dışı yöntemlerle pozisyon doğrulama, yoğun trafikte radar navigasyon stratejisi, Marmara VTS ve çevre trafiği bilgilendirme, geçiş planı veya hız değişiklikleri.',
            'ru' => 'Опишите немедленные действия при отказе ЭКНИС и GPS: восстановление или обход систем, определение места без GPS, радарная навигация в плотном трафике, уведомление VTS, изменения в плане перехода.',
            'az' => 'ECDIS və GPS nasazlığına dərhal reaksiyanızı təsvir edin: sistemlərin bərpası, GPS-siz pozisiya müəyyənləşdirmə, sıx trafikdə radar naviqasiyası, VTS məlumatlandırma, keçid planında dəyişikliklər.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'electronic_failure_response',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Continues to rely on the erratic backup ECDIS GPS position. No attempt to troubleshoot the primary ECDIS. Does not recognize that the GPS jamming affects all GPS-dependent systems (ECDIS, AIS). No reversion to alternative navigation methods.',
                    '2' => 'Recognizes the ECDIS failure but focuses only on trying to restart the system. Does not consider GPS jamming as the root cause. Does not connect the ECDIS problem with the AIS position offsets. Eventually reverts to radar but does not set up systematic radar navigation.',
                    '3' => 'Correct failure response: immediately stops relying on GPS-derived position data from all systems. Recognizes the link between ECDIS failure, erratic GPS, and AIS offsets — diagnoses probable GPS jamming. Activates paper chart navigation as primary method. Configures radar with parallel index lines for coastal navigation. Verifies position by radar ranges and bearings to charted landmarks. Cross-checks gyro compass heading against magnetic compass to ensure heading references are still reliable.',
                    '4' => 'Thorough system recovery: isolates the GPS problem from the radar and compass systems, confirming which systems are affected and which are reliable. Notes that radar (operates independently of GPS) and compass (magnetic and gyro) are unaffected. Switches AIS display to radar-overlay mode and uses radar-confirmed positions rather than AIS positions for traffic management. Attempts primary ECDIS recovery using hardware reset. Configures backup ECDIS to dead-reckoning mode if possible, disabling GPS input. Sets up paper chart with plotted position from radar fix. Assigns C/O to maintain the paper chart plot. Records all system failures and actions in the log.',
                    '5' => 'Expert electronic casualty management: conducts a systematic diagnosis — primary ECDIS hardware failure (separate issue, may be coincidental or related), GPS jamming affecting all GNSS-dependent systems, AIS position reliability degraded. Immediately switches to Mode 2 navigation (radar + paper chart primary). Configures radar with electronic bearing lines and variable range markers for position fixing. Sets up parallel indexing on Marmara Island coast for continuous track monitoring. Checks if vessel\'s AIS is transmitting the erratic position (potentially dangerous — other vessels may be receiving incorrect position data). If so, considers temporarily reducing AIS transmission power or contacting VTS to advise of the AIS data error. Instructs C/E to check if any engine room systems depend on GPS time synchronization. Creates a documented bridge procedure for the degraded navigation state and briefs all watchkeepers.',
                ],
            ],
            [
                'axis'   => 'position_verification',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No attempt to verify position by non-GPS means. Trusts the erratic GPS display or navigates without knowing the vessel\'s position. No radar position fixing. No visual bearings despite good visibility.',
                    '2' => 'Takes occasional radar ranges but does not systematically fix the vessel\'s position. Does not use multiple methods to cross-check. Unsure how to use radar for position fixing without GPS.',
                    '3' => 'Systematic position fixing: takes radar ranges and bearings to identifiable features on Marmara Island coast. Uses at least two radar ranges to charted objects for a position fix. Plots the fix on the paper chart. Establishes a regular fix interval (every 10-15 minutes or more frequently near hazards). Cross-checks with echo sounder depths against charted depths.',
                    '4' => 'Multi-method position verification: combines radar ranges to two or more targets for a reliable radar fix. Takes visual bearings of lights on Marmara Island and mainland (lighthouse bearings plotted on chart). Uses echo sounder as a continuous position verification tool (depth contour matching). Checks position against known current and leeway to verify dead-reckoning between fixes. Identifies the best radar targets (isolated, charted features with good radar response) and uses them consistently.',
                    '5' => 'Expert position determination: establishes a robust position-fixing regime using all available independent methods — radar ranges (most accurate), radar bearings (less accurate, used as cross-checks), visual bearings of lighthouses and identified shore lights, echo sounder depth matching, and dead-reckoning between fixes using reliable speed log and compass. Immediately takes a high-confidence radar fix to establish the vessel\'s position on the paper chart as the baseline. Sets up parallel indexing on two or more targets to provide continuous cross-track monitoring without needing repeated individual fixes. Calculates position accuracy circle for each method and selects the most reliable combination. Increases fix frequency as the vessel approaches the Dardanelles entrance or any navigation hazard.',
                ],
            ],
            [
                'axis'   => 'radar_navigation_strategy',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No coherent radar navigation plan for the transit. Uses radar only to look at contacts occasionally. Does not use radar for position fixing, parallel indexing, or systematic traffic monitoring.',
                    '2' => 'Uses radar for traffic awareness but does not set up systematic collision avoidance. No parallel indexing. ARPA tracking sporadic. Does not adjust radar settings for optimal performance in the Marmara Sea environment.',
                    '3' => 'Effective radar navigation: uses X-band at short range for collision avoidance with ARPA tracking on closest contacts, S-band at longer range for strategic traffic picture. Sets up parallel index lines on the nearest coast for continuous track monitoring. Tracks all contacts within potential risk range with CPA/TCPA assessment. Adjusts course or speed when CPA is unsatisfactory.',
                    '4' => 'Advanced radar utilization: optimizes both radars for complementary roles. X-band for precise close-range navigation and target tracking (better resolution for small contacts), S-band for overview and early detection. Parallel indexing on Marmara Island coastline for continuous cross-track position. ARPA tracking on all contacts with CPA alarm set to 1.0 NM. Uses radar overlay on the paper chart (by plotting radar-derived positions) to maintain a complete navigation picture. Adjusts radar gain and clutter controls for night conditions to detect small fishing vessels.',
                    '5' => 'Expert radar-primary navigation: recognizes that with GPS unreliable, radar becomes the primary navigation sensor and treats it accordingly. Configures a comprehensive radar navigation setup: parallel indexing on two targets for both cross-track and along-track monitoring, ARPA tracking on all significant contacts, clearing bearings on radar for key hazards (shoal areas, traffic convergence points). Uses the radar for both navigation and collision avoidance simultaneously by assigning specific tasks to each radar (X-band for collision avoidance, S-band for navigation and overview). Briefs the bridge team on radar-primary procedures — every contact must be tracked and assessed, no assumptions based on AIS data alone. Identifies radar-conspicuous navigation marks on the paper chart and uses them as waypoints for the transit. Plans the approach to the Dardanelles using radar-derived positions for each course alteration point.',
                ],
            ],
            [
                'axis'   => 'communication_and_passage_plan',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No notification to VTS of the navigation equipment failure. No communication with other traffic about the degraded situation. Continues the passage plan without modification despite loss of primary navigation systems.',
                    '2' => 'Considers contacting VTS but does not prioritize it. No modification to the passage plan despite the navigation casualty. Does not warn other traffic about own vessel\'s AIS position inaccuracy.',
                    '3' => 'Appropriate communication: contacts Marmara VTS on Channel 11 to report ECDIS failure and suspected GPS jamming. Advises VTS that own AIS position may be inaccurate. Requests traffic information for the westbound route. Reviews the passage plan and considers whether to reduce speed or alter course to give wider margins from hazards. Reports the equipment failure to the company.',
                    '4' => 'Proactive communication and planning: notifies VTS immediately with details of the equipment failures. Requests that VTS advise other vessels that own ship\'s AIS position is unreliable. Asks VTS if other vessels have reported GPS anomalies in the area (to confirm jamming hypothesis). Modifies the passage plan to increase safety margins from all hazards — shifts to deeper water where possible, increases planned CPA distances from traffic, reduces speed to allow more time for radar navigation. Reports to company and DPA. Issues a NAVTEX/VHF broadcast warning if appropriate.',
                    '5' => 'Expert situational management: immediately contacts VTS with a comprehensive report: primary ECDIS failed, GPS suspected jamming, AIS positions unreliable for own and possibly other vessels, vessel navigating by radar and paper chart. Requests VTS provide radar-based traffic information. Asks VTS to investigate whether other vessels in the area are experiencing GPS issues (which would confirm regional jamming). If confirmed, requests VTS consider issuing a navigational warning. Modifies passage plan significantly: reduces speed to 7-8 knots to allow more time for manual radar navigation, plots a track with increased clearances from all charted hazards, identifies radar-conspicuous waypoints for each course change, considers whether to anchor until GPS is restored if the situation deteriorates further. Reports the suspected GPS jamming to NAVAREA III coordinator through the company (for safety of other vessels). Ensures deck log has complete record of the incident.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Continuing to rely on GPS-derived positions (from either ECDIS or AIS) when GPS is clearly unreliable — navigating on false position data', 'severity' => 'critical'],
            ['flag' => 'Not reverting to radar position fixing and paper chart when ECDIS is unavailable — proceeding without a verified position in heavy traffic at night', 'severity' => 'critical'],
            ['flag' => 'No notification to Marmara VTS about ECDIS failure and suspected GPS jamming — other vessels may be affected', 'severity' => 'critical'],
            ['flag' => 'Not reducing speed when the primary navigation system has failed — maintaining full transit speed in degraded conditions', 'severity' => 'major'],
            ['flag' => 'Not recognizing that own vessel AIS is broadcasting incorrect position data — creating a hazard for other vessels relying on AIS', 'severity' => 'major'],
            ['flag' => 'No log entry documenting the equipment failures, suspected GPS jamming, and corrective actions taken', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'SOLAS Chapter V Regulation 19 — Carriage requirements for shipborne navigational systems and equipment',
            'SOLAS Chapter V Regulation 27 — Nautical charts and nautical publications (paper chart backup)',
            'IMO Resolution MSC.232(82) — Revised Performance Standards for ECDIS',
            'IMO SN.1/Circ.334 — Guidance for Good Practice in ECDIS (equipment failure procedures)',
            'IMO MSC.1/Circ.1575 — Guidelines on GNSS Vulnerability (GPS jamming/spoofing awareness)',
            'STCW Code A-II/1 — Competence in radar navigation and position fixing by all means',
            'Turkish Maritime VTS Regulations — mandatory reporting of navigation equipment defects',
        ],
        'red_flags_json' => [
            'Trusting the frozen ECDIS or erratic GPS positions and continuing to navigate based on unreliable data',
            'Not establishing a radar-based position fix when GPS is obviously compromised',
            'Failing to notify VTS that vessel navigation systems are degraded and AIS position may be incorrect',
            'Maintaining full transit speed at night with degraded navigation capability in heavy traffic',
            'Not preparing paper charts as backup when both ECDIS units are unavailable or unreliable',
            'Ignoring the AIS discrepancies as a clue to the GPS jamming — not connecting the symptoms to diagnose the root cause',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 4 — RISK_MGMT (CARGO_EMG) — Cargo shift in Aegean gale with ISM/PSC implications
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S04_RISK_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Aegean Trader, a 4,200 DWT general cargo vessel (85 metres LOA, beam 13.8 metres, draft 5.6 metres) bound for Antalya from Volos, Greece with a mixed cargo: 1,800 tonnes of steel coils in the lower hold (No. 2 hold) and 600 tonnes of sawn timber as deck cargo. You are in the southern Aegean Sea, approximately 20 nautical miles northwest of Rhodes, when a rapidly developing NW gale (Etesian wind — meltemi) has exceeded the forecast. The current conditions are wind NW force 7 (35 knots) with gusts to force 8, seas 3 to 4 metres with a short steep swell typical of the Aegean. The vessel has developed a 5-degree starboard list over the past 30 minutes. The Bosun has just reported from No. 2 hold: two of the eight wire rope lashings securing the steel coils have parted, and a third is visibly stretched. The coils, each weighing approximately 22 tonnes, have shifted approximately 15 centimetres to starboard. On deck, the timber cargo has begun to work against its lashings — the Bosun can see movement on the starboard stack with each roll. The vessel is rolling 15-18 degrees with a noticeable hang to starboard at the end of each roll cycle. Your stability booklet shows that at the current loading condition the vessel\'s GM was calculated as 0.45 metres at departure — already at the lower end of acceptable. With the cargo shift, the effective GM may now be reduced. Antalya is 14 hours away at the current speed of 8 knots (reduced from 11 due to weather). The nearest sheltered anchorage is Marmaris, approximately 35 nautical miles to the NE (5 hours). Antalya is known for active PSC targeting of general cargo vessels, and your vessel was last inspected 14 months ago. Your ISM system requires you to report any cargo-related incident to the DPA within 2 hours.',
                'your_position'       => 'Wheelhouse, command. Chief Officer on the bridge assisting with navigation. Bosun on deck at No. 2 hold (reported by radio). Second Officer below checking stability calculations. One AB at the helm. Chief Engineer in engine room — main engine running normally.',
                'available_resources'  => 'Stability booklet and loading computer (software), inclinometer on the bridge (showing 5° starboard list with roll amplitude 15-18° both sides), cargo securing manual (CSM), lashing materials: additional wire ropes, turnbuckles, chain lashings, timber dunnage in boatswain store. Ballast system: double bottom tanks and peak tanks, ballast pump 200 m³/h. Two radars, ECDIS, AIS, GPS. VHF radio. Satellite phone for company communication. ISM documentation and non-conformity report forms. Weather forecast service via Navtex and internet. 14 crew total. Vessel intact — no structural damage reported. Rescue coordination: Turkish Coast Guard MRCC Antalya.',
                'current_conditions'   => 'Wind NW 35 knots gusting 40, sea state 3-4m with steep short swell, vessel rolling 15-18° with 5° starboard list and starboard hang. No. 2 hold: 2 of 8 steel coil lashings parted, 1 stretched, coils shifted 15cm starboard. Deck timber cargo showing movement. GM at departure 0.45m, likely reduced by shift. 14 hours to Antalya, 5 hours to Marmaris shelter. Weather forecast: NW gale continuing 24-36 hours. PSC active in Antalya. ISM 2-hour incident reporting requirement. Speed reduced to 8 knots. Heading approximately SE.',
            ],
            'tr' => [
                'situation'           => 'MV Aegean Trader\'ın kaptanısınız — 4.200 DWT genel kargo gemisi (85 m LOA, genişlik 13,8 m, draft 5,6 m), Volos\'tan Antalya\'ya karışık yükle gidiyor: alt ambar (No. 2) de 1.800 ton çelik bobin ve güvertede 600 ton biçilmiş kereste. Güney Ege\'desiniz, Rodos\'un yaklaşık 20 deniz mili kuzeybatısında, hızla gelişen KB fırtınası (meltem) tahminleri aşmış durumda. Mevcut koşullar: rüzgar KB kuvvet 7 (35 knot) hamlelerde kuvvet 8, dalga 3-4 metre kısa ve dik Ege karakterinde. Gemi son 30 dakikada 5 derece sancak meyil verdi. Lostromo az önce No. 2 ambardan bildirdi: çelik bobinleri sabitleyen sekiz tel halat bağlamasından ikisi kopmuş, üçüncüsü görünür şekilde gerilmiş. Her biri yaklaşık 22 ton ağırlığındaki bobinler yaklaşık 15 santimetre sancağa kaymış. Güvertede kereste yükü bağlamalarına karşı hareket etmeye başlamış — Lostromo her yalpada sancak istifinde hareket görebiliyor. Gemi 15-18 derece yalpalamayla sancak tarafında belirgin bir takılma gösteriyor. Stabilite kitapçığınıza göre mevcut yükleme durumunda kalkışta GM 0,45 metre olarak hesaplanmıştı — kabul edilebilirin alt sınırında. Yük kaymasıyla etkin GM muhtemelen azalmış. Antalya mevcut 8 knot hızla 14 saat uzaklıkta (havadan dolayı 11\'den düşürüldü). En yakın korunaklı demirleme yeri Marmaris, yaklaşık 35 deniz mili KD\'da (5 saat). Antalya\'nın genel kargo gemilerine yönelik aktif PSC denetimiyle bilindiğini ve geminizin son denetiminin 14 ay önce yapıldığını biliyorsunuz. ISM sisteminiz herhangi bir kargo ile ilgili olayı 2 saat içinde DPA\'ya bildirmenizi gerektiriyor.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Zabit köprüde navigasyon yardımı. Lostromo güvertede No. 2 ambar (telsizle bildirdi). İkinci Zabit aşağıda stabilite hesapları yapıyor. Bir AB dümen başında. Baş Mühendis makine dairesinde — ana makine normal.',
                'available_resources'  => 'Stabilite kitapçığı ve yükleme bilgisayarı, köprüde meyil ölçer (5° sancak + 15-18° yalpa), kargo sabitleme el kitabı (CSM), ek bağlama malzemeleri (tel halatlar, gergi cihazları, zincir, kereste takozlar), balast sistemi (çift dip ve pik tankları, 200 m³/h pompa), iki radar, ECDIS, AIS, VHF, uydu telefonu, ISM belgeleri, hava tahmin servisi. 14 mürettebat. Yapısal hasar bildirilmemiş. MRCC Antalya.',
                'current_conditions'   => 'Rüzgar KB 35 knot hamle 40, dalga 3-4m, yalpa 15-18° + 5° sancak meyil ve sancak takılması. No. 2: 8 bağlamadan 2 kopuk, 1 gerilmiş, bobinler 15cm kaymış. Güverte kerestesi hareket ediyor. GM kalkışta 0,45m, muhtemelen azalmış. Antalya 14 saat, Marmaris 5 saat. Fırtına 24-36 saat devam edecek. Antalya\'da aktif PSC. ISM 2 saat bildirim. Hız 8 knot.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Aegean Trader (4 200 DWT, 85 м, осадка 5,6 м). Рейс Волос — Анталья. Груз: 1 800 т стальных рулонов в трюме №2 + 600 т пиломатериалов на палубе. Южное Эгейское море, 20 миль к СЗ от Родоса. Шторм (мельтем) NW 35 уз, порывы 40, волна 3–4 м. Судно получило крен 5° на правый борт. Боцман доложил: 2 из 8 найтовов на рулонах лопнули, 1 натянут, смещение ~15 см вправо. Палубный лес начал двигаться. Качка 15–18° с зависанием вправо. GM при отходе 0,45 м — теперь вероятно меньше. До Антальи 14 ч, до укрытия (Мармарис) 5 ч. Шторм 24–36 ч. Анталья — активный PSC. ISM: доклад DPA в течение 2 ч.',
                'your_position'       => 'Рубка. Старпом на мостике. Боцман на палубе. 2-й помощник считает остойчивость. Рулевой на ручном. Стармех — машинное отделение.',
                'available_resources'  => 'Таблица остойчивости + компьютер, кренометр (5° + качка 15–18°), CSM, доп. найтовы, балластная система (200 м³/ч), два радара, ECDIS, УКВ, спутн. телефон, ISM документация. 14 чел. MRCC Анталья.',
                'current_conditions'   => 'NW 35 уз → 40, волна 3–4 м, крен 5° пр. борт, качка 15–18°. Груз смещён. GM снижен. До Антальи 14 ч, Мармарис 5 ч. Шторм 24–36 ч.',
            ],
            'az' => [
                'situation'           => 'MV Aegean Trader-ın kapitanısınız — 4.200 DWT yük gəmisi (85 m, su çəkimi 5,6 m). Volosdan Antalyaya. Yük: anbar №2-də 1.800 t polad bobinlər + göyərtədə 600 t taxta. Cənubi Egey, Rodosdan 20 mil ŞQ-da. Fırtına (meltem) ŞQ 35 düyün, dalğa 3–4 m. Gəmi 5° sağ yan əyilmə aldı. Lostromo bildirdi: 8 bağlamadan 2 qırılıb, 1 gərilib, bobinlər 15 sm sağa sürüşüb. Göyərtə yükü hərəkətdə. Yalpa 15–18°. Kalkışda GM 0,45 m — indi azalıb. Antalyaya 14 saat, Marmarisə 5 saat. Fırtına 24–36 saat. Antalyada aktiv PSC.',
                'your_position'       => 'Kapitanlıq körpüsü. Baş zabit köprüdə. Lostromo göyərtədə. 2-ci zabit sabitlik hesablayır. Matros sükan başında.',
                'available_resources'  => 'Sabitlik kitabı + kompüter, əyilmə ölçən, CSM, əlavə bağlama materialları, ballast sistemi (200 m³/saat), iki radar, ECDIS, VHF, peyk telefonu, ISM sənədləri. 14 nəfər. MRCC Antalya.',
                'current_conditions'   => 'ŞQ 35→40 düyün, dalğa 3–4 m, 5° əyilmə + yalpa 15–18°. Yük sürüşüb. GM azalıb. Antalya 14 saat, Marmaris 5 saat. Fırtına 24–36 saat.',
            ],
        ],
        'decision_prompt'      => 'How will you manage the developing cargo shift and its safety implications? Address: your immediate actions to assess and correct the vessel\'s stability, the plan for re-securing the cargo considering crew safety in heavy weather, your routing decision (continue to Antalya, divert to Marmaris, or other options), ISM incident reporting to the DPA, and how you will prepare for the likely PSC inspection at your next port.',
        'decision_prompt_i18n' => [
            'tr' => 'Gelişen yük kaymasını ve güvenlik sonuçlarını nasıl yöneteceksiniz? Ele alınacak konular: stabiliteyi değerlendirmek ve düzeltmek için acil eylemleriniz, ağır havada mürettebat güvenliğini gözeterek yükü yeniden sabitleme planı, rota kararınız (Antalya\'ya devam, Marmaris\'e sapma veya diğer seçenekler), DPA\'ya ISM olay bildirimi ve bir sonraki limanda olası PSC denetimine nasıl hazırlanacağınız.',
            'ru' => 'Как будете управлять смещением груза? Немедленные действия по остойчивости, план перекрепления с учётом безопасности экипажа, решение по маршруту (Анталья/Мармарис/другое), доклад DPA по ISM, подготовка к PSC.',
            'az' => 'Yük sürüşməsini necə idarə edəcəksiniz? Sabitliyin qiymətləndirilməsi və düzəldilməsi, ağır havada heyət təhlükəsizliyi ilə yükün yenidən bağlanması, marşrut qərarı, DPA-ya ISM bildirişi, PSC hazırlığı.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'stability_assessment_and_correction',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'No stability assessment after the cargo shift. Does not check the loading computer or stability booklet. No ballast adjustment to correct the list. Does not recognize the significance of a 5-degree list with an initial GM of only 0.45 metres.',
                    '2' => 'Notes the list but does not quantify the stability impact. Considers ballasting but is unsure which tanks to use. Does not calculate the new GM or verify that the vessel still meets minimum stability criteria.',
                    '3' => 'Proper stability response: instructs the Second Officer to recalculate stability with the estimated cargo shift (1,800 tonnes shifted 15cm = shifting moment, plus deck cargo movement). Checks the loading computer with revised weight distribution. Identifies ballast correction: transfer ballast to port double bottom tanks to reduce the list while monitoring GM effect. Ensures that ballasting does not reduce GM further (free surface effect). Verifies that the vessel remains within the minimum stability criteria per the stability booklet.',
                    '4' => 'Thorough stability management: calculates the cargo shifting moment quantitatively — estimates the shifted weight and distance for both the steel coils and timber deck cargo movement. Re-evaluates GM considering the cargo shift, sea state-induced dynamic effects, and free surface from any ballast transfers. Plans ballast operations carefully: uses only full/empty tank transfers to minimize free surface, or uses tanks that are already slack. Monitors the inclinometer continuously during ballast operations. Sets a target list correction (reduce to 2° or less) as an interim measure. Recognizes that the 0.45m initial GM with cargo shift may now be below the IMO minimum (0.15m) and treats the situation as potentially critical.',
                    '5' => 'Expert stability crisis management: immediately assesses whether the vessel is approaching a dangerous stability state. Calculates approximate GM loss from the cargo shift and determines that with initial GM 0.45m and the shift of multiple 22-tonne coils, the remaining GM is critically low. Recognizes that dynamic effects in 3-4m seas with a 5° static list create a risk of progressive cargo shift — each roll drives the coils further starboard in a self-reinforcing cycle. Takes immediate action to arrest the deterioration: alters course to reduce rolling (head/stern to sea or quartering), reduces speed, begins ballast transfer to port. Plans ballast sequence to maximize stability improvement while minimizing free surface at each step. If calculations show GM is below minimum, immediately contacts the flag state and classification society as required. Considers whether the situation requires distress notification. Documents all calculations and decisions.',
                ],
            ],
            [
                'axis'   => 'cargo_resecuring_and_crew_safety',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Orders crew to re-secure cargo immediately regardless of weather conditions. No risk assessment for sending crew into the hold or on deck in force 7-8. No safety precautions for the work.',
                    '2' => 'Recognizes the danger of working on deck/in hold in heavy weather but has no plan to manage the risk. Either sends crew out without adequate precautions or delays all action indefinitely.',
                    '3' => 'Balanced approach: assesses whether re-securing is possible and safe in current conditions. For the hold work (steel coils): may be feasible as the hold provides some shelter, but requires safety precautions — crew in hard hats, safety harnesses, no one positioned downhill of the shifted coils. For deck cargo: likely too dangerous in force 7-8 until weather moderates or vessel reaches shelter. Alters course first to reduce rolling before any crew are sent to work. Establishes safety procedures including a deck watch, communication protocol, and emergency recall plan.',
                    '4' => 'Risk-managed cargo operations: conducts a formal risk assessment before any crew exposure. Prioritizes stabilizing the vessel through ballast and course change first. For the hold: organizes a team with specific safety measures — only experienced crew, two-person minimum, safety harnesses attached to fixed points away from the coils, hard hats, steel-toe boots, boatswain supervising, radio communication with the bridge, immediate recall procedure. No work until rolling is reduced below 10 degrees. For deck timber: defers until in sheltered water (Marmaris) as the risk of crew overboard is unacceptable in current conditions. Documents the risk assessment in the ISM system.',
                    '5' => 'Expert crew safety management: recognizes that the priority order is (1) stabilize the vessel — ballast and course change, (2) prevent further shift — which may be achievable without entering the hold (e.g., securing additional lashings from the hatch coaming), (3) re-secure in sheltered conditions. Makes a clear determination that sending crew into a hold with 22-tonne coils that have partially broken free in heavy weather is extremely dangerous — the coils could shift further during re-securing, crushing the crew. If hold entry is necessary, implements maximum precautions and reduces vessel motion first. For deck cargo, absolutely no deck work in force 7-8 on an 85m vessel. Plans comprehensive re-securing for when the vessel reaches Marmaris shelter. Throughout, communicates clearly with the crew about the risks and the plan, maintaining morale and discipline.',
                ],
            ],
            [
                'axis'   => 'weather_routing_decision',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Continues on the original course to Antalya (14 hours) without considering alternatives. No assessment of whether the vessel can safely withstand 14 more hours of gale conditions with shifted cargo.',
                    '2' => 'Considers diverting but focuses on commercial implications (delay, PSC) rather than safety factors. Hesitates to change the plan because of the schedule.',
                    '3' => 'Sound routing decision: evaluates the options — Antalya (14 hours through continuing gale), Marmaris (5 hours, provides shelter), Rhodes (Greek port, closest but creates port state complications), or heaving to. Considers the stability situation, weather forecast (gale continuing 24-36 hours), and crew ability to re-secure cargo. Selects Marmaris as the safest option: shorter transit means less time in heavy weather with shifted cargo, sheltered anchorage allows safe re-securing, and it is a Turkish port simplifying procedures. Notifies the company of the diversion.',
                    '4' => 'Well-reasoned diversion: analyzes each option with specific criteria. Antalya: 14 hours in force 7-8 with progressive cargo shift risk, vessel stability marginal and deteriorating, crew cannot re-secure deck cargo en route, arriving in poor condition for PSC. Marmaris: 5 hours, beam/quartering seas initially but vessel can be stabilized by course adjustment, sheltered waters allow full re-securing, stability can be restored before proceeding. Rhodes: closest but Greek authorities, potential detention complications. Heaving to: reduces risk but does not address the cargo situation and delays resolution. Clearly documents the decision rationale. Plans the approach to Marmaris including VTS notification, pilotage requirements, and anchorage selection.',
                    '5' => 'Expert routing synthesis: frames the diversion decision in terms of the total risk trajectory. Continuing to Antalya for 14 hours means 14 hours of progressive deterioration — cargo shifting further, GM decreasing, crew fatigue increasing, structural loads accumulating. The risk is increasing with time. Diverting to Marmaris for 5 hours means 5 hours of managed risk followed by resolution of the cargo problem in shelter. The risk decreases after 5 hours. The decision is clear: Marmaris diversion is the risk-minimizing option. Plans the diversion route to minimize beam seas exposure — adjusts course changes to avoid worst rolling angles. Calculates ETA to shelter and plans the work sequence on arrival: (1) anchor in shelter, (2) assess stability, (3) re-secure hold cargo, (4) re-secure deck cargo, (5) recalculate stability, (6) proceed to Antalya in improved conditions. Notifies all stakeholders: company/DPA (ISM), charterer (commercial), Marmaris VTS (operational), insurer/P&I if appropriate.',
                ],
            ],
            [
                'axis'   => 'ism_and_psc_compliance',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No ISM incident report. No DPA notification. No consideration of PSC implications. No documentation of the cargo shift event.',
                    '2' => 'Aware that ISM reporting is required but delays or provides incomplete information. Does not think about PSC preparation. Minimal documentation.',
                    '3' => 'Proper ISM/PSC response: reports the cargo shift to the DPA within the 2-hour window as required by the ISM system. Provides details of the incident, actions taken, and current status. Begins preparing non-conformity documentation. Considers PSC implications: ensures all cargo securing certificates, CSM, and stability records are ready for inspection. Verifies that the previous PSC observations have been properly closed out.',
                    '4' => 'Thorough regulatory compliance: files a detailed ISM incident report covering the sequence of events, probable cause (weather exceeding forecast, possible pre-existing lashing deficiency), corrective actions taken, and planned follow-up. Requests DPA assistance in notifying the classification society if required. Prepares for PSC by reviewing all documentation: cargo securing manual compliance, lashing certificate, stability records (departure and corrected), maintenance records for lashing equipment, crew training records for cargo securing. Identifies and corrects any documentation gaps before arrival.',
                    '5' => 'Expert compliance management: treats the ISM report as both a regulatory requirement and a learning opportunity. Files a comprehensive report that enables root cause analysis — was the CSM followed? Were the lashings inspected before departure? Were they suitable for the expected weather? Reports with full transparency, not defensively. For PSC preparation: conducts a self-inspection against the MOU checklist, verifies all 14 areas of concentrated inspection campaign relevance, ensures all certificates are valid, reviews the vessel\'s EQUASIS record for any outstanding issues. Prepares a file showing the incident, actions taken, and corrective measures — proactive transparency with PSC often results in better outcomes than concealment. Plans to have the re-secured cargo surveyed by a cargo surveyor at Marmaris or Antalya before proceeding.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'No stability reassessment after the cargo shift — vessel may be below minimum stability criteria with a 5-degree list and GM of only 0.45 metres at departure', 'severity' => 'critical'],
            ['flag' => 'Ordering crew to work on deck to re-secure timber cargo in force 7-8 without adequate safety assessment — risk of crew injury or man overboard', 'severity' => 'critical'],
            ['flag' => 'Continuing the 14-hour passage to Antalya with shifted cargo and marginal stability instead of diverting to the closer shelter at Marmaris', 'severity' => 'critical'],
            ['flag' => 'No ISM incident report to DPA within the required 2-hour window — failure of the safety management system', 'severity' => 'major'],
            ['flag' => 'No course alteration to reduce rolling and prevent further cargo shift', 'severity' => 'major'],
            ['flag' => 'No ballast adjustment to correct the 5-degree list and improve stability margins', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'IMO CSS Code (Code of Safe Practice for Cargo Stowage and Securing) — cargo securing and lashing requirements',
            'SOLAS Chapter VI — Carriage of Cargoes (safe stowage and securing obligations)',
            'ISM Code Section 9 — Reports and Analysis of Non-conformities, Accidents and Hazardous Occurrences',
            'IMO Intact Stability Code (2008 IS Code) — minimum GM and stability criteria',
            'Paris MoU / Mediterranean MoU — PSC inspection procedures and Concentrated Inspection Campaign focus areas',
            'Company Cargo Securing Manual (CSM) — vessel-specific lashing requirements for steel coils and deck timber',
            'STCW Code A-II/2 — Master\'s competence in stability and cargo operations',
        ],
        'red_flags_json' => [
            'Ignoring a 5-degree list and marginal GM without reassessing vessel stability after cargo shift',
            'Sending crew to work on deck or in holds with shifting cargo without a proper risk assessment',
            'Choosing the 14-hour route to Antalya over the 5-hour shelter at Marmaris with compromised stability',
            'Failing to report the cargo shift incident to the DPA within the ISM-required timeframe',
            'Not altering course to reduce rolling and arrest the progressive cargo shift',
            'Focusing on PSC avoidance rather than addressing the safety of the vessel and crew',
        ],
    ],

];
