<?php

return [

    // ══════════════════════════════════════════════════════════════
    // SLOT 5 — CREW_LEAD (CREW_EMG) — BRM breakdown from crew fatigue during rapid port turnaround
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S05_CREW_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Eastern Med, a 5,500 DWT multipurpose coastal vessel (95 metres LOA, beam 15.2 metres, draft 6.1 metres) currently departing Iskenderun, Turkey at 0230 local time. This is your third port call in four days — you loaded in Mersin (36 hours ago), discharged a parcel in Dortyol (18 hours ago), and have just completed loading additional cargo in Iskenderun. The vessel is bound for Limassol, Cyprus — a 24-hour passage. The rapid turnaround schedule has exhausted the crew. Your Chief Officer, who is responsible for the 0000-0400 bridge watch, has been showing clear signs of fatigue: during the Dortyol-Iskenderun passage yesterday he was observed having micro-sleeps at the radar, and the AB on watch had to shake him awake twice. You personally observed his sluggish response time when entering Iskenderun. Two of your 14 crew members have reported sick — one AB with severe gastroenteritis and the deck cadet with a sprained ankle from cargo operations. Your MLC rest-hour records show that the Chief Officer has had only 5 hours of rest in the past 24 hours (the MLC/STCW minimum is 10 hours in any 24-hour period). The Second Officer had 7 hours. You yourself had 6 hours. The vessel is now navigating outbound from Iskenderun Bay at night. The area has offshore oil platform installations to the south (lit but requiring careful navigation), there is a moderate amount of traffic (3 vessels visible on radar within 5 NM), and the weather is fair with good visibility. The passage to Limassol requires crossing the traffic routes in the eastern Mediterranean. Your company\'s SMS requires a competent officer on watch at all times and compliance with STCW rest-hour requirements.',
                'your_position'       => 'Wheelhouse, command. Chief Officer nominally on watch but showing visible fatigue. One AB at the helm (the other AB is the one reported sick). Lookout not yet posted for departure. Engine room on UMS — Chief Engineer was working during cargo operations and is now resting.',
                'available_resources'  => 'Bridge team: Master, Chief Officer (fatigued), Second Officer (available but had 7 hours rest), one healthy AB on bridge, one AB sick. Deck: Bosun (available), deck cadet (injured). Engine: Chief Engineer (resting after cargo ops), Second Engineer (on UMS standby). Navigation: two radars, ECDIS, AIS, GPS, VHF, autopilot. Manual steering available. Navigation lights. Echo sounder. Passage plan to Limassol prepared. Company SMS with bridge procedures, rest-hour management procedures, and Master\'s standing orders. MLC rest-hour recording system. Ship\'s medical supplies.',
                'current_conditions'   => 'Night (0230 local), visibility good (8+ NM), wind E 10 knots, sea state 1-2. Departing Iskenderun Bay outbound. 3 vessels on radar within 5 NM. Oil platforms to the south. Traffic crossing routes ahead. C/O on watch showing fatigue (micro-sleeps observed, 5 hours rest in 24). 2/O had 7 hours rest. Master had 6 hours. 2 of 14 crew sick/injured. Vessel speed 11 knots. Third port in 4 days. 24-hour passage to Limassol.',
            ],
            'tr' => [
                'situation'           => 'MV Eastern Med\'in kaptanısınız — 5.500 DWT çok amaçlı kıyı gemisi (95 m LOA, genişlik 15,2 m, draft 6,1 m), yerel saat 02:30\'da İskenderun\'dan ayrılıyorsunuz. Bu dört gün içindeki üçüncü liman uğrağınız — Mersin\'de yüklediniz (36 saat önce), Dörtyol\'da bir parti boşalttınız (18 saat önce) ve İskenderun\'da ek yük yüklemeyi tamamladınız. Gemi Limasol\'a gidiyor — 24 saatlik geçiş. Hızlı liman dönüşleri mürettebatı tüketmiş durumda. 00:00-04:00 köprü nöbetinden sorumlu Baş Zabitiniz belirgin yorgunluk belirtileri gösteriyor: dün Dörtyol-İskenderun geçişinde radarda mikro-uykular gözlemlendi ve nöbetteki AB onu iki kez sarsarak uyandırmak zorunda kaldı. İskenderun\'a girişte yavaş tepki süresini bizzat gözlemlediniz. 14 mürettebatınızdan ikisi hasta raporu verdi — bir AB şiddetli mide-bağırsak rahatsızlığı ve güverte stajyeri kargo operasyonlarından burkulmuş ayak bileği. MLC dinlenme saati kayıtlarınız Baş Zabitin son 24 saatte yalnızca 5 saat dinlendiğini gösteriyor (MLC/STCW minimum 24 saatte 10 saat). İkinci Zabit 7 saat, siz 6 saat dinlendiniz. Gemi şimdi gece İskenderun Körfezi\'nden çıkış seyri yapıyor. Güneyde deniz üstü petrol platformu tesisleri var (aydınlatılmış ama dikkatli seyir gerektirir), radarda 5 NM içinde 3 gemi görünen orta düzeyde trafik var ve hava güzel, görüş iyi. Limasol geçişi doğu Akdeniz\'deki trafik yollarını geçmeyi gerektiriyor.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Zabit nominal olarak nöbette ama belirgin yorgunluk. Bir AB dümen başında (diğer AB hasta). Çıkış için gözcü henüz görevlendirilmemiş. Makine dairesi UMS — Baş Mühendis kargo operasyonları sırasında çalıştı, şimdi dinleniyor.',
                'available_resources'  => 'Köprü: Kaptan, Baş Zabit (yorgun), İkinci Zabit (müsait, 7 saat dinlenmiş), bir sağlıklı AB, bir AB hasta. Güverte: Lostromo (müsait), stajyer (yaralı). Makine: Baş Mühendis (dinleniyor), İkinci Mühendis (UMS hazır). İki radar, ECDIS, AIS, GPS, VHF, otopilot. Geçiş planı hazır. SMS prosedürleri, dinlenme saati yönetimi, kaptanın daimi emirleri. MLC kayıt sistemi.',
                'current_conditions'   => 'Gece (02:30), görüş 8+ NM, rüzgar D 10 knot, deniz durumu 1-2. İskenderun Körfezi çıkışı. 5 NM\'de 3 gemi. Güneyde petrol platformları. Trafik yolları ileride. Baş Zabit yorgun (24 saatte 5 saat dinlenme). 2/Z 7 saat. Kaptan 6 saat. 14\'ten 2 mürettebat hasta/yaralı. Hız 11 knot. 4 günde 3. liman. Limasol\'a 24 saat.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Eastern Med (5 500 DWT, 95 м, осадка 6,1 м), выходите из Искендеруна в 02:30. Третий порт за 4 дня — Мерсин, Дёртйол, Искендерун. Курс на Лимасол (24 ч перехода). Экипаж измотан. Старпом на вахте 00–04 показывает признаки усталости: микросон на радаре (матрос будил дважды). За 24 ч — всего 5 ч отдыха (STCW минимум 10 ч). 2-й помощник — 7 ч. Вы — 6 ч. 2 из 14 больны/травмированы. Ночь, хорошая видимость, нефтяные платформы к югу, 3 судна в 5 милях.',
                'your_position'       => 'Рубка. Старпом на вахте (усталый). Один рулевой. Наблюдатель не выставлен. Машина — безвахтенный режим.',
                'available_resources'  => 'Мостик: капитан, старпом (уставший), 2-й помощник (7 ч отдыха), 1 матрос. Два радара, ECDIS, AIS, GPS, автопилот. План перехода готов. SMS процедуры. MLC записи.',
                'current_conditions'   => 'Ночь 02:30, видимость хорошая. Выход из залива Искендерун. 3 контакта, платформы к югу. Старпом — 5 ч отдыха/24 ч. Экипаж измотан. 2 из 14 больны.',
            ],
            'az' => [
                'situation'           => 'MV Eastern Med-in kapitanısınız — 5.500 DWT çoxməqsədli gəmi (95 m, su çəkimi 6,1 m), İskəndərundan 02:30-da çıxırsınız. 4 gündə 3-cü liman. Ekipaj tükənib. Baş zabit vaxta zamanı mikro-yuxu göstərir — son 24 saatda cəmi 5 saat istirahət (STCW minimum 10). 2-ci zabit 7 saat, siz 6 saat. 14 nəfərdən 2-si xəstə/yaralı. Gecə, yaxşı görmə, cənubda neft platformaları, 5 mil daxilində 3 gəmi. Limasola 24 saat keçid.',
                'your_position'       => 'Körpü. Baş zabit vaxta (yorğun). Bir matros sükan başında. Müşahidəçi qoyulmayıb.',
                'available_resources'  => 'Kapitan, baş zabit (yorğun), 2-ci zabit (7 saat istirahət), 1 matros. İki radar, ECDIS, AIS, GPS, avtopilot. Keçid planı hazır. SMS prosedurları.',
                'current_conditions'   => 'Gecə 02:30, görmə yaxşı. İskəndərun körfəzindən çıxış. 3 əlaqə, platformalar. Baş zabit — 5 saat istirahət/24. Ekipaj yorğun. 2/14 xəstə.',
            ],
        ],
        'decision_prompt'      => 'How do you address the bridge resource management breakdown caused by crew fatigue? Describe: your immediate actions regarding the Chief Officer\'s fitness for watch, how you will reorganize the watch schedule for the 24-hour passage with reduced crew, your approach to STCW/MLC rest-hour compliance when the numbers simply do not add up, whether and how you notify the company about the manning and fatigue situation, and your leadership approach to maintaining crew morale and safety.',
        'decision_prompt_i18n' => [
            'tr' => 'Mürettebat yorgunluğundan kaynaklanan köprü kaynak yönetimi çöküşünü nasıl ele alacaksınız? Açıklayınız: Baş Zabitin nöbet yetkinliğine ilişkin acil eylemleriniz, azalmış mürettebatla 24 saatlik geçiş için nöbet programını nasıl yeniden düzenleyeceğiniz, sayılar tutmadığında STCW/MLC dinlenme saati uyumu yaklaşımınız, kadro ve yorgunluk durumunu şirkete bildirip bildirmeyeceğiniz ve mürettebat moralini/güvenliğini sürdürmek için liderlik yaklaşımınız.',
            'ru' => 'Как решите проблему BRM из-за усталости? Немедленные действия по старпому, реорганизация вахт на 24 ч с сокращённым составом, соблюдение STCW/MLC при невозможности уложиться в нормы, уведомление компании, поддержание морального духа.',
            'az' => 'Heyət yorğunluğundan yaranan BRM problemini necə həll edəcəksiniz? Baş zabitin vaxta yararlılığı, 24 saatlıq keçid üçün vaxta cədvəli, STCW/MLC uyğunluğu, şirkətə bildiriş, ekipaj moralının qorunması.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'fatigue_recognition_and_action',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Allows the Chief Officer to continue the watch despite observed micro-sleeps and only 5 hours rest. Does not recognize that a fatigued OOW is a critical safety hazard. No intervention to address the immediate danger.',
                    '2' => 'Recognizes the C/O is tired but only tells him to "stay alert" or drink coffee. Does not relieve him from the watch. Does not assess whether other crew members are also fatigued. Treats it as an individual discipline issue rather than a systemic problem.',
                    '3' => 'Takes appropriate immediate action: relieves the Chief Officer from the watch and sends him to rest. Assumes the watch personally or calls the Second Officer to take over. Recognizes that allowing a fatigued officer to stand watch is a violation of STCW and creates a genuine risk of collision or grounding. Posts a lookout immediately. Reviews the rest-hour records for all watchkeepers to understand the scope of the problem.',
                    '4' => 'Comprehensive fatigue response: immediately relieves the C/O and assumes command of the navigation personally. Conducts a fatigue assessment of the entire bridge team and deck crew — reviews rest hours, identifies who is fit for duty and who needs immediate rest. Recognizes the systemic cause: three port calls in four days has made STCW compliance impossible with the current watch rotation. Does not blame the C/O — the schedule created the problem. Adjusts the passage plan if necessary to allow rest periods before entering demanding navigation areas.',
                    '5' => 'Expert fatigue management: treats this as a safety-critical event that requires both immediate action and systemic response. Immediately removes the C/O from watch duties and ensures he gets minimum 10 hours continuous rest. Takes the watch personally for the critical departure phase. Designs a modified watch schedule for the passage that maximizes rest for all watchkeepers — may need to reduce to two-watch rotation with Master participating, or extend individual watches with rest periods between. Considers whether to delay departure or reduce speed to extend the passage time and create more rest opportunities. Documents the fatigue situation comprehensively. Identifies that this is a management-of-change issue: the commercial schedule imposed by the charterer/company has created an unsafe manning situation that the Master must address.',
                ],
            ],
            [
                'axis'   => 'watch_reorganization',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No change to the watch schedule. Continues with the three-watch rotation despite two officers being non-compliant with rest hours. Does not consider alternatives.',
                    '2' => 'Makes ad hoc changes but does not create a coherent plan for the 24-hour passage. May take one watch himself but does not plan the full rotation. Does not consider the reduced AB availability.',
                    '3' => 'Reorganizes the watch schedule for the passage: plans which officer will stand which watch, ensuring each gets the maximum possible rest. Creates a modified rotation — likely Master takes the 0230-0600 watch (current), C/O rests until 1000 minimum, 2/O takes 0600-1000. Adjusts AB assignments to cover watches with one healthy AB and the bosun as substitute. Ensures a lookout is posted at all times.',
                    '4' => 'Strategic watch planning: maps out the entire 24-hour passage with specific watch assignments. Master takes the departure and initial transit watch (0230-0600) — the most critical phase with platforms and traffic. C/O sleeps 0230-1200 (nearly 10 hours). 2/O takes 0600-1000 watch. C/O returns for 1200-1600 and 0000-0400. 2/O takes 1600-2000 and Master takes 2000-0000 (arrival preparation). Uses the Bosun as relief helmsman and lookout to allow the AB to rotate. Identifies periods where the Master must be on the bridge regardless (departure, traffic crossings, arrival approach). Builds in contingency for unexpected events requiring additional bridge manning.',
                    '5' => 'Expert resource optimization: creates a watch schedule that complies with STCW as closely as possible while maintaining safe navigation. Recognizes that perfect compliance may be impossible but documents the deviation and the rationale. For the departure: Master + 2/O + AB (gives C/O immediate rest). Plans the passage to avoid navigation-intensive periods during crew rest transitions. Considers reducing speed to extend the passage from 24 to 28 hours, giving everyone more rest time. Identifies the highest-risk periods (departure, traffic crossing, approach to Limassol) and ensures maximum bridge manning during those windows. Creates a written schedule, posts it on the bridge, and briefs all participants. Includes fatigue self-monitoring requirements — any watchkeeper who feels drowsiness must report immediately, not try to continue.',
                ],
            ],
            [
                'axis'   => 'stcw_mlc_compliance',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No awareness of STCW/MLC rest-hour requirements. Does not recognize that the C/O\'s 5 hours in 24 is a violation. No documentation of the rest-hour situation. No reporting to the company.',
                    '2' => 'Aware of the requirements but treats them as paperwork rather than safety measures. May falsify rest-hour records to show compliance. Does not report the non-compliance to the company.',
                    '3' => 'Honest compliance approach: acknowledges the STCW/MLC violations in the rest-hour records — does not falsify data. Reports the non-compliance to the DPA/company as required by the ISM system. Implements corrective measures to achieve compliance as quickly as possible during the passage. Documents the exceptional circumstances that led to the violation.',
                    '4' => 'Proactive regulatory management: records accurate rest hours, flags the non-compliance in the ISM system, and reports to the DPA with a corrective action plan. References STCW Code A-VIII/1 which allows deviation from rest hours in exceptional circumstances if the Master determines it necessary for safety — but requires documentation and reporting. Explains to the DPA that the port schedule has created unavoidable violations and requests schedule adjustment for future voyages. Prepares documentation for potential PSC inspection at Limassol showing the deviation, its cause, and the corrective measures taken.',
                    '5' => 'Expert regulatory and safety integration: recognizes that rest-hour violations are both a compliance issue and a safety indicator. Reports fully to the DPA with the message that the current trading pattern creates structural non-compliance — this is not a one-off problem but will recur unless the schedule changes. Provides specific data: the three-port rotation in four days requires X hours of cargo watch, Y hours of bridge watch, Z hours of other duties, leaving only W hours for rest — mathematically impossible to comply. Requests the company to engage with the charterer to modify the schedule or provide additional crew. Documents everything per STCW and ISM. Prepares the vessel for potential PSC attention at Limassol by ensuring rest-hour records are honest, corrective actions are documented, and the company\'s response is on file. This transparency actually protects the vessel better than falsified records.',
                ],
            ],
            [
                'axis'   => 'leadership_and_crew_welfare',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'Blames the Chief Officer for being tired. No concern for crew welfare. Pushes crew to continue working despite exhaustion. Creates additional stress through authoritarian behaviour.',
                    '2' => 'Shows some sympathy but does not take practical action. Acknowledges the crew is tired but offers only verbal encouragement. Does not adjust expectations or workload.',
                    '3' => 'Supportive leadership: reassures the C/O that being relieved is not a disciplinary matter but a safety decision. Briefs the crew on the modified watch schedule and explains the rationale. Checks on the sick/injured crew members. Ensures meals are available for those who have been working through normal meal times. Maintains a calm, professional bridge atmosphere.',
                    '4' => 'Strong welfare leadership: acknowledges to the crew that the schedule has been demanding and that their fatigue is understood, not a personal failing. Takes visible personal responsibility by assuming bridge watches himself. Ensures the galley provides hot food and beverages for watchkeepers. Checks on the AB with gastroenteritis and the injured cadet — arranges medical treatment if needed. Adjusts non-essential work (maintenance, cleaning) to allow maximum rest. Creates an environment where crew feel safe reporting fatigue without fear of repercussion.',
                    '5' => 'Expert human element management: demonstrates genuine care for crew welfare while maintaining professional standards. Holds a brief meeting with available crew to explain the situation honestly: the schedule has been too intensive, rest hours are violated, and the Master is taking corrective action. Emphasizes that safety depends on everyone reporting their condition honestly. Implements a "fatigue buddy" system — watchkeepers monitor each other and report any signs of drowsiness. Ensures all physiological needs are met: food, hydration, temperature comfort, lighting. Addresses the sick AB and injured cadet medically. Plans for Limassol arrival to give maximum shore leave. Follows up with the company not just on the regulatory issue but on the human impact — crew retention suffers when vessels are commercially pushed beyond safe limits. This conversation positions the Master as both a safety leader and a crew advocate.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Allowing the Chief Officer to continue standing watch despite observed micro-sleeps and only 5 hours rest in 24 — direct risk of collision or grounding', 'severity' => 'critical'],
            ['flag' => 'No reorganization of the watch schedule after identifying that two officers are non-compliant with STCW rest hours', 'severity' => 'critical'],
            ['flag' => 'Not posting a lookout during night departure from a port area with offshore platforms and traffic', 'severity' => 'critical'],
            ['flag' => 'Falsifying rest-hour records to conceal STCW violations rather than reporting honestly to the company', 'severity' => 'major'],
            ['flag' => 'Not reporting the manning and fatigue situation to the DPA/company — failure to use the ISM safety management system', 'severity' => 'major'],
            ['flag' => 'No consideration of slowing down or delaying departure to create rest opportunities for the exhausted crew', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'STCW Convention and Code A-VIII/1 — Fitness for Duty (minimum rest hours: 10 hours in any 24-hour period)',
            'STCW Code A-VIII/2 — Watchkeeping Arrangements and Principles (competent person on watch)',
            'MLC 2006 — Regulation 2.3: Hours of Work and Hours of Rest',
            'ISM Code Section 6 — Resources and Personnel (company ensures adequate manning and rest)',
            'COLREG Rule 5 — Lookout (by sight, hearing, and all available means at all times)',
            'IMO Guidelines on Fatigue (MSC/Circ.1014) — fatigue recognition, mitigation, and management',
            'Company SMS — Bridge watchkeeping procedures, Master\'s standing orders, fatigue management policy',
        ],
        'red_flags_json' => [
            'Allowing a visibly fatigued officer with micro-sleeps to continue standing a bridge watch at night',
            'Not reorganizing watches when STCW rest-hour minimum violations are documented',
            'Departing a port area at night without a dedicated lookout posted',
            'Falsifying MLC/STCW rest-hour records to show compliance when violations have occurred',
            'Not reporting the fatigue and manning issue to the company — treating it as a bridge-level problem only',
            'Prioritizing the schedule over crew rest — not considering speed reduction or delayed departure as options',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 6 — AUTO_DEP (NAV_HAZ) — Radar and alarm system failure at night in coastal waters near Bodrum
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S06_AUTO_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Coastal Runner, a 2,800 DWT coaster (74 metres LOA, beam 11.8 metres, draft 4.4 metres) with 2,200 tonnes of general cargo, transiting the southwest Turkish coast at night between Fethiye and Bodrum. It is 0115 local time and you are passing through the waters between the Turkish mainland and the Greek Dodecanese islands — a complex area with numerous small islands, rocks, and shoals. Fifteen minutes ago the X-band radar (your primary radar) failed suddenly with a magnetron fault — the display shows only noise. The Chief Officer has diagnosed the magnetron as burned out; there is no spare on board and repair requires a port call. Your S-band radar is operational but is showing heavy sea clutter in the 2-3 metre seas (sea state 4 from a W wind at 20 knots) — small contacts are being lost in the clutter. More concerning: when the Chief Officer checked the ECDIS alarm settings, he discovered that the previous watch officer (Second Officer, who went off watch at midnight) had disabled the ECDIS proximity alarms, waypoint approach alarms, and cross-track distance alarms. The alarm log shows they were silenced at 2215 and never re-enabled. The Second Officer apparently found the frequent proximity alarms annoying in this island-dense area and turned them all off rather than adjusting the alarm parameters. You are now navigating through a channel between Kos (Greece) and the Bodrum peninsula with limited radar capability, no ECDIS safety alarms, and numerous small craft around — this is peak tourist season and sailing yachts, motor yachts, inter-island ferries, and fishing boats operate at all hours. Many of these small craft do not carry AIS transponders. Your navigation lights are functioning and the ECDIS chart display is working (it is only the alarms that were disabled), but your primary collision avoidance tool (X-band radar) is gone.',
                'your_position'       => 'Wheelhouse, command — called to the bridge when X-band radar failed. Chief Officer on the bridge troubleshooting the radar. One AB at the helm on manual steering. No dedicated lookout posted — the Second Officer\'s watch had been operating with only the OOW and helmsman.',
                'available_resources'  => 'S-band radar (operational but sea clutter issues), ECDIS (chart display working, alarms disabled — can be re-enabled), AIS (operational, but many small craft not equipped), GPS (two receivers, functioning), VHF (Ch 16, Ch 12 for Bodrum VTS area), gyrocompass and magnetic compass, echo sounder, navigation lights verified, binoculars (7x50 and night-vision), searchlight, manual steering engaged. Main engine 2,400 kW, CPP, single rudder, no bow thruster. One anchor ready. 12 crew total. Second Officer off watch (available for recall). Paper charts of the area on the chart table.',
                'current_conditions'   => 'Night (0115 local), visibility 5+ NM (clear sky, half moon), wind W 20 knots, sea state 3-4, swell 2-3m from W. X-band radar failed (magnetron). S-band showing heavy sea clutter — small contacts unreliable. ECDIS alarms all disabled by previous watchkeeper. Many small craft in the area (tourist season) — most without AIS. Between Kos and Bodrum peninsula. Vessel speed 10 knots, manual steering. 12 crew.',
            ],
            'tr' => [
                'situation'           => 'MV Coastal Runner\'ın kaptanısınız — 2.800 DWT koster (74 m LOA, genişlik 11,8 m, draft 4,4 m), 2.200 ton genel kargo ile Fethiye ile Bodrum arasında güneybatı Türkiye kıyısında gece transit geçiyor. Yerel saat 01:15 ve Türkiye anakarası ile Yunan Onikiadaları arasındaki sulardan geçiyorsunuz — çok sayıda küçük ada, kayalık ve sığlık bulunan karmaşık bir bölge. On beş dakika önce X-band radar (birincil radarınız) magnetron arızası ile aniden bozuldu — ekran yalnızca parazit gösteriyor. Baş Zabit magnetronun yandığını teşhis etti; gemide yedek yok ve onarım liman uğrağı gerektiriyor. S-band radarınız çalışıyor ancak 2-3 metre dalgalarda (batıdan 20 knot rüzgarla deniz durumu 4) yoğun deniz paraziti gösteriyor — küçük temaşlar parazitin içinde kayboluyor. Daha endişe verici olan: Baş Zabit ECDIS alarm ayarlarını kontrol ettiğinde, önceki nöbet zabitinin (gece yarısında nöbeti bırakan İkinci Zabit) ECDIS yakınlık alarmlarını, rota noktası yaklaşma alarmlarını ve çapraz iz mesafesi alarmlarını devre dışı bıraktığını keşfetti. Alarm kaydı bunların 22:15\'te susturulduğunu ve hiç yeniden etkinleştirilmediğini gösteriyor. İkinci Zabit bu ada yoğunluklu bölgede sık yakınlık alarmlarını rahatsız edici bulmuş ve alarm parametrelerini ayarlamak yerine hepsini kapatmış. Şimdi Kos (Yunanistan) ile Bodrum yarımadası arasındaki bir kanaldan sınırlı radar kapasitesiyle, ECDIS güvenlik alarmları olmadan ve etrafta çok sayıda küçük tekne ile navigasyon yapıyorsunuz — turizm sezonu zirvesinde ve yelkenli yatlar, motorlu yatlar, adalar arası feribotlar ve balıkçı tekneleri her saatte faaliyet gösteriyor. Bu küçük teknelerin çoğu AIS verici taşımıyor.',
                'your_position'       => 'Kaptan köprüsü, komuta — X-band radar arızasında köprüye çağrıldınız. Baş Zabit köprüde radar arıza tespiti yapıyor. Bir AB dümen başında manuel. Ayrılmış gözcü yok — İkinci Zabitin nöbeti sadece nöbet zabiti ve dümenci ile yürütülüyordu.',
                'available_resources'  => 'S-band radar (çalışıyor ama deniz paraziti sorunlu), ECDIS (harita çalışıyor, alarmlar devre dışı — yeniden etkinleştirilebilir), AIS (çalışıyor ama küçük tekneler donanımsız), GPS (iki alıcı), VHF (Kanal 16, 12 Bodrum VTS), cayro ve manyetik pusula, iskandil, dürbün (7x50 ve gece görüş), projektör, manuel dümen. Ana makine 2.400 kW, CPP, tek dümen, baş itici yok. Bir çıpa hazır. 12 mürettebat. İkinci Zabit nöbet dışı (çağrılabilir). Bölge kağıt haritaları.',
                'current_conditions'   => 'Gece (01:15), görüş 5+ NM, rüzgar B 20 knot, deniz durumu 3-4, dalga 2-3m batıdan. X-band radar arızalı (magnetron). S-band yoğun deniz paraziti — küçük temaşlar güvenilmez. ECDIS alarmları önceki nöbetçi tarafından devre dışı. Çok sayıda AIS\'siz küçük tekne (turizm sezonu). Kos-Bodrum arasında. Hız 10 knot. 12 mürettebat.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Coastal Runner (2 800 DWT, 74 м, осадка 4,4 м), следуете ночью вдоль юго-западного побережья Турции между Фетхие и Бодрумом. 01:15. X-band радар отказал (магнетрон сгорел, запасного нет). S-band работает, но сильные помехи от моря (волна 2–3 м) — мелкие цели теряются. Старпом обнаружил, что 2-й помощник на предыдущей вахте отключил все аварийные сигналы ЭКНИС (приближение, путевые точки, отклонение от курса) в 22:15 — не включил обратно. Проходите между Косом (Греция) и полуостровом Бодрум. Туристический сезон — множество малых судов без AIS (яхты, катера, паромы, рыбаки). Ночь, ветер W 20 уз, волна 3–4.',
                'your_position'       => 'Рубка. Старпом — диагностика радара. Один рулевой на ручном. Наблюдатель не выставлен.',
                'available_resources'  => 'S-band радар (помехи), ЭКНИС (карта работает, алармы отключены), AIS, два GPS, УКВ, компасы, эхолот, бинокли (ночные), прожектор, ручное управление. ГД 2 400 кВт, CPP. Якорь готов. 12 чел. 2-й помощник — вызов.',
                'current_conditions'   => 'Ночь, видимость 5+ миль, ветер W 20 уз, волна 3–4. X-band — отказ. S-band — помехи. ЭКНИС алармы выключены. Множество малых судов без AIS. Бодрум–Кос. Скорость 10 уз.',
            ],
            'az' => [
                'situation'           => 'MV Coastal Runner-ın kapitanısınız — 2.800 DWT koster (74 m, su çəkimi 4,4 m), Fethiyə ilə Bodrum arasında gecə keçid. 01:15. X-band radar nasaz olub (maqnetron). S-band işləyir amma dəniz interferensiyası güclüdür — kiçik hədəflər itirilir. Baş zabit kəşf edib ki, əvvəlki vaxta zabiti (2-ci zabit) ECDIS-in bütün alarmlarını 22:15-də söndürüb — yenidən aktivləşdirməyib. Kos ilə Bodrum arasında keçirsiniz. Turizm mövsümü — AIS-siz çoxlu kiçik gəmilər.',
                'your_position'       => 'Körpü. Baş zabit — radar diaqnostikası. Bir matros sükan başında. Müşahidəçi yoxdur.',
                'available_resources'  => 'S-band radar (interferensiya), ECDIS (xəritə işləyir, alarmlar söndürülüb), AIS, iki GPS, VHF, kompaslar, exolot, dürbünlər, projektor. Baş mühərrik 2400 kVt. Lövbər hazır. 12 nəfər.',
                'current_conditions'   => 'Gecə, görmə 5+ mil, külək Q 20 düyün, dalğa 3–4. X-band nasaz. S-band interferensiya. ECDIS alarmları söndürülüb. AIS-siz kiçik gəmilər çox. Bodrum–Kos. Sürət 10 düyün.',
            ],
        ],
        'decision_prompt'      => 'Describe your response to the combined radar failure and disabled alarm situation. Address: your immediate actions to restore navigation safety, how you will manage the S-band radar sea clutter to maximize small-target detection, your plan for re-enabling and properly configuring ECDIS alarms, how you will compensate for the lost X-band radar through visual watchkeeping and other measures, and how you deal with the Second Officer\'s alarm-disabling action.',
        'decision_prompt_i18n' => [
            'tr' => 'Radar arızası ve devre dışı bırakılmış alarm durumuna birleşik müdahalenizi açıklayın: navigasyon güvenliğini geri kazanmak için acil eylemler, küçük hedef tespiti için S-band deniz paraziti yönetimi, ECDIS alarmlarını yeniden etkinleştirme ve yapılandırma planı, X-band kaybını görsel gözcülük ile telafi, İkinci Zabitin alarm kapatma eylemiyle nasıl başa çıkacağınız.',
            'ru' => 'Опишите реакцию на отказ радара и отключённые алармы: немедленные действия, управление помехами S-band, восстановление алармов ЭКНИС, компенсация потери X-band визуальным наблюдением, разбор действий 2-го помощника.',
            'az' => 'Radar nasazlığı və söndürülmüş alarmlara reaksiyanızı təsvir edin: dərhal tədbirlər, S-band interferensiyasının idarəsi, ECDIS alarmlarının bərpası, X-band itkisinin vizual müşahidə ilə kompensasiyası, 2-ci zabitin hərəkəti ilə davranış.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'manual_navigation_capability',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Continues at full speed with no adaptation to the degraded navigation capability. Does not increase visual lookout. Does not optimize the remaining S-band radar. Relies on ECDIS chart display alone without alarms.',
                    '2' => 'Reduces speed slightly but does not fundamentally change the navigation approach. Some attempt to use the S-band radar but does not optimize its settings. No systematic visual lookout plan.',
                    '3' => 'Adapts to the degraded state: reduces speed to allow more reaction time for visual detection. Optimizes S-band radar settings — adjusts sea clutter, gain, and tuning to maximize detection of small targets in the sea return. Posts a dedicated lookout on the bridge wing with binoculars. Uses ECDIS chart display to maintain awareness of charted hazards. Considers whether to navigate a wider route to give more searoom from islands and rocks.',
                    '4' => 'Comprehensive manual navigation: reduces speed significantly (to 6-7 knots) through the island channel area. Assigns the C/O (once radar troubleshooting is complete) to dedicated S-band radar watch with ARPA tracking on all detectable contacts. Posts two lookouts — one on each bridge wing with night-vision binoculars. Uses the echo sounder continuously for depth confirmation. Sets up the ECDIS with enhanced visual route monitoring — zoomed in, safety contours highlighted. Considers diverting to Bodrum or anchoring in a safe area until daylight when visual detection is reliable.',
                    '5' => 'Expert degraded-mode navigation: immediately assesses whether it is safe to continue the passage through the island channel at all with only one degraded radar and no ECDIS alarms at night in tourist season. Recognizes that the risk profile has fundamentally changed: the X-band was the primary collision avoidance tool for small targets, and without it, detection capability for non-AIS craft in sea clutter is severely compromised. If continuing: reduces to minimum safe speed, maximizes all visual and electronic detection methods, routes through the widest channels, and considers whether to anchor and wait for daylight. If the vessel is near Bodrum: diverts for both the radar repair and to transit the complex island waters in daylight. Plans the passage from this point using radar-verified position fixes on the S-band, parallel indexing on identifiable coast features, and continuous depth monitoring. Every decision accounts for the reduced safety margin.',
                ],
            ],
            [
                'axis'   => 'alarm_system_management',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Does not check or re-enable the ECDIS alarms. Continues navigating with all safety alarms disabled. Does not recognize the significance of the disabled alarms.',
                    '2' => 'Re-enables the alarms but restores them to the previous settings that were causing false alarms — resulting in repeated nuisance alerts that may be silenced again.',
                    '3' => 'Properly restores ECDIS alarms: re-enables all safety alarms immediately. Adjusts the parameters to be appropriate for the area — sets proximity alarm distances to reflect the island-dense environment (perhaps 0.5 NM rather than 2 NM), adjusts cross-track alarm to suit the passage plan, enables waypoint approach alarm. Tests each alarm to confirm it is functioning. Documents the alarm restoration in the log.',
                    '4' => 'Thorough alarm management: re-enables all alarms with appropriate settings for the navigation area. Reviews the alarm log to understand exactly which alarms were disabled and when. Recognizes that the alarm disabling represents a breakdown in bridge procedures — the standing orders should require OOW to adjust alarm parameters rather than disable alarms entirely. Adds a bridge notebook entry about the requirement to maintain ECDIS safety alarms active at all times. Reviews the company SMS for alarm management procedures.',
                    '5' => 'Expert alarm philosophy: re-enables and properly configures all ECDIS alarms as an immediate priority. Recognizes the systemic issue: if the 2/O found the alarms annoying and disabled them, the alarm settings were probably inappropriate for the area (too sensitive for island-dense waters), creating alarm fatigue. The solution is not to disable alarms but to configure them intelligently — set proximity alarms to distances that provide useful warning without constant false triggering, use look-ahead sector appropriate to the vessel speed and manoeuvrability, adjust safety contour to the actual navigable depth. After restoring, monitors for excessive false alarms and adjusts as needed. Plans to address this as a fleet-wide lessons-learned item through the company SMS. Recognizes that alarm management is a known factor in maritime accidents (similar to the ECDIS-related groundings) and treats it accordingly.',
                ],
            ],
            [
                'axis'   => 'visual_watchkeeping',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No additional visual lookout measures. Continues with just the helmsman and OOW, same as before the radar failure. Does not recognize the increased importance of visual detection.',
                    '2' => 'Asks the helmsman to keep a lookout while steering, but does not post a dedicated lookout. Does not use night-vision equipment or binoculars systematically.',
                    '3' => 'Proper lookout enhancement: posts a dedicated lookout on the bridge wing with binoculars. Recalls an additional crew member if needed. Ensures the lookout is adapted to night vision (no white light exposure). Uses the searchlight cautiously for close-range detection when needed. Maintains a proper lookout per COLREG Rule 5 — using sight, hearing, and all available means.',
                    '4' => 'Enhanced visual capability: posts lookouts on both bridge wings with night-adapted vision and 7x50 binoculars. Recalls the 2/O to augment the bridge team. Assigns specific sectors for each lookout to scan. Uses night-vision binoculars where available. Ensures bridge lighting is minimized for night vision. Opens bridge wing doors for better hearing (sound signals from approaching vessels). Issues a VHF security broadcast on Channel 16 advising vessels in the area of own vessel\'s degraded radar capability.',
                    '5' => 'Expert visual detection system: creates a comprehensive visual watchkeeping plan that compensates for the radar loss. Two dedicated lookouts on bridge wings with binoculars, assigned overlapping sectors, with regular rotation to prevent fatigue-related attention loss. Master or C/O maintains continuous S-band radar watch. 2/O manages ECDIS and communications. All bridge personnel brief on what to look for: navigation lights, silhouettes, reflections, phosphorescence from bow waves. Bridge windows cleaned. All unnecessary bridge lighting eliminated. Sound reception maximized — bridge wing doors open, engine room ventilators noted for masking. VHF security broadcast issued. Speed reduced so that visual detection range exceeds the vessel\'s stopping distance. Recognizes that in sea state 3-4 at night, small sailing yachts showing only feeble lights at wave-trough level may be virtually undetectable until very close — adjusts expectations and speed accordingly.',
                ],
            ],
            [
                'axis'   => 'procedural_and_disciplinary_response',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No reaction to the Second Officer\'s alarm disabling. Does not recognize it as a serious bridge procedure violation. No follow-up action.',
                    '2' => 'Verbally reprimands the 2/O but takes no formal action. Does not investigate why the alarms were disabled or address the systemic issue.',
                    '3' => 'Addresses the issue appropriately: notes the alarm disabling as a serious bridge procedure violation. Discusses it with the 2/O when he returns to duty — determines whether it was deliberate negligence or lack of training on alarm configuration. Documents the event in the deck log. Reports through ISM as a non-conformity or near-miss. Plans additional training on ECDIS alarm management.',
                    '4' => 'Thorough procedural response: treats the alarm disabling as a near-miss event per ISM Code Section 9. Documents the event with full timeline. Interviews the 2/O to understand the root cause — alarm fatigue, inadequate training, workload, or attitude problem. If training gap: arranges additional ECDIS familiarization. If attitude: formal counselling documented in personnel file. Reviews the standing orders to determine if they clearly prohibit disabling ECDIS safety alarms. If not, updates them. Reports to the company as an ISM near-miss for fleet-wide learning.',
                    '5' => 'Expert root cause management: handles the 2/O situation as both a disciplinary matter and a learning opportunity. Conducts a structured investigation: why were the alarms annoying? (probably inappropriate settings for the area), why did the 2/O disable rather than adjust? (possibly lack of ECDIS competence, or time pressure, or inadequate standing orders), why was this not caught at watch handover? (handover procedure gap). Addresses each root cause: updates standing orders to explicitly prohibit alarm disabling, adds alarm status to the watch handover checklist, arranges ECDIS alarm configuration training, adjusts alarm parameters for different navigation areas. Reports as an ISM near-miss with root cause analysis and corrective actions. The goal is not punishment but prevention of recurrence — while still making clear to the 2/O that the action was unacceptable and created a real danger to the vessel.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Continuing at full speed at night through island waters with only one degraded radar and no ECDIS alarms — navigation safety critically compromised', 'severity' => 'critical'],
            ['flag' => 'Not re-enabling the disabled ECDIS safety alarms immediately upon discovery', 'severity' => 'critical'],
            ['flag' => 'Not posting a dedicated visual lookout when the primary radar has failed at night in waters with numerous small craft', 'severity' => 'critical'],
            ['flag' => 'Not reducing speed to match the reduced detection capability — reaction time insufficient for visual-only detection of small craft', 'severity' => 'major'],
            ['flag' => 'No notification to VTS or surrounding traffic about degraded radar capability', 'severity' => 'major'],
            ['flag' => 'Not addressing the Second Officer\'s alarm-disabling action as a serious bridge procedure violation', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'COLREG Rule 5 — Lookout by sight, hearing, and all available means appropriate to the circumstances',
            'COLREG Rule 7 — Risk of Collision (use of radar, systematic observation, not making assumptions on scanty information)',
            'SOLAS Chapter V Regulation 19 — Navigation equipment carriage and operational requirements',
            'IMO Resolution MSC.232(82) — ECDIS Performance Standards (alarm management requirements)',
            'STCW Code A-VIII/2 Part 3-1 — OOW responsibilities (maintaining proper lookout and monitoring equipment)',
            'IMO MSC.1/Circ.1503 — ECDIS Guidance for Good Practice (alarm configuration, never disabling safety alarms)',
            'Company SMS — Bridge procedures, alarm management, OOW responsibilities, near-miss reporting',
        ],
        'red_flags_json' => [
            'Navigating at full speed at night through island waters with only one poor-performing radar and disabled alarms',
            'Not immediately re-enabling ECDIS safety alarms when the unauthorized disabling is discovered',
            'Failing to post lookouts when the primary detection tool (X-band radar) is unavailable',
            'Treating the alarm disabling as trivial rather than a serious bridge procedure violation',
            'Not considering diverting to Bodrum or anchoring until daylight given the degraded navigation state',
            'Not broadcasting a safety message to alert other vessels of degraded radar capability',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 7 — CRISIS_RSP (CREW_EMG) — Engine room fire on coastal tanker approaching Antalya
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S07_CRIS_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Med Tanker, a 4,500 DWT coastal product tanker (92 metres LOA, beam 14.6 metres, draft 6.3 metres) carrying 4,000 tonnes of gas oil (marine diesel, flash point 62°C) in six cargo tanks. You are 8 nautical miles southwest of Antalya port, proceeding at 10 knots on a course of 045°T toward the Antalya pilot boarding area. At 1045 local time the engine room fire alarm activated. The Chief Engineer immediately confirmed a fire — a fuel oil service line to the main engine has fractured at a flange joint, spraying pressurized fuel oil onto the hot exhaust manifold of the main engine. The fuel ignited and is burning fiercely around the main engine exhaust casing. The Chief Engineer and Second Engineer evacuated the engine room immediately and reported to the bridge. The engine room is now sealed, ventilation flaps closed. The main engine tripped automatically on the fire detection system — the vessel is now without propulsion and losing way. You have approximately 3-4 knots residual speed, decreasing. The wind is onshore SSW at 15 knots, and the current is setting NE at 0.8 knots — both are pushing the vessel toward the coast. At the current drift rate you estimate the vessel will be in water less than 20 metres deep in approximately 2 hours. The fire is contained within the engine room for now but the Chief Engineer reports that the fire is close to the generator fuel supply, and if it spreads, you will lose electrical power as well. The emergency generator on the upper deck is available. You have 12 crew members, all accounted for. The nearest vessel on AIS is a bulk carrier 3 nautical miles to the east, outbound from Antalya. The Turkish Coast Guard MRCC Antalya monitors VHF Channel 16.',
                'your_position'       => 'Wheelhouse, command. Chief Engineer and Second Engineer at the bridge reporting on the fire. Chief Officer at the fire control station on the main deck, preparing fire-fighting equipment. Bosun and two ABs standing by at the fire muster point. One AB at the helm (no steerage without engine, but ready for emergency rudder). Third Engineer checking the emergency generator.',
                'available_resources'  => 'Fixed CO2 fire-extinguishing system for engine room (87 cylinders, total flooding system), fire main with international shore connection, two fire pumps (one emergency pump on deck above engine room, powered by emergency generator), fire hoses and nozzles, fireman\'s outfits (2 sets), SCBA (4 sets), fire blankets. Emergency generator on upper deck (diesel, 120 kW — can power fire pump, navigation lights, radio, and essential systems). Steering gear — emergency hand-steering available. Two anchors, port anchor cleared. VHF radio on battery backup. EPIRB, SART, liferafts (2 × 20 persons). Lifeboat (1 × 20 persons). 12 crew total, all mustered. Cargo: 4,000t gas oil in 6 tanks, inerted cargo space. AIS showing bulk carrier 3 NM to east. MRCC Antalya on Ch 16.',
                'current_conditions'   => 'Fire in engine room — fuel oil on hot exhaust manifold, burning around main engine exhaust casing. Engine room sealed, ventilation closed. Main engine tripped — vessel without propulsion, losing way (3-4 knots decreasing). Wind SSW 15 knots onshore, current NE 0.8 knots — drift toward coast. Water depth decreasing: 2 hours to <20m depth. Fire near generator fuel supply — risk of blackout. Emergency generator available but not yet started. 12 crew mustered. Visibility good, sea state 2. Daylight. Bulk carrier 3 NM east. 8 NM from Antalya. Cargo: gas oil, flash point 62°C, tanks inerted.',
            ],
            'tr' => [
                'situation'           => 'MV Med Tanker\'ın kaptanısınız — 4.500 DWT kıyı ürün tankeri (92 m LOA, genişlik 14,6 m, draft 6,3 m), altı kargo tankında 4.000 ton motorin (deniz dizeli, parlama noktası 62°C) taşıyor. Antalya limanının 8 deniz mili güneybatısındasınız, Antalya pilot alma noktasına doğru 045°T rotada 10 knot ile ilerliyorsunuz. Yerel saat 10:45\'te makine dairesi yangın alarmı aktive oldu. Baş Mühendis derhal yangını doğruladı — ana makineye giden yakıt servis hattı bir flanş bağlantısından kırılmış, basınçlı yakıt ana makinenin sıcak egzoz manifolduna püskürüyor. Yakıt tutuşmuş ve ana makine egzoz muhafazası çevresinde şiddetli yanıyor. Baş Mühendis ve İkinci Mühendis makine dairesini derhal tahliye edip köprüye rapor etti. Makine dairesi şimdi mühürlenmiş, havalandırma kapakları kapalı. Ana makine yangın algılama sistemiyle otomatik kapanmış — gemi şimdi tahriksiz ve yavaşlıyor. Yaklaşık 3-4 knot artık hızınız var, azalıyor. Rüzgar kıyıya doğru GGB 15 knot ve akıntı KD 0,8 knot — her ikisi gemiyi kıyıya doğru itiyor. Mevcut sürüklenme hızında tahminen 2 saat içinde 20 metreden sığ suya gireceksiniz. Yangın şimdilik makine dairesinde kontrol altında ama Baş Mühendis yangının jeneratör yakıt beslemesine yakın olduğunu ve yayılırsa elektrik gücünü de kaybedeceğinizi bildiriyor. Üst güvertedeki acil durum jeneratörü kullanılabilir. 12 mürettebatınız var, hepsi sayılmış. AIS\'te en yakın gemi Antalya\'dan çıkış yapan 3 deniz mili doğuda bir kuru yük gemisi. Türk Sahil Güvenlik MRCC Antalya VHF Kanal 16\'yı dinliyor.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Mühendis ve İkinci Mühendis köprüde yangın raporu veriyor. Baş Zabit ana güvertede yangın kontrol istasyonunda. Lostromo ve iki AB yangın toplanma noktasında. Bir AB dümen başında (motor olmadan dümen etkisi yok ama acil dümen hazır). Üçüncü Mühendis acil jeneratörü kontrol ediyor.',
                'available_resources'  => 'Makine dairesi sabit CO2 söndürme sistemi (87 tüp, toplam doldurma), yangın hattı, iki yangın pompası (biri güvertede acil pompa, acil jeneratörle çalışır), yangın hortumları, 2 set itfaiyeci kıyafeti, 4 set SCBA, yangın battaniyeleri. Acil jeneratör (dizel 120 kW). Acil el dümeni. İki çıpa (iskele hazır). VHF batarya yedekli. EPIRB, SART, 2 can salı (2×20), 1 can filikası (20 kişi). 12 mürettebat. Kargo: 4.000t motorin, inertlenmiş tanklar. 3 NM\'de kuru yük gemisi. MRCC Antalya Kanal 16.',
                'current_conditions'   => 'Makine dairesinde yangın — yakıt sıcak egzoz üzerinde. Makine dairesi mühürlü. Ana makine durmuş — tahriksiz, yavaşlıyor (3-4 knot). Rüzgar GGB 15 knot kıyıya, akıntı KD 0,8 knot — kıyıya sürükleniyor. 2 saatte sığ su. Yangın jeneratör yakıtına yakın — karartma riski. Acil jeneratör mevcut. 12 mürettebat. Görüş iyi, gündüz. Kuru yük gemisi 3 NM doğuda. Antalya\'ya 8 NM.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Med Tanker (4 500 DWT, 92 м, осадка 6,3 м), 4 000 т дизтоплива (т. вспышки 62°C) в 6 танках. В 8 милях от Антальи. 10:45 — пожар в машинном отделении: разрыв топливной линии, горящее топливо на горячем коллекторе ГД. Машинное отделение загерметизировано, вентиляция закрыта. ГД остановлен автоматически — судно без хода, теряет инерцию. Ветер ЮЮЗ 15 уз на берег, течение СВ 0,8 уз — дрейф к берегу. Через ~2 ч глубина <20 м. Огонь рядом с топливоснабжением генераторов — риск блэкаута. Аварийный генератор на верхней палубе готов. 12 человек — все на местах. Балкер в 3 милях к востоку. MRCC Анталья на канале 16.',
                'your_position'       => 'Рубка. Стармех и 2-й механик докладывают. Старпом — пожарный пост. Боцман и 2 матроса — место сбора. Рулевой наготове. 3-й механик проверяет аварийный генератор.',
                'available_resources'  => 'Система CO2 (87 баллонов), пожарная магистраль, 2 пожарных насоса, 2 комплекта пожарного снаряжения, 4 ДАСВ. Аварийный генератор 120 кВт. Аварийное рулевое. Два якоря. УКВ на батарее. EPIRB, SART, 2 плота × 20, шлюпка × 20. AIS — балкер 3 мили.',
                'current_conditions'   => 'Пожар в МО, герметизировано. ГД — стоп, без хода. Ветер 15 уз на берег, дрейф к берегу. 2 ч до мелководья. Риск блэкаута. 12 чел. День, хорошая видимость.',
            ],
            'az' => [
                'situation'           => 'MV Med Tanker-ın kapitanısınız — 4.500 DWT sahil tankeri (92 m, su çəkimi 6,3 m), 4.000 t dizel yanacaq. Antalyadan 8 mil cənub-qərbdə. 10:45 — maşın şöbəsində yanğın: yanacaq xətti qırılıb, isti kollektora sıçrayıb. Maşın şöbəsi möhürlənib. Baş mühərrik avtomatik dayanıb — gəmi enerji olmadan. Külək CQQ 15 düyün sahilə doğru, axın 0,8 düyün — sahilə sürüklənir. 2 saatda dayaz su. Yanğın generator yanacağına yaxın — elektrik kəsilmə riski. Fövqəladə generator hazır. 12 nəfər. Balker 3 mil şərqdə. MRCC Antalya kanal 16.',
                'your_position'       => 'Körpü. Baş mühəndis və 2-ci mühəndis məruzə edir. Baş zabit yanğın postunda. Lövbər hazır.',
                'available_resources'  => 'CO2 sistemi (87 balon), yanğın xətti, 2 pompa, 2 yanğınsöndürən dəst, 4 SCBA. Fövqəladə generator 120 kVt. Əl sükanı. İki lövbər. VHF batareya. EPIRB, SART, 2 sal, 1 qayıq. 12 nəfər.',
                'current_conditions'   => 'Yanğın maşın şöbəsində, möhürlənib. Mühərrik dayanıb. Sahilə sürüklənir. 2 saat dayaz suya. Elektrik riski. 12 nəfər. Gündüz, görmə yaxşı.',
            ],
        ],
        'decision_prompt'      => 'Describe your crisis response to the engine room fire. Address: your immediate fire-fighting actions including the decision on CO2 release, how you manage the vessel\'s drift toward the coast without propulsion, your distress or urgency communication with MRCC Antalya and nearby vessels, crew safety and muster management, and the cargo safety considerations given you are carrying 4,000 tonnes of gas oil.',
        'decision_prompt_i18n' => [
            'tr' => 'Makine dairesi yangınına kriz müdahalenizi açıklayın: CO2 salınımı kararı dahil acil yangın söndürme eylemleri, tahriksiz olarak kıyıya sürüklenmeyi yönetme, MRCC Antalya ve yakın gemilerle tehlike/aciliyet haberleşmesi, mürettebat güvenliği ve toplanma yönetimi, 4.000 ton motorin taşırken kargo güvenliği değerlendirmeleri.',
            'ru' => 'Опишите антикризисные действия: тушение с решением о CO2, управление дрейфом без хода, связь с MRCC, безопасность экипажа, безопасность груза (4 000 т дизтоплива).',
            'az' => 'Maşın şöbəsi yanğınına böhran reaksiyanızı təsvir edin: CO2 buraxılması qərarı, sahilə sürüklənmənin idarəsi, MRCC ilə əlaqə, heyət təhlükəsizliyi, 4.000 t yanacaq ilə yük təhlükəsizliyi.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'fire_fighting_response',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'No structured fire-fighting response. Does not activate the CO2 system. Attempts to re-enter the engine room to fight the fire manually without proper assessment. Does not ensure engine room is properly sealed before considering CO2.',
                    '2' => 'Understands that the fixed system should be used but hesitates on the CO2 release decision. Does not verify that the engine room is properly sealed (ventilation, dampers, doors). Does not account for all personnel before releasing CO2.',
                    '3' => 'Proper fire-fighting sequence: confirms engine room is evacuated and all personnel accounted for, verifies engine room is sealed (ventilation flaps closed, doors shut, fuel quick-closing valves activated), activates the emergency generator before CO2 release to maintain essential services, releases CO2 into the engine room per the vessel\'s fire plan, monitors engine room boundaries for heat (boundary cooling with fire hoses), does not open the engine room for at least 15-20 minutes after CO2 release.',
                    '4' => 'Thorough fire management: follows the vessel fire plan step by step. Before CO2: ensures all quick-closing valves for fuel are shut from the remote station, confirms all engine room openings are sealed (dampers, ventilation, funnel damper, exhaust emergency flap), accounts for all crew by name. Starts the emergency generator and confirms power to fire pump, navigation, and communications. Releases CO2 with a verbal command recorded in the log. Posts fire boundary teams with hoses for boundary cooling — monitors engine room bulkhead temperatures with the infrared thermometer from the fire station. Plans timeline: CO2 requires 15+ minutes to be effective, then careful monitoring. Prepares for a secondary response if CO2 is insufficient — long-range boundary cooling, foam attack through access points.',
                    '5' => 'Expert fire-fighting command: treats this as a high-stakes fire on a tanker — the engine room fire is adjacent to cargo tanks containing 4,000t gas oil. Even though cargo tanks are inerted, the bulkhead heating must be monitored as a priority. Executes the CO2 release with precision: ensures personnel accountability is 100%, all fuel shut-offs are activated (main engine, generators, boiler), engine room sealed, emergency generator running and confirmed, fire teams in position for boundary cooling. After CO2 release, establishes a temperature monitoring regime on all engine room boundaries including the shared bulkhead with cargo tanks. Plans the timeline: CO2 soak for minimum 20 minutes, then boundary temperature trend analysis before any consideration of opening. Considers the possibility of re-flash if the engine room is opened prematurely. Has a plan for total loss of the engine room (fire uncontrollable) — protect the cargo tanks, prepare for tow, and if necessary, prepare for abandonment. All actions logged with times.',
                ],
            ],
            [
                'axis'   => 'drift_and_grounding_management',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No awareness of or plan for the vessel\'s drift toward the coast. Focuses only on the fire without considering the grounding risk. Does not deploy the anchor or request towing assistance.',
                    '2' => 'Recognizes the drift problem but does not take timely action. Considers anchoring but does not act. Does not calculate the time available before grounding becomes a risk.',
                    '3' => 'Addresses the drift: calculates the approximate drift rate and time to critical depth. Deploys the anchor when depth is still adequate (before entering shallow water where anchor might not hold against wind and current). Requests towing assistance from the nearby bulk carrier or from Antalya port tugs through MRCC. Monitors the vessel\'s position on ECDIS for drift tracking.',
                    '4' => 'Proactive drift management: immediately recognizes that without propulsion, the onshore wind (15 knots) and current (0.8 knots) create a grounding risk within 2 hours. Deploys the port anchor early while in adequate depth (40-50m) to arrest the drift — uses enough cable (5-7 shackles) for the anchor to hold effectively. Monitors anchor drag using ECDIS anchor watch function. Simultaneously requests tow through MRCC Antalya and directly contacts the nearby bulk carrier on VHF Ch 16 for possible emergency tow. Prepares emergency towing gear on the forecastle. Calculates the worst-case timeline and triggers for escalating the emergency (if anchor drags, if fire worsens, if tow is not available).',
                    '5' => 'Expert multi-threat management: manages the fire and drift as parallel critical threats, allocating crew resources appropriately. Deploys anchor immediately as insurance while still in deep water. Requests tug assistance through MRCC with specific position, drift rate, and urgency. Contacts the bulk carrier directly — requests emergency standby or tow if the bulk carrier has the capability. Prepares the vessel\'s emergency towing arrangement on the bow. Monitors the position continuously with drift plot. Recognizes that a tanker grounding with 4,000t gas oil in an approach to a major tourist port would be an environmental catastrophe — this elevates the urgency of preventing the grounding above almost all other considerations except crew safety. If the anchor holds and fire is controlled, the situation is manageable. If the anchor drags, immediate escalation to PAN-PAN or MAYDAY may be needed. Has a decision tree: fire out + anchor holding = tow to port; fire spreading + anchor holding = prepare to abandon; fire + anchor dragging = MAYDAY, immediate evacuation.',
                ],
            ],
            [
                'axis'   => 'external_communication',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No distress or urgency communication. Does not contact MRCC or nearby vessels. Tries to manage the situation alone.',
                    '2' => 'Makes a VHF call but does not use the correct format (PAN-PAN or MAYDAY). Provides incomplete information. Does not coordinate with the nearby bulk carrier.',
                    '3' => 'Appropriate communication: broadcasts a PAN-PAN urgency message on VHF Channel 16 to MRCC Antalya — reports engine room fire, loss of propulsion, vessel drifting toward coast, 4,000t gas oil cargo. Provides position, number of crew, and current situation. Requests towing assistance. Contacts the nearby bulk carrier for possible assistance. Keeps MRCC informed of developments.',
                    '4' => 'Thorough communication management: assesses the urgency level correctly — initially PAN-PAN (urgency: fire in engine room, loss of propulsion, drifting toward coast, but vessel not in immediate danger). Provides MRCC with comprehensive information: vessel particulars, exact position, drift rate and direction, cargo type and quantity, fire status, crew status, assistance required (towing), EPIRB activation status. Contacts the bulk carrier on Ch 16 requesting standby assistance. Requests MRCC coordinate tug dispatch from Antalya. Updates MRCC at regular intervals. Has criteria for escalating from PAN-PAN to MAYDAY (fire spreading uncontrollably, anchor dragging and grounding imminent, crew in immediate danger).',
                    '5' => 'Expert emergency communication: manages the communication as a coordinated emergency response. Broadcasts PAN-PAN with complete MIPDANIO format. Activates the EPIRB as a backup. Requests MRCC to coordinate: tug from Antalya (how soon can it arrive?), standby assistance from the bulk carrier, notification to Antalya port authority (port approach may need to be cleared for towing operation), notification to coastal environmental response team (precautionary — tanker with gas oil drifting toward coast). Provides MRCC with regular updates on fire status, anchor holding, drift rate, and crew condition. Contacts the company/DPA with a parallel report. Informs the P&I club and flag state if the situation escalates. Has clear escalation criteria: from PAN-PAN to MAYDAY if two of the following occur: fire not controlled within 30 minutes, anchor dragging toward shallow water, electrical power lost. All communications logged with times.',
                ],
            ],
            [
                'axis'   => 'crew_and_cargo_safety',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No crew muster or accountability. No consideration of cargo safety implications. No preparation for potential evacuation. Crew left without clear instructions.',
                    '2' => 'Crew mustered but no specific duties assigned beyond fire team. Cargo safety not assessed. No evacuation preparation. No medical readiness.',
                    '3' => 'Proper crew management: musters all crew and confirms accountability. Assigns specific duties: fire team (C/O, bosun, AB), bridge team (Master, 2/O, helmsman), engine support (C/E, 2/E monitoring from outside), anchor team (AB, 3/E). Checks cargo tank monitoring system — confirms inert gas pressure is maintained and no cargo heating from the fire. Prepares lifesaving appliances (liferafts, lifeboat) as precautionary measure. Ensures crew wear lifejackets.',
                    '4' => 'Comprehensive safety management: full crew accountability with specific assignments. Monitors cargo tanks closely — checks ullage, temperature, and inert gas pressure in tanks adjacent to the engine room. If any cargo tank shows temperature rise, prepares to cool the tank boundaries with deck water. Prepares both liferafts for immediate deployment. Has the lifeboat swung out if the davit is not on the fire side. Distributes survival equipment. Ensures all crew have lifejackets and immersion suits ready. Identifies abandon-ship triggers. Medically assesses any crew who were in the engine room when the fire started (smoke inhalation risk).',
                    '5' => 'Expert crisis safety management: manages crew safety as the top priority throughout the crisis. Creates a clear command structure with designated responsibilities. Monitors cargo tank safety continuously — recognizes that the engine room fire adjacent to gas oil tanks is a potential catastrophe. Checks cargo tank inert gas system (is the IG plant operational without the main engine? — it may not be, requiring manual monitoring and possible cargo tank cooling). If tanks cannot be maintained inerted, treats this as a critical escalation. Prepares for ordered abandonment if necessary — designated muster station, survival craft readiness, SART and EPIRB ready, crew briefed on procedure. Medical readiness: C/E and 2/E checked for smoke inhalation, first aid supplies available. Throughout the crisis, maintains calm command presence — crew effectiveness depends on clear leadership.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Not activating the CO2 fixed fire-extinguishing system when the fire cannot be fought manually — engine room fire left to burn uncontrolled', 'severity' => 'critical'],
            ['flag' => 'Not addressing the vessel drift toward the coast — no anchor deployment, no tow request, grounding risk with 4,000t gas oil', 'severity' => 'critical'],
            ['flag' => 'No PAN-PAN or MAYDAY broadcast to MRCC Antalya — vessel with fire and no propulsion drifting toward coast without alerting rescue services', 'severity' => 'critical'],
            ['flag' => 'Not monitoring cargo tank temperatures when engine room fire is adjacent to cargo tanks containing gas oil', 'severity' => 'major'],
            ['flag' => 'Not starting the emergency generator before losing main power — losing communications and fire pump capability', 'severity' => 'major'],
            ['flag' => 'No preparation for possible abandonment despite fire on a tanker with loss of propulsion drifting toward shore', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'SOLAS Chapter II-2 — Fire Protection, Fire Detection, and Fire Extinction (Regulation 10: fixed fire-extinguishing systems)',
            'SOLAS Chapter III — Life-Saving Appliances (muster, abandonment procedures)',
            'SOLAS Chapter V Regulation 7 — Search and Rescue (cooperation with SAR services)',
            'IAMSAR Manual Volume III — Ship\'s responsibilities in SAR and emergency response',
            'ICS/OCIMF/IAPH Ship-to-Ship Transfer Guide (tanker emergency response principles)',
            'Company Emergency Response Plan — fire on board, loss of propulsion, grounding prevention',
            'ISM Code Section 8 — Emergency Preparedness (drills, procedures, and response)',
        ],
        'red_flags_json' => [
            'Not using the fixed CO2 system and instead attempting manual entry into a sealed engine room with an active fuel fire',
            'Ignoring the drift toward the coast while without propulsion — grounding risk with gas oil cargo near a tourist coastline',
            'Failing to broadcast any distress or urgency message when the vessel has fire, no propulsion, and is drifting',
            'Not monitoring cargo tank conditions when the fire is in the adjacent engine room',
            'Failing to start the emergency generator proactively — risking total power loss',
            'No evacuation preparation or liferaft readiness on a burning tanker drifting toward shore',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 8 — TRADEOFF — Weather shelter vs ETA vs CII vs machinery concern in Aegean
    // ══════════════════════════════════════════════════════════════
    'COASTAL_S08_TRADE_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are the Master of MV Izmir Bulk, a 5,000 DWT bulk coaster (88 metres LOA, beam 14.2 metres, draft 5.8 metres) carrying 4,200 tonnes of bagged cement from Izmir to Piraeus. You are in the central Aegean Sea, approximately 10 nautical miles east of Chios, heading south. The summer Meltemi wind has rapidly intensified beyond the forecast: current conditions are NW 35 knots with gusts to 42 knots, seas 4-5 metres with a short steep swell characteristic of the open Aegean. The vessel is experiencing heavy head seas (heading approximately 180°T into the NW swell) with pitching reaching 8-10 degrees and occasional green water over the bow. Your speed has dropped from the planned 12 knots to 7 knots due to the sea conditions, and the ETA to Piraeus has slipped from tomorrow morning (0800) to tomorrow evening (2000) — beyond the receiver\'s working hours. The delivery window in the charter party is 36 hours from now; if you arrive after that, a demurrage penalty of USD 4,000 per day applies. Your Chief Engineer has just reported that the sea water cooling pump for the main engine is showing increasing vibration — bearing wear suspected. The pump is still functional but he recommends reducing engine load to 75% as a precaution, which would reduce your speed through water to approximately 9 knots (but with the head seas, your effective speed over ground would be only 5 knots). Your vessel\'s CII rating is currently D — one more heavy-fuel voyage at high consumption and you risk falling to E rating, which requires a corrective action plan to the flag state. Running the engine hard into head seas dramatically increases fuel consumption. You have three options for shelter: Chios port (Greek, 10 NM to the west, good shelter, but requires Greek port entry procedures), Cesme (Turkish, 35 NM to the NE, familiar port, but requires backtracking), or continuing through the weather. The forecast shows the Meltemi moderating in 18-24 hours. Three of your 14 crew members are seasick and unable to perform duties effectively.',
                'your_position'       => 'Wheelhouse, command. Chief Officer on bridge watch with helmsman. Second Officer checking cargo (cement bags) for shifting. Chief Engineer in engine room monitoring the cooling pump. Bosun and ABs secured on deck — no deck work possible in current conditions.',
                'available_resources'  => 'Main engine 3,600 kW at current 100% load (C/E recommends 75%), CPP, single rudder, no bow thruster. Two radars, ECDIS, AIS, GPS, VHF. Weather forecast via Navtex and GMDSS (Meltemi moderating in 18-24 hours). Fuel: adequate for 5 additional days at normal speed. Ballast system: double bottom tanks (ballast condition satisfactory). Cargo: 4,200t bagged cement — not at risk of liquefaction but bags can shift if not properly secured. Stability adequate (GM 0.82m). Passage plan alternatives in ECDIS. Company operations manager available by sat-phone. Charter party documentation. CII monitoring software showing current D rating with projected consumption data. 14 crew (3 seasick). Vessel structural condition: 18-year-old vessel, class survey current, hull in satisfactory condition.',
                'current_conditions'   => 'Wind NW 35 knots gusting 42, seas 4-5m short steep Aegean swell, heavy head seas. Vessel pitching 8-10°, occasional green water forward. SOG 7 knots (engine 100%), would drop to ~5 knots at 75% engine. ETA Piraeus slipped to 2000 tomorrow (was 0800). Delivery window 36 hours. Demurrage USD 4,000/day after that. Cooling pump vibration increasing — C/E recommends 75% load. CII rating D — risk of E if high consumption continues. Shelter options: Chios 10 NM (Greek, good shelter), Cesme 35 NM (Turkish, backtrack), or continue. Meltemi moderating in 18-24 hours. 3 of 14 crew seasick. Cement cargo needs monitoring for bag shifting.',
            ],
            'tr' => [
                'situation'           => 'MV Izmir Bulk\'un kaptanısınız — 5.000 DWT dökme yük kosteri (88 m LOA, genişlik 14,2 m, draft 5,8 m), İzmir\'den Pire\'ye 4.200 ton torbalı çimento taşıyor. Orta Ege\'desiniz, Sakız Adası\'nın yaklaşık 10 deniz mili doğusunda, güneye yöneliyorsunuz. Yaz meltemi tahminlerin ötesinde hızla şiddetlendi: mevcut koşullar KB 35 knot hamlelerde 42 knot, dalgalar 4-5 metre açık Ege\'ye özgü kısa ve dik. Gemi ağır pruva dalgası yaşıyor (yaklaşık 180°T rotayla KB dalga içine) — baş kıç vurma 8-10 derece ve zaman zaman pruvadan yeşil su. Hızınız deniz koşulları nedeniyle planlanan 12 knot\'tan 7 knot\'a düştü ve Pire ETA\'nız yarın sabah (08:00) yerine yarın akşam (20:00) olarak kaydı — alıcının çalışma saatleri dışında. Çarter parti teslimat penceresi şu andan itibaren 36 saat; bundan sonra varırsanız günlük 4.000 USD sürestarya cezası uygulanır. Baş Mühendis az önce ana makine deniz suyu soğutma pompasının artan titreşim gösterdiğini bildirdi — yatak aşınması şüphesi. Pompa hala çalışıyor ama ihtiyat olarak motor yükünün %75\'e düşürülmesini öneriyor, bu da suda hızınızı yaklaşık 9 knot\'a düşürür (ama pruva dalgasıyla yer üstü efektif hızınız sadece 5 knot olur). Geminizin CII puanı şu anda D — yüksek tüketimle bir ağır yakıt seferi daha ve E puanına düşme riskiniz var, bu da bayrak devletine düzeltici eylem planı gerektirir. Motoru pruva dalgasına karşı zorlayarak çalıştırmak yakıt tüketimini dramatik artırır. Üç sığınma seçeneğiniz var: Sakız Limanı (Yunan, 10 NM batıda, iyi barınak, Yunan liman giriş prosedürleri gerekir), Çeşme (Türk, 35 NM KD\'da, tanıdık liman, geri dönüş gerekir), veya havada devam. Tahmin meltemin 18-24 saatte yumuşayacağını gösteriyor. 14 mürettebatınızdan 3\'ü deniz tutması yaşıyor.',
                'your_position'       => 'Kaptan köprüsü, komuta. Baş Zabit köprü nöbetinde dümenci ile. İkinci Zabit kargo kontrolünde (çimento torbaları). Baş Mühendis makine dairesinde soğutma pompasını izliyor. Lostromo ve AB\'ler güvertede emniyete alınmış — mevcut koşullarda güverte çalışması mümkün değil.',
                'available_resources'  => 'Ana makine 3.600 kW mevcut %100 yük (BM %75 öneriyor), CPP, tek dümen, baş itici yok. İki radar, ECDIS, AIS, GPS, VHF. Navtex hava tahmini (meltem 18-24 saatte yumuşayacak). Yakıt: normal hızda 5 gün yeterli. Balast sistemi. Kargo: 4.200t torbalı çimento (sıvılaşma riski yok ama torbalar kayabilir). GM 0,82m. Alternatif geçiş planları ECDIS\'te. Şirket operasyon müdürü uydu telefonu. Çarter parti. CII izleme yazılımı (D puanı). 14 mürettebat (3 deniz tutması). Gemi 18 yaşında, sınıf sörvey güncel.',
                'current_conditions'   => 'Rüzgar KB 35 knot hamle 42, dalga 4-5m, ağır pruva dalgası. Baş kıç 8-10°, pruvadan yeşil su. SOG 7 knot (%100 motor), %75\'te ~5 knot olur. ETA Pire 20:00 yarın (08:00 idi). Teslimat penceresi 36 saat. Sürestarya 4.000 USD/gün. Soğutma pompası titreşimi — BM %75 yük öneriyor. CII D — E riski. Barınak: Sakız 10 NM, Çeşme 35 NM, veya devam. Meltem 18-24 saatte yumuşar. 3/14 deniz tutması. Çimento kontrol gerekiyor.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан MV Izmir Bulk (5 000 DWT, 88 м, осадка 5,8 м), 4 200 т мешкованного цемента из Измира в Пирей. Центральное Эгейское, 10 миль восточнее Хиоса, курс на юг. Мельтем усилился: NW 35 уз, порывы 42, волна 4–5 м. Сильная встречная зыбь, килевая качка 8–10°, вода на бак. Скорость упала с 12 до 7 уз, ETA Пирей сдвинулась на 20:00 завтра (было 08:00). Окно доставки — 36 ч, далее демередж 4 000 $/день. Стармех: насос охлаждения ГД вибрирует, рекомендует 75% нагрузки (скорость ~5 уз). Рейтинг CII — D, при высоком расходе — риск E. Укрытие: Хиос 10 миль (Греция), Чешме 35 миль (Турция, назад), или продолжать. Мельтем стихнет через 18–24 ч. 3 из 14 укачало.',
                'your_position'       => 'Рубка. Старпом на вахте. 2-й помощник проверяет груз. Стармех — машинное отделение. Палубная команда закрепилась.',
                'available_resources'  => 'ГД 3 600 кВт (100%, рекоменд. 75%), CPP, ECDIS, два радара, AIS, прогноз Navtex, топливо на 5 дней, балласт, GM 0,82 м, CII-монитор (D), спутн. телефон, чартер-партия. 14 чел.',
                'current_conditions'   => 'NW 35→42 уз, волна 4–5 м, встречная, SOG 7 уз (100%) / ~5 уз (75%). ETA сдвинута. Демередж через 36 ч. Насос вибрирует. CII — D. Укрытие: Хиос 10 / Чешме 35 миль. Мельтем стихнет через 18–24 ч.',
            ],
            'az' => [
                'situation'           => 'MV Izmir Bulk-un kapitanısınız — 5.000 DWT yük kosteri (88 m, su çəkimi 5,8 m), İzmirdən Pireyə 4.200 t torbalı sement. Mərkəzi Egey, Xiossun 10 mil şərqində, cənuba gedir. Meltem güclənib: ŞQ 35 düyün, küləklər 42, dalğa 4–5 m. Güclü baş dalğa, yalpa 8–10°. Sürət 12-dən 7-yə düşüb. ETA Pirey sabah 20:00 (08:00 idi). Çatdırılma pəncərəsi 36 saat, sonra 4000$/gün. Baş mühəndis soyutma nasosunun titrədiyini bildirir — 75% yük tövsiyə edir (~5 düyün). CII reytinqi D — E riski. Sığınacaq: Xios 10 mil, Çeşmə 35 mil, və ya davam. Meltem 18–24 saatda yumşalacaq. 3/14 dəniz xəstəliyi.',
                'your_position'       => 'Körpü. Baş zabit vaxta. 2-ci zabit yükü yoxlayır. Baş mühəndis maşın şöbəsində.',
                'available_resources'  => 'Baş mühərrik 3600 kVt (100%, tövsiyə 75%), CPP, ECDIS, iki radar, AIS, hava proqnozu, yanacaq 5 gün, ballast, GM 0,82 m, CII monitor (D), peyk telefonu, çarter. 14 nəfər.',
                'current_conditions'   => 'ŞQ 35→42 düyün, dalğa 4–5 m, baş dalğa, SOG 7 (100%) / ~5 (75%). ETA gecikir. Cərimə 36 saatdan sonra. Nasos titrəyir. CII D. Sığınacaq: Xios 10 / Çeşmə 35 mil. Meltem 18–24 saatda.',
            ],
        ],
        'decision_prompt'      => 'Describe your decision-making process for this multi-factor tradeoff. Address: your weather assessment and how you use the forecast, the cooling pump situation and whether you accept the Chief Engineer\'s recommendation, your analysis of the shelter options versus continuing, the CII and fuel consumption implications, the commercial consequences (delivery window, demurrage), crew welfare with 3 seasick, and how you justify and document your final decision.',
        'decision_prompt_i18n' => [
            'tr' => 'Bu çok faktörlü dengeleme için karar verme sürecinizi açıklayın: hava durumu değerlendirmesi ve tahmini nasıl kullandığınız, soğutma pompası durumu ve Baş Mühendisin önerisini kabul edip etmeyeceğiniz, barınak seçenekleri ile devam etme analizi, CII ve yakıt tüketimi sonuçları, ticari sonuçlar (teslimat penceresi, sürestarya), 3 hasta mürettebatla refah ve nihai kararınızı nasıl gerekçelendirip belgelediğiniz.',
            'ru' => 'Опишите процесс принятия решения: оценка погоды, насос охлаждения и рекомендация стармеха, анализ укрытия vs продолжения, последствия CII/расхода, коммерческие последствия, благополучие экипажа, обоснование и документирование решения.',
            'az' => 'Çoxfaktorlu tarazlıq üçün qərar vermə prosesinizi təsvir edin: hava qiymətləndirməsi, soyutma nasosu və mühəndisin tövsiyəsi, sığınacaq və ya davam analizi, CII/yanacaq nəticələri, kommersiya nəticələri, heyət rifahı, yekun qərarın əsaslandırılması.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'weather_assessment',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No weather assessment beyond looking out the window. Does not consult the forecast. No understanding of Meltemi patterns or how they develop and decline. Makes the decision based on current conditions only.',
                    '2' => 'Checks the Navtex forecast but does not integrate it into the decision. Aware the Meltemi is strong but does not understand the implications for the passage or the moderation timeline.',
                    '3' => 'Sound weather analysis: reviews the Navtex forecast and understands that the Meltemi will moderate in 18-24 hours. Calculates the impact on the passage — if sheltering, the vessel loses 18-24 hours of waiting plus transit time to/from shelter, versus continuing at reduced speed and arriving at Piraeus perhaps 12-14 hours late but without the detour. Considers the sea state forecast for the passage — will conditions improve gradually or remain severe until the Meltemi breaks?',
                    '4' => 'Thorough meteorological integration: analyzes the Meltemi pattern — understanding that Aegean summer NW gales typically last 3-5 days with diurnal variation (stronger afternoons, lighter mornings). Uses the forecast to identify potential weather windows. Calculates passage alternatives: (a) shelter at Chios, wait 18-24 hours, resume in lighter conditions — total delay ~24 hours but safer; (b) continue at reduced speed in head seas — arrive 12 hours late but with high fuel consumption and machinery stress; (c) alter course to east lee of islands for partial shelter while making southing. Considers the wave period and direction for each option — beam seas to Chios versus head seas continuing south.',
                    '5' => 'Expert weather-based decision-making: treats the forecast as the foundation for all planning. Identifies the Meltemi moderation window (18-24 hours) and plans around it. Recognizes that the Aegean Meltemi creates different conditions in different locations — the open stretch between Chios and Andros is the worst, while the lee of large islands provides significant shelter. Maps the passage to minimize exposure: could alter course to pass through the lee of Chios/Ikaria before crossing the open fetch to Piraeus. Calculates specific ETA scenarios for each option with weather windows considered. Checks multiple forecast sources if available. Understands that a forecast of moderation in 18-24 hours means the worst is now — trying to push through the peak is the worst time to do so.',
                ],
            ],
            [
                'axis'   => 'machinery_and_safety_analysis',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Ignores the Chief Engineer\'s recommendation about the cooling pump. Maintains 100% engine load because of the schedule. No assessment of the risk of pump failure at sea.',
                    '2' => 'Acknowledges the pump issue but is reluctant to reduce power because of the ETA impact. Asks the C/E to monitor it without committing to the load reduction.',
                    '3' => 'Accepts the C/E recommendation to reduce to 75% load as a prudent safety measure. Understands that a cooling pump failure at sea in a gale would lead to main engine shutdown — loss of propulsion in 4-5 metre seas near a rocky island coast would be extremely dangerous. The speed loss from 7 to 5 knots SOG is significant but the risk of total failure is unacceptable.',
                    '4' => 'Thorough machinery assessment: discusses with the C/E the specific failure mode — bearing wear leading to seizure, which would stop the cooling water flow and cause engine overheating shutdown. Evaluates the consequences: loss of propulsion in the current sea state near the rocky Aegean islands could result in grounding within hours. The 2-knot speed difference is trivial compared to the catastrophic risk of a complete failure. Agrees to 75% and also asks the C/E to prepare a contingency plan if the pump fails completely — is there a backup cooling path or emergency procedure? Factors the reduced speed into all ETA calculations.',
                    '5' => 'Expert risk-weighted machinery decision: integrates the pump issue into the overall decision matrix. Recognizes that running at 100% load in heavy head seas is already stressing the engine (higher thermal loads, vibration from propeller racing in waves) — the pump vibration is a warning signal that must be respected. At 75% load: lower thermal stress on the pump, lower fuel consumption (improving CII), lower structural stress on the hull (less slamming), and the speed difference in these seas is minimal because the vessel is already being slowed by the waves. At 100%: marginally faster but dramatically higher risk of pump failure, higher fuel consumption, worse CII, more structural stress, and more crew discomfort. The risk-benefit analysis overwhelmingly favours 75%. Also asks the C/E to log the pump condition, vibration readings, and temperature trends so the condition can be tracked and maintenance planned at the next port.',
                ],
            ],
            [
                'axis'   => 'commercial_and_cii_analysis',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Focuses only on meeting the delivery window without considering CII, fuel cost, or other factors. Or conversely, fixates on one factor (CII) without considering the commercial picture.',
                    '2' => 'Considers the delivery window and demurrage but does not quantify the tradeoffs. Aware of CII but does not connect it to the current decision.',
                    '3' => 'Balanced commercial analysis: calculates the demurrage exposure if the delivery window is missed (USD 4,000/day). Compares this to the fuel cost of pushing through heavy weather at high consumption. Considers the CII impact: running hard into head seas uses dramatically more fuel per mile than the planned consumption, pushing the D-rated vessel toward E. Documents the analysis for the company.',
                    '4' => 'Quantified tradeoff analysis: calculates specific numbers — fuel consumption at 100% vs 75% vs sheltering. At 100% in head seas: roughly 15-18 tonnes/day versus the planned 10 tonnes/day at 12 knots in calm seas — a 50-80% increase. This extra consumption directly worsens the CII. An E rating would require a corrective action plan and could affect future charter rates and P&I cover. Demurrage at USD 4,000/day for a potential 1-2 day delay is USD 4,000-8,000 — significant but not catastrophic. Presents this analysis to the company with a recommendation. Notes that sheltering may actually minimize total fuel consumption (waiting in calm water uses minimal fuel, then sailing in moderate conditions uses normal fuel) versus fighting through heavy weather at high consumption.',
                    '5' => 'Expert multi-dimensional commercial optimization: creates a comprehensive comparison of all options with quantified outcomes. Option A (continue at 100%): arrives ~12h late, delivery window met, but high fuel cost, machinery risk, CII damage, crew stress, possible cargo shifting. Option B (reduce to 75%): arrives ~18-20h late, delivery window likely missed by a few hours, demurrage ~USD 4,000, but lower fuel cost, better CII, less machinery risk, safer for crew. Option C (shelter at Chios): arrives ~30h late, demurrage ~USD 8,000-12,000, but lowest total fuel consumption, no machinery risk, crew rest and recovery, cargo can be checked. Recognizes that the total cost of Option A includes not just fuel but the risk-weighted cost of potential engine failure (towing, delay, repair — USD 50,000+), potential CII E rating (charter market impact over multiple voyages), and crew welfare. When risk-adjusted costs are included, Option B or C may actually be cheaper than pushing through. Presents this framework to the company for a collaborative decision.',
                ],
            ],
            [
                'axis'   => 'decision_justification',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Makes a decision without articulating the reasoning. Cannot explain why one option was chosen over another. No documentation.',
                    '2' => 'Makes a decision and can give a general rationale but has not systematically evaluated the alternatives. Limited documentation.',
                    '3' => 'Structured decision: evaluates the three options against safety, commercial, environmental, and crew welfare criteria. Selects the option that best balances all factors. Documents the decision rationale in the deck log. Communicates the decision to the company with supporting reasoning.',
                    '4' => 'Well-documented decision framework: creates a written analysis of each option across multiple criteria (safety, commercial, environmental/CII, crew, machinery, cargo). Assigns relative priority (safety first, then crew welfare, then environment, then commercial). Makes the decision based on the analysis and clearly explains why the selected option is optimal. Records in the deck log with timestamp, conditions, C/E recommendation, crew status, forecast, and decision rationale. Sends a comprehensive report to the company including the analysis.',
                    '5' => 'Expert decision architecture: demonstrates that the decision was made through a structured, transparent, and defensible process. Uses a framework that considers: (1) What are the risks of each option? (2) What are the consequences if things go wrong? (3) Which risks are reversible and which are not? (4) What is the asymmetry? — recognizes that the downside of pushing through (engine failure, grounding, E-rated CII, injured crew) is catastrophic and largely irreversible, while the downside of sheltering (delay, demurrage) is costly but fully recoverable. This asymmetry drives the decision toward the safer option. Documents everything with the transparency that would withstand a subsequent investigation. Communicates proactively with all stakeholders: company (commercial impact + safety rationale), charterer through company (delay notification), C/E (agreed machinery management), crew (plan and expectations). Sets review points: reassess when weather moderates, when C/E reports on pump condition, when approaching Piraeus.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Ignoring the Chief Engineer\'s cooling pump recommendation and maintaining full engine load — risking loss of propulsion in a gale near rocky coast', 'severity' => 'critical'],
            ['flag' => 'No weather forecast analysis — making passage decisions without understanding the Meltemi pattern and moderation timeline', 'severity' => 'critical'],
            ['flag' => 'Pushing through the gale at maximum speed solely to meet the commercial deadline without assessing safety, CII, and machinery risks', 'severity' => 'critical'],
            ['flag' => 'Not considering shelter as an option when the vessel has a machinery concern, 3 seasick crew, and 18-24 hours of gale remaining', 'severity' => 'major'],
            ['flag' => 'No communication with the company about the multi-factor situation — making a significant commercial/safety decision in isolation', 'severity' => 'major'],
            ['flag' => 'Not monitoring the cargo (bagged cement) for shifting in the heavy seas with 8-10 degree pitching', 'severity' => 'major'],
        ],
        'expected_references_json' => [
            'ISM Code Section 5 — Master\'s Responsibility and Authority (overriding authority for safety decisions)',
            'SOLAS Chapter V Regulation 34 — Safe Navigation (Master not constrained by charterer from safety decisions)',
            'IMO MEPC.353(78) — CII Rating and Corrective Action Plan requirements for vessels rated E',
            'MARPOL Annex VI — Energy efficiency and fuel consumption regulations',
            'STCW Code A-VIII/2 — Principles for bridge watchkeeping in heavy weather',
            'Company SMS — Heavy weather procedures, speed reduction guidelines, port of refuge decisions',
            'MLC 2006 — Regulation 4.3: Health and Safety Protection (crew welfare in severe conditions)',
        ],
        'red_flags_json' => [
            'Overriding the Chief Engineer\'s cooling pump recommendation to maintain schedule — engine failure in a gale could be fatal',
            'Making no weather assessment — not checking the forecast or understanding when the Meltemi will moderate',
            'Treating the delivery window as an absolute constraint that overrides safety, machinery, CII, and crew welfare',
            'Not considering or evaluating shelter options when conditions are dangerous and forecast to continue',
            'Not informing the company of the situation — company should be involved in decisions with significant commercial and safety implications',
            'Neglecting crew welfare when 3 of 14 are seasick and the vessel is being punished by heavy seas that could be avoided by sheltering',
        ],
    ],

];
