<?php

namespace Database\Seeders;

use App\Models\Competency;
use Illuminate\Database\Seeder;

class CompetencyLibrarySeeder extends Seeder
{
    public function run(): void
    {
        $competencies = [
            // ── Behavioral ──
            [
                'code' => 'communication',
                'name_tr' => 'İletişim',
                'name_en' => 'Communication',
                'description_tr' => 'Sözlü ve yazılı iletişim becerisi',
                'description_en' => 'Verbal and written communication skills',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['clarity', 'active_listening', 'feedback_quality', 'cross_cultural'],
                'evaluation_criteria' => [
                    'high' => 'Clear, concise, adapts to audience',
                    'medium' => 'Generally communicates well with occasional gaps',
                    'low' => 'Unclear, poor listening, frequent misunderstandings',
                ],
                'red_flags' => ['avoids questions', 'contradicts self frequently', 'cannot articulate thoughts'],
            ],
            [
                'code' => 'accountability',
                'name_tr' => 'Sorumluluk',
                'name_en' => 'Accountability',
                'description_tr' => 'Sorumluluk alma ve hesap verebilirlik',
                'description_en' => 'Taking ownership and being answerable',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['ownership', 'follow_through', 'admits_mistakes', 'meets_commitments'],
                'evaluation_criteria' => [
                    'high' => 'Takes full ownership, admits mistakes, follows through',
                    'medium' => 'Generally responsible but deflects under pressure',
                    'low' => 'Blames others, avoids responsibility',
                ],
                'red_flags' => ['blames others consistently', 'no examples of taking ownership'],
            ],
            [
                'code' => 'teamwork',
                'name_tr' => 'Takım Çalışması',
                'name_en' => 'Teamwork',
                'description_tr' => 'Ekip içinde uyumlu ve verimli çalışma',
                'description_en' => 'Working harmoniously and productively in teams',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['collaboration', 'conflict_resolution', 'shared_goals', 'support_others'],
                'evaluation_criteria' => [
                    'high' => 'Proactively supports team, resolves conflicts',
                    'medium' => 'Works well in team but rarely leads collaboration',
                    'low' => 'Prefers solo work, causes friction',
                ],
                'red_flags' => ['inability to give team examples', 'consistently negative about colleagues'],
            ],
            [
                'code' => 'stress_resilience',
                'name_tr' => 'Stres Dayanıklılığı',
                'name_en' => 'Stress Resilience',
                'description_tr' => 'Baskı altında sakin ve etkili kalabilme',
                'description_en' => 'Remaining calm and effective under pressure',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['composure', 'decision_under_pressure', 'recovery', 'workload_management'],
                'evaluation_criteria' => [
                    'high' => 'Thrives under pressure, makes sound decisions',
                    'medium' => 'Manages stress adequately in most situations',
                    'low' => 'Visibly struggles, impaired judgment under stress',
                ],
                'red_flags' => ['panic responses', 'freezing under pressure', 'emotional volatility'],
            ],
            [
                'code' => 'adaptability',
                'name_tr' => 'Uyum Yeteneği',
                'name_en' => 'Adaptability',
                'description_tr' => 'Değişen koşullara uyum sağlama',
                'description_en' => 'Adjusting to changing conditions and requirements',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['flexibility', 'openness_to_change', 'quick_learning', 'resilience'],
                'evaluation_criteria' => [
                    'high' => 'Embraces change, adjusts quickly',
                    'medium' => 'Adapts with some resistance or delay',
                    'low' => 'Rigid, resists change',
                ],
                'red_flags' => ['refuses to consider alternatives', 'stuck in old ways'],
            ],
            [
                'code' => 'learning_agility',
                'name_tr' => 'Öğrenme Çevikliği',
                'name_en' => 'Learning Agility',
                'description_tr' => 'Yeni bilgi ve becerileri hızla edinme',
                'description_en' => 'Rapidly acquiring new knowledge and skills',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['curiosity', 'self_directed_learning', 'applies_new_knowledge', 'seeks_feedback'],
                'evaluation_criteria' => [
                    'high' => 'Actively seeks learning, applies quickly',
                    'medium' => 'Learns when required but not proactive',
                    'low' => 'Resistant to learning, slow to adopt',
                ],
                'red_flags' => ['no interest in self-development', 'cannot describe recent learning'],
            ],
            [
                'code' => 'integrity',
                'name_tr' => 'Dürüstlük',
                'name_en' => 'Integrity',
                'description_tr' => 'Etik değerlere bağlılık ve tutarlılık',
                'description_en' => 'Commitment to ethical values and consistency',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['honesty', 'consistency', 'ethical_behavior', 'transparency'],
                'evaluation_criteria' => [
                    'high' => 'Consistent values, transparent, ethical',
                    'medium' => 'Generally honest but may bend under pressure',
                    'low' => 'Inconsistent, deceptive tendencies',
                ],
                'red_flags' => ['contradictory statements', 'evasive answers', 'blame-shifting'],
            ],
            [
                'code' => 'role_competence',
                'name_tr' => 'Rol Yetkinliği',
                'name_en' => 'Role Competence',
                'description_tr' => 'Pozisyona özgü teknik ve mesleki yetkinlik',
                'description_en' => 'Position-specific technical and professional competence',
                'category' => 'behavioral',
                'is_universal' => true,
                'indicators' => ['technical_depth', 'practical_experience', 'problem_solving', 'domain_knowledge'],
                'evaluation_criteria' => [
                    'high' => 'Deep expertise, practical experience, solves complex problems',
                    'medium' => 'Adequate knowledge with some gaps',
                    'low' => 'Insufficient knowledge for the role',
                ],
                'red_flags' => ['cannot describe core responsibilities', 'lacks fundamental knowledge'],
            ],
            // ── Soft Skill ──
            [
                'code' => 'leadership',
                'name_tr' => 'Liderlik',
                'name_en' => 'Leadership',
                'description_tr' => 'Ekibi yönlendirme, motive etme ve karar alma',
                'description_en' => 'Guiding, motivating, and making decisions for the team',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['vision', 'delegation', 'motivation', 'decision_authority'],
                'evaluation_criteria' => [
                    'high' => 'Inspires others, delegates effectively, makes tough decisions',
                    'medium' => 'Can lead when required but not a natural leader',
                    'low' => 'Avoids leadership, indecisive',
                ],
                'red_flags' => ['micromanagement tendencies', 'cannot motivate others'],
            ],
            [
                'code' => 'conflict_resolution',
                'name_tr' => 'Çatışma Çözme',
                'name_en' => 'Conflict Resolution',
                'description_tr' => 'Anlaşmazlıkları yapıcı şekilde çözme',
                'description_en' => 'Resolving disagreements constructively',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['mediation', 'empathy', 'de_escalation', 'win_win_solutions'],
                'evaluation_criteria' => [
                    'high' => 'Proactively resolves conflicts, finds win-win solutions',
                    'medium' => 'Handles minor conflicts but avoids major ones',
                    'low' => 'Escalates conflicts or avoids them entirely',
                ],
                'red_flags' => ['aggressive conflict style', 'total avoidance'],
            ],
            [
                'code' => 'decision_making',
                'name_tr' => 'Karar Verme',
                'name_en' => 'Decision Making',
                'description_tr' => 'Bilgiye dayalı, zamanlı ve etkili karar alma',
                'description_en' => 'Making informed, timely, and effective decisions',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['analytical_thinking', 'risk_assessment', 'timeliness', 'decisiveness'],
                'evaluation_criteria' => [
                    'high' => 'Decisive, data-driven, considers risks',
                    'medium' => 'Makes adequate decisions with guidance',
                    'low' => 'Indecisive or impulsive',
                ],
                'red_flags' => ['analysis paralysis', 'reckless decisions without data'],
            ],
            [
                'code' => 'emotional_intelligence',
                'name_tr' => 'Duygusal Zeka',
                'name_en' => 'Emotional Intelligence',
                'description_tr' => 'Kendi ve başkalarının duygularını anlama ve yönetme',
                'description_en' => 'Understanding and managing own and others\' emotions',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['self_awareness', 'empathy', 'social_skills', 'self_regulation'],
                'evaluation_criteria' => [
                    'high' => 'High empathy, self-aware, excellent interpersonal skills',
                    'medium' => 'Adequate emotional awareness in most situations',
                    'low' => 'Poor self-awareness, lacks empathy',
                ],
                'red_flags' => ['dismisses others\' feelings', 'uncontrolled emotional reactions'],
            ],
            [
                'code' => 'time_management',
                'name_tr' => 'Zaman Yönetimi',
                'name_en' => 'Time Management',
                'description_tr' => 'Zamanı verimli kullanma ve önceliklendirme',
                'description_en' => 'Using time efficiently and prioritizing effectively',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['prioritization', 'planning', 'punctuality', 'efficiency'],
                'evaluation_criteria' => [
                    'high' => 'Excellent prioritization, always on time',
                    'medium' => 'Generally manages time but occasionally misses deadlines',
                    'low' => 'Poor planning, frequently late',
                ],
                'red_flags' => ['chronic lateness', 'inability to prioritize'],
            ],
            [
                'code' => 'cultural_awareness',
                'name_tr' => 'Kültürel Farkındalık',
                'name_en' => 'Cultural Awareness',
                'description_tr' => 'Farklı kültürlere saygı ve anlayış',
                'description_en' => 'Respect and understanding for diverse cultures',
                'category' => 'soft_skill',
                'is_universal' => false,
                'indicators' => ['respect', 'inclusivity', 'cultural_sensitivity', 'adaptability'],
                'evaluation_criteria' => [
                    'high' => 'Actively inclusive, adapts to cultural differences',
                    'medium' => 'Respectful but limited cross-cultural experience',
                    'low' => 'Insensitive to cultural differences',
                ],
                'red_flags' => ['stereotyping', 'dismissive of other cultures'],
            ],
            // ── Technical ──
            [
                'code' => 'safety_awareness',
                'name_tr' => 'Güvenlik Bilinci',
                'name_en' => 'Safety Awareness',
                'description_tr' => 'İş güvenliği kurallarına uyum ve risk farkındalığı',
                'description_en' => 'Compliance with safety rules and risk awareness',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['risk_identification', 'protocol_adherence', 'safety_culture', 'incident_reporting'],
                'evaluation_criteria' => [
                    'high' => 'Proactive safety advocate, identifies risks before incidents',
                    'medium' => 'Follows safety protocols when reminded',
                    'low' => 'Ignores safety rules, cavalier attitude',
                ],
                'red_flags' => ['dismisses safety concerns', 'history of preventable incidents'],
            ],
            [
                'code' => 'technical_knowledge',
                'name_tr' => 'Teknik Bilgi',
                'name_en' => 'Technical Knowledge',
                'description_tr' => 'Alanına özgü teknik bilgi düzeyi',
                'description_en' => 'Domain-specific technical knowledge level',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['domain_expertise', 'current_knowledge', 'practical_application', 'troubleshooting'],
                'evaluation_criteria' => [
                    'high' => 'Expert-level knowledge, stays current',
                    'medium' => 'Adequate technical knowledge for the role',
                    'low' => 'Outdated or insufficient technical knowledge',
                ],
                'red_flags' => ['cannot explain basic concepts', 'outdated certifications'],
            ],
            [
                'code' => 'equipment_operation',
                'name_tr' => 'Ekipman Kullanımı',
                'name_en' => 'Equipment Operation',
                'description_tr' => 'Ekipman ve araç-gereç kullanma becerisi',
                'description_en' => 'Ability to operate equipment and machinery',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['proficiency', 'maintenance_knowledge', 'safety_compliance', 'troubleshooting'],
                'evaluation_criteria' => [
                    'high' => 'Expert operator, performs preventive maintenance',
                    'medium' => 'Can operate standard equipment adequately',
                    'low' => 'Limited equipment skills, needs supervision',
                ],
                'red_flags' => ['unfamiliar with standard equipment', 'unsafe operation practices'],
            ],
            [
                'code' => 'emergency_response',
                'name_tr' => 'Acil Durum Müdahalesi',
                'name_en' => 'Emergency Response',
                'description_tr' => 'Acil durumlarda hızlı ve doğru müdahale',
                'description_en' => 'Rapid and correct response in emergencies',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['quick_response', 'protocol_knowledge', 'calm_under_crisis', 'first_aid'],
                'evaluation_criteria' => [
                    'high' => 'Calm, follows protocols, leads emergency response',
                    'medium' => 'Knows procedures but limited hands-on experience',
                    'low' => 'Panics, does not know emergency procedures',
                ],
                'red_flags' => ['unaware of emergency procedures', 'freezes in crisis scenarios'],
            ],
            [
                'code' => 'navigation_skills',
                'name_tr' => 'Navigasyon Becerileri',
                'name_en' => 'Navigation Skills',
                'description_tr' => 'Deniz navigasyonu ve rota planlama',
                'description_en' => 'Maritime navigation and route planning',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['chart_reading', 'GPS_systems', 'weather_assessment', 'route_planning'],
                'evaluation_criteria' => [
                    'high' => 'Expert navigator, handles complex routes',
                    'medium' => 'Competent in standard navigation tasks',
                    'low' => 'Limited navigation experience',
                ],
                'red_flags' => ['cannot read nautical charts', 'unfamiliar with ECDIS'],
            ],
            [
                'code' => 'regulatory_compliance',
                'name_tr' => 'Mevzuata Uyum',
                'name_en' => 'Regulatory Compliance',
                'description_tr' => 'Yasal düzenlemelere ve standartlara uyum',
                'description_en' => 'Adherence to legal regulations and standards',
                'category' => 'technical',
                'is_universal' => false,
                'indicators' => ['ISM_knowledge', 'SOLAS_compliance', 'MARPOL_awareness', 'flag_state_rules'],
                'evaluation_criteria' => [
                    'high' => 'Thorough knowledge of relevant regulations',
                    'medium' => 'Aware of key regulations but gaps in detail',
                    'low' => 'Poor regulatory awareness',
                ],
                'red_flags' => ['unaware of ISM code', 'history of compliance violations'],
            ],
            // ── Hard Skill ──
            [
                'code' => 'english_proficiency',
                'name_tr' => 'İngilizce Yetkinliği',
                'name_en' => 'English Proficiency',
                'description_tr' => 'İş ortamında İngilizce iletişim becerisi',
                'description_en' => 'English communication skills in professional context',
                'category' => 'hard_skill',
                'is_universal' => false,
                'indicators' => ['speaking', 'listening', 'reading', 'writing', 'maritime_english'],
                'evaluation_criteria' => [
                    'high' => 'Fluent, technical vocabulary, clear communication',
                    'medium' => 'Functional English, some limitations in complex topics',
                    'low' => 'Basic or insufficient English skills',
                ],
                'red_flags' => ['cannot understand basic instructions', 'unable to communicate safety info'],
            ],
            [
                'code' => 'documentation',
                'name_tr' => 'Dokümantasyon',
                'name_en' => 'Documentation',
                'description_tr' => 'Kayıt tutma ve raporlama becerisi',
                'description_en' => 'Record-keeping and reporting skills',
                'category' => 'hard_skill',
                'is_universal' => false,
                'indicators' => ['accuracy', 'completeness', 'organization', 'timeliness'],
                'evaluation_criteria' => [
                    'high' => 'Meticulous records, clear reports, always up to date',
                    'medium' => 'Adequate documentation with occasional gaps',
                    'low' => 'Poor record-keeping, incomplete documentation',
                ],
                'red_flags' => ['missing critical records', 'falsified documentation'],
            ],
            [
                'code' => 'watchkeeping',
                'name_tr' => 'Vardiya Tutma',
                'name_en' => 'Watchkeeping',
                'description_tr' => 'Vardiya görevlerini güvenle ve dikkatle yerine getirme',
                'description_en' => 'Performing watch duties safely and attentively',
                'category' => 'hard_skill',
                'is_universal' => false,
                'indicators' => ['alertness', 'handover_quality', 'log_keeping', 'situational_awareness'],
                'evaluation_criteria' => [
                    'high' => 'Highly alert, thorough handovers, excellent log-keeping',
                    'medium' => 'Adequate watch performance in normal conditions',
                    'low' => 'Inattentive, poor handovers',
                ],
                'red_flags' => ['sleeping on watch', 'failure to report critical observations'],
            ],
            [
                'code' => 'cargo_handling',
                'name_tr' => 'Yük Elleçleme',
                'name_en' => 'Cargo Handling',
                'description_tr' => 'Yük operasyonlarını güvenli ve verimli yürütme',
                'description_en' => 'Conducting cargo operations safely and efficiently',
                'category' => 'hard_skill',
                'is_universal' => false,
                'indicators' => ['loading_plans', 'stability_awareness', 'hazmat_handling', 'lashing'],
                'evaluation_criteria' => [
                    'high' => 'Expert in cargo operations, stability-aware',
                    'medium' => 'Handles standard cargo types adequately',
                    'low' => 'Limited cargo handling experience',
                ],
                'red_flags' => ['no stability awareness', 'unsafe cargo practices'],
            ],
            [
                'code' => 'vessel_maintenance',
                'name_tr' => 'Gemi Bakımı',
                'name_en' => 'Vessel Maintenance',
                'description_tr' => 'Gemi bakım ve onarım bilgisi',
                'description_en' => 'Vessel maintenance and repair knowledge',
                'category' => 'hard_skill',
                'is_universal' => false,
                'indicators' => ['planned_maintenance', 'troubleshooting', 'quality_standards', 'spare_management'],
                'evaluation_criteria' => [
                    'high' => 'Proactive maintenance, high quality standards',
                    'medium' => 'Performs routine maintenance adequately',
                    'low' => 'Reactive only, poor maintenance practices',
                ],
                'red_flags' => ['unfamiliar with PMS', 'deferred critical maintenance'],
            ],
        ];

        foreach ($competencies as $data) {
            Competency::updateOrCreate(
                ['code' => $data['code']],
                array_merge($data, ['is_active' => true])
            );
        }
    }
}
