<?php

return [

    // ══════════════════════════════════════════════════════════════
    // SLOT 1 — NAV_COMPLEX — Narrow port approach + heavy traffic + schedule pressure + passengers onboard
    // ══════════════════════════════════════════════════════════════
    'PASSENGER_S01_NAV_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are Master of a 330-metre, 5,200-passenger cruise ship approaching Venice lagoon via the Malamocco channel for a scheduled 0700 arrival. Twelve tour buses are waiting at the terminal for shore excursion departures at 0800 — any delay cascades into €320,000 in cancellation penalties. Port authority has assigned a narrow 25-minute approach window between 0645 and 0710 due to outbound ferry traffic from the Lido terminal. Wind is 20 knots crosswind from the southeast, creating significant drift on your vessel\'s high-sided profile (65 metres air draft, 14 decks of superstructure acting as a sail area). Two pilots are boarding at the sea buoy but the Master/Pilot exchange has revealed a disagreement on approach speed — the lead pilot is insisting on 8 knots to meet the timing window, while your bridge team calculations show maximum 6 knots is required for safe stopping distance with 5,200 passengers aboard and limited channel width. Your bow thruster effectiveness is significantly reduced above 5 knots — the manufacturer specification shows 80% efficiency loss at 8 knots. The Malamocco channel allows only 15 metres clearance on each side of your beam (40 metres beam, 70-metre channel effective width at your draft). ECDIS shows a charted depth of 9.7 metres in the channel with your vessel drawing 8.5 metres, leaving a 1.2-metre under-keel clearance at predicted low water. Small craft fishing activity has been reported in the outer approach by VTS. Passenger observation decks on Decks 12 and 14 are open and filling with spectators watching the port approach — the Hotel Director reports approximately 800 passengers on external decks.',
                'your_position'       => 'Bridge, command. Staff Captain as co-navigator, OOW managing radar and AIS plots, two helmsmen standing by (primary and backup), two pilots boarding.',
                'available_resources'  => 'ECDIS with port approach chart and UKC monitoring, two X-band ARPA radars, AIS, VHF Ch 16 and Venice VTS channel, electronic whistle and sound signals, bow thruster (3,500 kW — reduced effectiveness above 5 knots), stern thruster (2,500 kW), twin azipod propulsion, anchors cleared away, tug on standby at channel entrance (2,500 bollard pull), ship\'s passage plan with detailed approach, CCTV monitoring of passenger areas, Hotel Director on internal phone.',
                'current_conditions'   => 'Wind SE 20 knots (beam-on during channel transit), visibility 4 NM (light haze), current 0.8 knot setting NW across channel, tidal height predicted LW+0.3m at 0700, depth margin 1.2m UKC at LW, small craft in outer approach, outbound ferry traffic scheduled 0710-0730, 800+ passengers on open decks.',
            ],
            'tr' => [
                'situation'           => 'Malamocco kanalı üzerinden Venedik lagününe yaklaşan 330 metre, 5.200 yolculu bir kruvaziyer gemisinin kaptanısınız. Planlanan varış 0700 — terminalde 0800\'de kıyı gezisi kalkışları için 12 tur otobüsü bekliyor, gecikme 320.000 €\'luk iptal cezalarına yol açacak. Liman otoritesi, Lido terminalinden çıkan feribot trafiği nedeniyle 0645-0710 arası 25 dakikalık dar bir yaklaşım penceresi atamış. Güneydoğudan 20 knot çapraz rüzgar, geminizin yüksek profilli yapısında (65 metre hava çekimi, 14 güverte üstyapı yelken alanı olarak etki ediyor) önemli bir sürüklenme yaratıyor. Deniz şamandırasında iki kılavuz kaptan biniyor ancak Kaptan/Kılavuz değişiminde yaklaşma hızı konusunda anlaşmazlık ortaya çıktı — baş kılavuz zamanlama penceresine yetişmek için 8 knot ısrar ediyor, köprü ekibinizin hesaplamaları 5.200 yolcuyla ve sınırlı kanal genişliğinde güvenli durma mesafesi için maksimum 6 knot gösteriyor. Baş iticinin etkinliği 5 knot üzerinde önemli ölçüde azalıyor — üretici spesifikasyonu 8 knotta %80 verimlilik kaybı gösteriyor. Malamocco kanalı geminizin her iki tarafında sadece 15 metre boşluk bırakıyor (40 metre genişlik, 70 metre efektif kanal genişliği). ECDIS kanalda 9,7 metre derinlik gösteriyor, geminizin su çekimi 8,5 metre — alçak suda 1,2 metre omurga altı boşluk. VTS dış yaklaşımda küçük balıkçı tekne faaliyeti bildirmiş. 12. ve 14. güvertelerdeki yolcu gözlem güverteleri açık ve liman yaklaşmasını izleyen seyircilerle doluyor — Otel Müdürü açık güvertelerde yaklaşık 800 yolcu bildiriyor.',
                'your_position'       => 'Köprüüstü, komuta. Baş Kaptan yardımcı seyirci olarak, VZ radar ve AIS çizimleri yönetiyor, iki dümenci hazır (birincil ve yedek), iki kılavuz kaptan biniyor.',
                'available_resources'  => 'Liman yaklaşım kartı ve UKC izlemeli ECDIS, iki X-bant ARPA radar, AIS, VHF Kanal 16 ve Venedik VTS kanalı, baş itici (5 knot üstü düşük etkinlik), kıç itici, ikiz azipod tahrik, çapalar hazır, kanal girişinde römorkör (2.500 bollard pull), detaylı yaklaşma ile gemi sefer planı, yolcu alanları CCTV, dahili telefonda Otel Müdürü.',
                'current_conditions'   => 'Rüzgar GD 20 knot (kanal geçişinde borttan), görüş 4 mil (hafif pus), akıntı 0,8 knot KB kanal boyunca, 0700\'de tahmini alçak su+0,3m, 1,2m UKC, dış yaklaşımda küçük tekneler, çıkış feribot trafiği 0710-0730, açık güvertelerde 800+ yolcu.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан круизного лайнера 330 м, 5 200 пассажиров, подход к лагуне Венеции через канал Маламокко, прибытие 07:00. Порт назначил 25-минутное окно (06:45–07:10) из-за паромного трафика. Боковой ветер ЮВ 20 узлов вызывает снос высокобортного судна (65 м надводный габарит). Лоцман настаивает на 8 узлах, ваши расчёты показывают максимум 6 узлов для безопасной остановки. Подруливающие неэффективны выше 5 узлов. Канал — 15 м запас с каждого борта. УКГ — 1,2 м при малой воде. Малые суда в подходе. 800+ пассажиров на открытых палубах наблюдают заход.',
                'your_position'       => 'Мостик, командование. Старший помощник — со-навигатор, ВП — радар/AIS, два рулевых, два лоцмана.',
                'available_resources'  => 'ЭКНИС, два САРП, AIS, УКВ, подруливающие (носовой/кормовой), азиподы, буксир наготове, план перехода, CCTV пассажирских зон.',
                'current_conditions'   => 'Ветер ЮВ 20, видимость 4 мили, течение 0,8 узла, УКГ 1,2 м, малые суда, паромное движение с 07:10.',
            ],
            'az' => [
                'situation'           => 'Venesiya laqunasına Malamokko kanalı ilə yaxınlaşan 330 m, 5.200 sərnişinli kruiz gəmisinin kapitanısınız. Gəliş 07:00, liman 25 dəqiqəlik pəncərə təyin edib (feribot trafiki). Cənub-şərqdən 20 knot yan külək yüksək bortlu gəmini sürüyür (65 m hava qabarığı). Losman 8 knot israr edir, hesablamalarınız maksimum 6 knot göstərir. Baş itələyici 5 knot üstündə səmərəsizdir. Kanalda hər tərəfdə cəmi 15 m boşluq, UKC 1,2 m. Açıq göyərtələrdə 800+ sərnişin müşahidə edir.',
                'your_position'       => 'Körpüüstü, komanda. Baş kapitan köməkçi naviqator, iki sükandar, iki losman.',
                'available_resources'  => 'ECDIS, iki radar, AIS, VHF, itələyicilər, azipodlar, yedəkçi hazır, keçid planı, CCTV.',
                'current_conditions'   => 'Külək CŞ 20, görmə 4 mil, axın 0,8 knot, UKC 1,2 m, kiçik gəmilər, feribot hərəkəti 07:10-dan.',
            ],
        ],
        'decision_prompt'      => 'Describe your approach plan for entering the Malamocco channel and berthing at the Venice cruise terminal. Address the Master/Pilot exchange disagreement on speed, your under-keel clearance management, how you handle the crosswind drift with limited thruster effectiveness, your plan for small craft and ferry traffic, and your management of passenger safety on open decks during this constrained approach.',
        'decision_prompt_i18n' => [
            'tr' => 'Malamocco kanalına giriş ve Venedik kruvaziyer terminaline yanaşma planınızı açıklayın. Kaptan/Kılavuz hız anlaşmazlığını, omurga altı boşluk yönetimini, sınırlı itici etkinliğiyle çapraz rüzgar sürüklenmesini, küçük tekne ve feribot trafiği planınızı ve bu kısıtlı yaklaşma sırasında açık güvertelerdeki yolcu güvenliği yönetiminizi ele alın.',
            'ru' => 'Опишите план захода в канал Маламокко и швартовки. Рассмотрите: разногласие с лоцманом по скорости, управление УКГ, снос при боковом ветре с ограниченными подруливающими, план по малым судам и паромам, безопасность пассажиров на открытых палубах.',
            'az' => 'Malamokko kanalına giriş və terminal yanaşma planınızı təsvir edin: losman ilə sürət fikir ayrılığı, UKC idarəsi, yan küləkdə sürüşmə, kiçik gəmi/feribot trafiği, açıq göyərtələrdə sərnişin təhlükəsizliyi.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'passage_planning_execution',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'No structured approach plan. Accepts pilot\'s 8-knot speed without question. No UKC monitoring strategy. No consideration of stopping distance or abort point for the channel transit.',
                    '2' => 'Basic approach plan exists but does not address the specific challenges of this transit. Accepts a compromise speed without calculating safety margins. UKC noted but not actively monitored.',
                    '3' => 'Sound approach plan: calculates safe approach speed based on stopping distance for the vessel\'s displacement and channel width, establishes UKC monitoring intervals with ECDIS depth alarms set at 1.0m and 0.8m, identifies abort point before channel narrows, accounts for tidal window and current set across the channel, verifies charted depths against recent surveys.',
                    '4' => 'Thorough passage execution: detailed speed profile for each phase of the approach (outer, mid-channel, final) with speeds matched to available manoeuvring margins, UKC management plan including squat calculation at each planned speed (squat at 6 knots vs 8 knots in shallow water — critical difference), dynamic UKC monitoring on ECDIS with multiple alarm thresholds, wheel-over points pre-calculated for channel bends accounting for current set, contingency anchorage identified in case of abort, tug engagement plan with pre-agreed communication protocol.',
                    '5' => 'Expert passage management: comprehensive approach plan briefed to entire bridge team including pilots, with detailed speed/distance/time calculations for each channel waypoint, full squat analysis (Barrass formula) showing that 8 knots produces 0.6m squat vs 0.3m at 6 knots — reducing effective UKC to 0.6m at 8 knots which is below company minimum of 0.8m, bank effect and interaction calculations for the narrow channel, real-time UKC monitoring with ECDIS and echo sounder cross-check, tidal stream atlas data overlaid on approach plan, contingency plans for every identified risk (engine failure, steering failure, unexpected traffic, UKC alarm), approach plan formally documented with go/no-go criteria at each decision point.',
                ],
            ],
            [
                'axis'   => 'master_pilot_relationship',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'Either completely defers to pilot on speed (abdicating Master\'s authority) or dismisses pilot input entirely creating a confrontational bridge environment. No structured Master/Pilot exchange.',
                    '2' => 'Conducts a basic exchange but does not assertively address the speed disagreement. Allows pilot to set 8 knots without presenting counter-evidence. Master/Pilot roles unclear during the transit.',
                    '3' => 'Conducts proper Master/Pilot exchange per IMO A.960: shares passage plan, discusses speed disagreement with technical evidence (stopping distance calculations, thruster limitations above 5 knots, UKC squat analysis), reaches agreement on safe speed, establishes clear roles and communication protocol.',
                    '4' => 'Effective Master/Pilot relationship: formal MPX conducted covering passage plan, vessel characteristics (high windage, thruster limitations, squat), local conditions (current, traffic, fishing), presents clear technical case for 6-knot maximum with supporting calculations, pilot card exchanged, agrees monitoring responsibilities (Master monitors overall safety, pilot conducts navigation with local knowledge), establishes intervention triggers and communication standards, discusses contingency actions for each identified risk.',
                    '5' => 'Exemplary Master/Pilot management: comprehensive MPX documented in bridge logbook, presents pilot card with detailed vessel manoeuvring data including thruster performance curves, squat tables, and stopping distances at various speeds, demonstrates respectful but firm assertion of Master\'s overriding authority under SOLAS V/34 when safety is concerned, integrates pilot\'s local knowledge (current patterns, fishing vessel behaviour, VTS protocols) with own passage plan, agrees that 6 knots maximum is non-negotiable based on the combined evidence but offers to request VTS for extended window to accommodate the safer speed, establishes closed-loop communication protocol including intervention phrases, both pilots briefed on their specific roles and the vessel\'s passenger ship characteristics.',
                ],
            ],
            [
                'axis'   => 'traffic_and_environmental_management',
                'weight' => 0.25,
                'rubric_levels' => [
                    '1' => 'No plan for managing small craft or ferry traffic. Does not contact VTS. No consideration of crosswind drift compensation in the narrow channel.',
                    '2' => 'Aware of traffic and wind but relies entirely on pilot for management. No proactive VTS communication. Crosswind noted but no drift compensation strategy.',
                    '3' => 'Active traffic management: communicates with Venice VTS regarding small craft and confirms ferry departure schedule, establishes radar/AIS monitoring for all traffic in approach and channel, plans crosswind drift compensation using helm and propulsion adjustments, sound signals prepared for restricted visibility and small craft.',
                    '4' => 'Comprehensive environmental management: VTS contacted for real-time traffic picture and confirmation of approach window, specific plan for small craft (lookout posted, speed reduction, sound signals, VHF warning on local channel), ferry traffic deconfliction confirmed with VTS timing, crosswind drift strategy calculated (crab angle or offset track) accounting for 20-knot beam wind on 65m air draft, current set across channel factored into track-keeping, tug positioned to assist with drift management if needed.',
                    '5' => 'Expert traffic and environmental integration: full coordination with Venice VTS including request for small craft advisory broadcast, outbound ferry holding until own vessel clears narrows, radar overlay with AIS used to track all contacts with CPA/TCPA alarms set, wind drift rate calculated using vessel\'s windage coefficients and corrected for channel effects (venturi acceleration between structures), current set modelled for each channel segment, helm orders pre-calculated for each phase accounting for combined wind/current effect, tug engagement criteria defined (if drift exceeds X metres from track centreline), contingency for unexpected traffic (abort to anchorage, all-stop in channel with tug holding), visual and radar lookout scheme specifically for small craft which may not carry AIS.',
                ],
            ],
            [
                'axis'   => 'passenger_safety_awareness',
                'weight' => 0.20,
                'rubric_levels' => [
                    '1' => 'No awareness of 800 passengers on open decks during constrained approach. No communication with Hotel Director. No consideration of passenger safety implications of manoeuvring decisions.',
                    '2' => 'Notes passengers on deck but takes no action. Does not consider the safety implications of having passengers on open observation decks during a high-risk approach in confined waters.',
                    '3' => 'Addresses passenger safety: communicates with Hotel Director about the approach, considers whether to restrict access to external decks during the most constrained phase, ensures PA system is ready for passenger instructions if needed, CCTV monitoring of passenger areas maintained.',
                    '4' => 'Proactive passenger management: assesses risk to passengers on Decks 12 and 14 during confined channel transit (potential for panic if close-quarters situation develops, crowd crush risk on external decks), coordinates with Hotel Director to increase crew presence on open decks, considers temporary closure of lower open decks closer to waterline, PA announcement prepared for passenger instructions, medical team on standby, ensures all watertight doors on lower decks confirmed closed for the approach.',
                    '5' => 'Comprehensive passenger safety integration: full risk assessment of passenger exposure during constrained approach — 800 passengers on open decks represents crowd management challenge if any emergency manoeuvre required, coordinates with Hotel Director to close weather decks below Deck 10 and post safety officers on remaining open decks, pre-recorded PA announcement ready in multiple languages for deck clearance if needed, medical team positioned with enhanced readiness, considers the passenger safety implications of every bridge decision (e.g., emergency astern thrust would create sudden deceleration affecting standing passengers), watertight integrity verified, CCTV monitored by dedicated officer, passenger muster awareness maintained in case situation escalates, ensures hotel department informed of timeline so passengers are managed away from critical zones during the narrowest channel sections.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'No assertion of Master\'s authority on safe approach speed — accepts pilot\'s 8 knots without challenge', 'severity' => 'critical'],
            ['flag' => 'No UKC management plan including squat calculation at planned speed',                                   'severity' => 'critical'],
            ['flag' => 'No Master/Pilot exchange addressing speed disagreement with technical evidence',                        'severity' => 'critical'],
            ['flag' => 'No plan for crosswind drift compensation in the narrow channel',                                        'severity' => 'major'],
            ['flag' => 'No consideration of passenger safety on open decks during constrained approach',                        'severity' => 'major'],
            ['flag' => 'No communication with VTS regarding small craft and traffic deconfliction',                             'severity' => 'major'],
        ],
        'expected_references_json' => [
            'SOLAS Chapter V — Safety of navigation, Regulation 34 (Master\'s discretion)',
            'IMO Resolution A.960(23) — Recommendations on training and certification of maritime pilots',
            'Company passage plan and bridge procedures manual',
            'STCW Code A-V/2 — Mandatory minimum requirements for passenger ship personnel',
            'Port of Venice approach regulations and VTS procedures',
            'IMO MSC.1/Circ.1503 — ECDIS guidance for practice',
            'Company UKC policy and squat calculation procedures',
        ],
        'red_flags_json' => [
            'Accepting pilot\'s 8-knot speed without independent assessment of stopping distance and squat',
            'Transiting channel with UKC below company minimum after squat at higher speed',
            'No structured Master/Pilot exchange — deferring entirely to pilot or creating confrontation',
            'Ignoring 800 passengers on open decks during high-risk confined water approach',
            'Allowing schedule pressure to override safe navigation decisions with 5,200 passengers aboard',
            'No abort plan or go/no-go criteria for the channel approach',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 2 — CMD_SCALE — Master-Hotel Director-Chief Engineer triangle, PSC scrutiny
    // ══════════════════════════════════════════════════════════════
    'PASSENGER_S02_CMD_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are Master of a 3,800-passenger cruise ship alongside in Barcelona. A Port State Control inspection is underway and the PSCO has identified three deficiencies: (1) two fire doors on Deck 7 midship corridor have been wedged open by hotel staff using wooden chocks to facilitate catering trolley movement during embarkation preparation — these are A-class fire doors forming part of the main vertical fire zone boundary; (2) one lifeboat davit limit switch on Boat 7 (starboard, Deck 5) has been bypassed with a wire jumper during a maintenance procedure three days ago and never restored — the Chief Engineer states the spare switch arrives in Marseille and the davit will be fully operational "by sailing time" but cannot demonstrate the limit switch function now; (3) three crew members from the galley department (transferred from a sister ship 10 days ago) have STCW Certificates of Competency that expired 14 days before transfer — the HR Manager claims renewal applications were submitted but certificates have not yet been received. The PSCO has indicated these findings may collectively warrant detention under the Paris MoU concentrated inspection campaign for passenger ships. The Hotel Director is pushing back forcefully: "We cannot close those fire doors during embarkation — 2,400 new passengers board in 3 hours and those corridors are the main catering supply routes to the dining rooms on Decks 6 and 8." Your company VP Operations is calling from head office, concerned about schedule impact — the next port is Marseille where sold-out shore excursions worth €800,000 in revenue are booked for tomorrow, and a 24-hour detention would require full cancellation. The ship agent has informed you that a cruise industry journalist is on the dock with a photographer. You have 1,600 passengers still aboard from the previous Mediterranean leg who are expecting to go ashore in Barcelona today.',
                'your_position'       => 'Master\'s office, with PSCO present. Chief Engineer, Hotel Director, and Safety Officer available. Ship agent on phone.',
                'available_resources'  => 'Ship\'s Safety Management System (SMS), ISM Code documentation, SOLAS fire safety plans, lifeboat maintenance records, crew certification files, company DPA (Designated Person Ashore) contact, ship agent in Barcelona, technical superintendent phone support, onboard maintenance team, spare fire door hold-open devices (magnetic, fire-alarm-linked) in ship\'s stores, HR department with crew documentation.',
                'current_conditions'   => 'Alongside Barcelona, good weather, 1,600 passengers aboard, 2,400 embarking in 3 hours, PSCO inspection ongoing with detention possible, media presence on dock, VP Operations calling, Marseille departure scheduled 1800 today.',
            ],
            'tr' => [
                'situation'           => 'Barselona\'da yanaşmış 3.800 yolculu kruvaziyer gemisinin kaptanısınız. Liman Devleti Kontrolü (PSC) denetimi devam ediyor ve denetçi üç eksiklik tespit etmiş: (1) Güverte 7\'deki ana dikey yangın bölge sınırını oluşturan iki A-sınıfı yangın kapısı, catering arabası geçişi kolaylığı için otel personeli tarafından tahta takozlarla açık tutulmuş; (2) Bot 7\'nin davit limit anahtarı bakım sırasında üç gün önce tel köprü ile devre dışı bırakılmış ve geri yüklenmemiş — Başmühendis yedek anahtarın Marsilya\'da geleceğini söylüyor ama şu anda limit anahtarı fonksiyonunu gösteremiyor; (3) kardeş gemiden 10 gün önce transfer edilen üç mutfak mürettebatının STCW yeterlilik belgeleri transferden 14 gün önce süreleri dolmuş. Denetçi, bu bulguların Paris MoU yolcu gemisi yoğunlaştırılmış denetim kampanyası kapsamında toplu olarak alıkoyma gerektirebileceğini belirtmiş. Otel Müdürü şiddetle itiraz ediyor: "Giriş sırasında bu kapıları kapayamayız — 3 saat içinde 2.400 yeni yolcu biniyor ve bu koridorlar Güverte 6 ve 8\'deki yemek salonlarına ana catering tedarik güzergahları." Şirket Operasyon Başkan Yardımcısı program etkisi konusunda endişeli — sonraki liman Marsilya\'da yarın 800.000 € gelir değerinde tamamen satılmış kıyı gezileri var. Gemi acentesi rıhtımda bir kruvaziyer sektörü gazetecisinin fotoğrafçıyla olduğunu bildirmiş. Önceki Akdeniz ayağından 1.600 yolcu hala gemide.',
                'your_position'       => 'Kaptan ofisi, denetçi mevcut. Başmühendis, Otel Müdürü ve Emniyet Zabiti hazır. Gemi acentesi telefonda.',
                'available_resources'  => 'Gemi SMS, ISM Kodu belgeleri, SOLAS yangın güvenlik planları, filika bakım kayıtları, mürettebat belge dosyaları, şirket DPA bağlantısı, Barselona gemi acentesi, teknik süpervizör telefon desteği, gemideki bakım ekibi, gemi depolarında manyetik/yangın alarm bağlantılı yangın kapısı açık tutma cihazları, mürettebat belgeleriyle İK departmanı.',
                'current_conditions'   => 'Barselona\'da yanaşık, iyi hava, 1.600 yolcu gemide, 3 saatte 2.400 biniyor, devam eden PSC denetimi — alıkoyma olası, rıhtımda medya, Operasyon Başkan Yardımcısı arıyor, Marsilya kalkışı bugün 1800.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан круизного лайнера на 3 800 пассажиров в Барселоне. PSC выявил: (1) две пожарные двери класса A на палубе 7 заклинены отельным персоналом для удобства провоза тележек; (2) концевик шлюпбалки бота 7 шунтирован проволокой — стармех говорит, запчасть будет в Марселе; (3) у трёх камбузных сотрудников просрочены STCW на 14 дней. Возможно задержание по Paris MoU. Отель-директор: «Не можем закрыть двери — 2 400 пассажиров через 3 часа». VP Operations давит из-за Марселя (экскурсии на €800 000). На причале пресса. 1 600 пассажиров на борту.',
                'your_position'       => 'Каюта капитана, инспектор PSC. Стармех, отель-директор, офицер безопасности — на связи.',
                'available_resources'  => 'SMS, ISM, планы SOLAS, записи ТО шлюпок, сертификаты экипажа, DPA, агент, тех. суперинтендант, магнитные дверные фиксаторы в запасах, кадровая служба.',
                'current_conditions'   => 'Барселона, хорошая погода, 1 600 на борту, посадка 2 400 через 3 ч, PSC с возможным задержанием, пресса, звонок VP Ops, отход 18:00.',
            ],
            'az' => [
                'situation'           => 'Barselonada 3.800 sərnişinli kruiz gəmisinin kapitanısınız. PSC yoxlaması: (1) 7-ci göyərtədə iki A-sinif yanğın qapısı otel heyəti tərəfindən açıq saxlanıb; (2) Bot 7 davit limit açarı 3 gün əvvəl tel ilə keçirilmiş; (3) 3 mətbəx heyətinin STCW sertifikatları 14 gün əvvəl bitib. Paris MoU üzrə saxlama mümkündür. Otel Direktoru etiraz edir — 3 saatda 2.400 sərnişin minir. VP Operations Marseldəki €800.000-lıq ekskursiyalardan narahatdır. Doqda mətbuat var. 1.600 sərnişin göyərtədədir.',
                'your_position'       => 'Kapitan ofisi, PSC müfəttişi ilə. Baş mühəndis, Otel Direktoru, Təhlükəsizlik Zabiti hazır.',
                'available_resources'  => 'SMS, ISM, SOLAS planları, bot baxım qeydləri, heyət sertifikatları, DPA, agent, texniki dəstək, maqnit qapı saxlayıcıları anbarda, kadr şöbəsi.',
                'current_conditions'   => 'Barselona, yaxşı hava, 1.600 göyərtədə, 3 saatda 2.400 miniş, PSC — saxlama mümkün, mətbuat, VP Ops zəngi, Marsel yola düşmə 18:00.',
            ],
        ],
        'decision_prompt'      => 'How do you manage this PSC situation to avoid detention while maintaining genuine safety standards? Address each deficiency with specific corrective actions and timelines, explain how you handle the Hotel Director\'s resistance on fire doors, the Chief Engineer\'s "fix by sailing" approach to the davit, the crew certification issue, and the commercial pressure from the VP Operations.',
        'decision_prompt_i18n' => [
            'tr' => 'Gerçek güvenlik standartlarını korurken alıkoymayı önlemek için bu PSC durumunu nasıl yönetiyorsunuz? Her eksiklik için spesifik düzeltici eylemler ve zaman çizelgeleri sunun, Otel Müdürü\'nün yangın kapıları direncini, Başmühendis\'in davit yaklaşımını, mürettebat belge sorununu ve Operasyon Başkan Yardımcısının ticari baskısını nasıl ele aldığınızı açıklayın.',
            'ru' => 'Как избежать задержания, сохраняя реальные стандарты безопасности? Опишите корректирующие меры по каждому замечанию, как справляетесь с сопротивлением отель-директора, подходом стармеха к шлюпбалке, проблемой сертификатов и давлением VP Operations.',
            'az' => 'Saxlamadan qaçmaq üçün əsl təhlükəsizlik standartlarını qoruyaraq bu PSC vəziyyətini necə idarə edirsiniz? Hər çatışmazlıq üçün düzəldici tədbirlər, Otel Direktorunun müqaviməti, baş mühəndisin yanaşması, sertifikat məsələsi və VP Operations təzyiqini izah edin.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'regulatory_compliance_command',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Attempts to negotiate or minimise deficiencies with PSCO rather than addressing them. Allows Hotel Director to override fire safety requirements. No corrective action plan presented to the inspector.',
                    '2' => 'Acknowledges deficiencies but proposes vague corrective actions without specific timelines. Agrees to "fix things" but does not demonstrate a systematic approach. Allows the Chief Engineer\'s "fix by sailing" to stand without verification.',
                    '3' => 'Addresses each deficiency with specific corrective actions: orders fire doors closed immediately and arranges alternative catering routes, requires Chief Engineer to demonstrate davit repair or provide documented risk mitigation, removes expired-certificate crew from safety duties, presents corrective action plan to PSCO with clear timelines.',
                    '4' => 'Decisive regulatory response: fire doors closed immediately with Master\'s standing order issued prohibiting wedging of any fire doors — installs magnetic hold-open devices from ship stores that release automatically on fire alarm activation (compliant solution), Chief Engineer directed to repair davit limit switch NOW as top priority with verifiable function test before PSCO leaves (or if impossible, lifeboat declared out of service with compensatory measures documented), three crew members removed from all duties pending certification resolution — contacts company HR for emergency replacement or verification of renewal status, full corrective action plan documented and presented to PSCO with evidence of each action.',
                    '5' => 'Exemplary command authority: takes full ownership of all deficiencies without deflection, immediately orders fire doors closed and personally directs installation of magnetic fire-alarm-linked hold-open devices as permanent compliant solution — issues fleet-wide safety bulletin via DPA about fire door integrity, directs Chief Engineer to repair limit switch with live demonstration for PSCO or formally withdraws Boat 7 from service with redistribution of passengers to adjacent boats documented in updated muster list, crew certification handled decisively — members removed from duties, DPA notified for company-level systemic investigation of crew transfer certification procedures, PSCO presented with comprehensive corrective action package including root cause analysis for each finding, timeline for verification, and preventive measures, requests DPA to attend the PSCO closing meeting by phone to demonstrate company commitment.',
                ],
            ],
            [
                'axis'   => 'stakeholder_management',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'Allows Hotel Director and VP Operations to dictate safety decisions. Does not manage the media situation. No communication strategy for the multiple conflicting demands.',
                    '2' => 'Manages one stakeholder at the expense of others. Either alienates the PSCO by appearing dismissive or alienates the Hotel Director by being heavy-handed without explanation. No media awareness.',
                    '3' => 'Balances stakeholders: explains to Hotel Director why fire doors must be closed and offers alternative catering routes, informs VP Operations of the situation factually with a realistic timeline, instructs ship agent to manage media presence, communicates with passengers aboard about potential schedule impact.',
                    '4' => 'Effective multi-stakeholder management: Hotel Director given clear directive on fire doors with immediate alternative solution (magnetic hold-open devices) that satisfies both safety and operational needs, VP Operations briefed with specific corrective action plan and realistic departure timeline, media managed through ship agent with factual statement prepared, 1,600 passengers aboard informed of any schedule changes via Hotel Director, DPA briefed as the ISM Code link between ship and company, PSCO treated professionally and cooperatively throughout.',
                    '5' => 'Expert stakeholder orchestration: Hotel Director brought into the solution (demonstrates that magnetic hold-open devices actually improve catering flow AND safety compliance — makes them an ally), VP Operations briefed with detailed plan showing that proactive compliance now prevents worse outcomes (detention = 24+ hours, media story = "cruise ship detained for safety failures" vs. brief delay = manageable), ship agent given specific media holding statement ("routine inspection, minor items being addressed"), DPA engaged for company-level support and to authorise any expenditure needed for immediate fixes, PSCO relationship managed professionally — demonstrates willingness to go beyond minimum compliance which builds credibility, embarking passengers managed with contingency plan if departure delayed, considers reputational implications of every decision.',
                ],
            ],
            [
                'axis'   => 'safety_culture_enforcement',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Treats the deficiencies as paperwork problems to be resolved for the PSCO rather than genuine safety issues. No recognition of the systemic safety culture failures these findings represent.',
                    '2' => 'Fixes the immediate deficiencies but does not address root causes. Does not recognise that wedging fire doors, bypassing safety switches, and transferring uncertified crew are symptoms of a deeper safety culture problem.',
                    '3' => 'Addresses both immediate fixes and recognises underlying issues: understands that hotel staff wedging fire doors indicates a systemic practice that must be stopped, davit bypass reflects incomplete maintenance procedures, crew certification gap shows a transfer process failure. Initiates corrective actions and reports to DPA.',
                    '4' => 'Strong safety culture response: each deficiency treated as both an immediate safety issue AND a systemic indicator — fire doors: standing order issued, all fire doors ship-wide checked, hotel department briefed on fire zone integrity, magnetic devices installed; davit: full review of all lifeboat maintenance work orders for open items, engineering standing order on safety switch bypass procedures; crew certificates: audit of all crew certification files, HR procedures reviewed for transfer documentation. Reports to DPA with systemic findings and proposed fleet-wide preventive measures.',
                    '5' => 'Exemplary safety leadership: uses the PSC findings as a catalyst for genuine safety improvement rather than just compliance, conducts emergency safety meeting with all department heads during the PSCO visit to demonstrate that these findings are unacceptable, fire door finding triggers a ship-wide fire safety audit with results reported to DPA for fleet consideration, davit bypass triggers a review of the entire Planned Maintenance System for open critical items and a standing order that safety device bypasses require Master\'s written approval with time-limited validity, crew certification finding triggers immediate audit of ALL crew files and a formal request to company for systemic review of the crew transfer certification verification process, entire response documented as a safety learning case study for fleet distribution, personally ensures that the message is clear — commercial pressure never justifies compromising fire safety, lifesaving equipment, or crew competency on a vessel carrying 3,800 passengers.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Fire doors not ordered closed immediately upon discovery of the deficiency',                      'severity' => 'critical'],
            ['flag' => 'No corrective action on lifeboat davit limit switch bypass — accepted "fix by sailing"',         'severity' => 'critical'],
            ['flag' => 'Expired-certificate crew not removed from safety-related duties',                                'severity' => 'critical'],
            ['flag' => 'No DPA notification of PSC findings and systemic safety concerns',                               'severity' => 'major'],
            ['flag' => 'Allowed commercial pressure from VP Operations to influence safety compliance decisions',         'severity' => 'critical'],
            ['flag' => 'No root cause analysis or systemic corrective actions beyond fixing the immediate deficiencies',  'severity' => 'major'],
        ],
        'expected_references_json' => [
            'Paris MoU on Port State Control — detention procedures and concentrated inspection campaigns',
            'SOLAS Chapter II-2 — Construction: fire protection, fire detection, and fire extinction',
            'SOLAS Chapter III — Life-saving appliances and arrangements',
            'ISM Code — International Safety Management Code, Section 5 (Master\'s responsibility and authority)',
            'STCW Convention — Standards of Training, Certification and Watchkeeping',
            'Company Safety Management System (SMS) — corrective action and nonconformity procedures',
        ],
        'red_flags_json' => [
            'Allowing fire doors to remain wedged open while passengers are aboard the vessel',
            'Accepting a bypassed lifeboat davit safety switch without immediate corrective action',
            'Permitting crew with expired STCW certificates to continue serving in safety-critical roles',
            'Prioritising commercial schedule over genuine safety compliance with 3,800 passengers at risk',
            'Attempting to persuade the PSCO to overlook deficiencies rather than fixing them',
            'No recognition that these findings represent systemic safety culture failures requiring company-level action',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 3 — TECH_DEPTH — Fire detection loop false alarm vs real alarm distinction
    // ══════════════════════════════════════════════════════════════
    'PASSENGER_S03_TECH_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are Master of a 4,500-passenger cruise ship at sea in the Eastern Mediterranean. It is 02:30 and the fire detection system has activated alarms in Zone 7 — Deck 9 midship passenger cabin corridor containing 120 cabins with approximately 250 passengers sleeping. The fire panel shows three smoke detectors activated in sequence along the corridor (detectors 7-042, 7-044, 7-046 — spaced 12 metres apart) over a 90-second period, suggesting smoke migration along the corridor rather than a single detector fault. However, this same zone has experienced six false alarms in the previous 72 hours, all attributed to HVAC duct condensation following a return air duct insulation replacement completed two days ago by the HVAC team. The Chief Engineer has been called and advises: "99% certain it is another false alarm — same detectors, same sequential pattern as the previous six incidents, we are still getting condensation drip onto the detector heads from the new insulation." However, information has just reached the bridge that was not previously available: a passenger cabin steward conducting their routine rounds on Deck 9 reported smelling "something electrical — like hot wiring" near cabin 9147 approximately 15 minutes ago. This report was made to the housekeeping supervisor and did not reach the bridge until now due to a communication breakdown. Cabin 9147 is located between detectors 7-044 and 7-046. The fire patrol team has been dispatched with a thermal imaging camera — they report normal temperatures at the three detector heads consistent with condensation, BUT cabin 9147\'s door is warm to the touch and they can detect a faint haze at the base of the door when viewed with a flashlight from a low angle. The fire team of six trained firefighters is on standby at the fire station in full BA gear. The Safety Officer is recommending immediate evacuation of Zone 7 (250 sleeping passengers), but the Hotel Director warns that evacuating elderly passengers (average age 68 on this Mediterranean itinerary) through narrow corridors at 02:30 with emergency alarms sounding risks falls, cardiac events, and crowd crush injuries — he cites a 2019 incident on another vessel where a false alarm evacuation resulted in 12 passenger injuries.',
                'your_position'       => 'Bridge, command. Safety Officer present, Chief Engineer on phone from engine room, Hotel Director on internal phone, fire patrol at scene, fire team on standby.',
                'available_resources'  => 'Fire detection panel with zone isolation capability, fire patrol team with thermal imaging camera at scene, fire team (6 firefighters) in full BA gear at fire station, CCTV cameras in Deck 9 corridor, fire dampers for HVAC zone isolation, drencher system for Zone 7, CO2 and water mist portable extinguishers with fire team, ship\'s fire safety plan with zone boundaries, PA system (all zones and zone-selective), Hotel Director with cabin steward team, medical team on standby, VDR recording.',
                'current_conditions'   => 'At sea, night (02:30), calm weather, 250 passengers sleeping in Zone 7 (120 cabins), 6 previous false alarms in 72 hours same zone (HVAC condensation), 3 detectors activated in sequence, steward report of electrical smell near cabin 9147 (15 min ago), cabin door warm to touch, faint haze at door base, fire team on standby.',
            ],
            'tr' => [
                'situation'           => 'Doğu Akdeniz\'de seyir halinde 4.500 yolculu kruvaziyer gemisinin kaptanısınız. Saat 02:30, yangın algılama sistemi Bölge 7\'de alarm verdi — Güverte 9 amidşip yolcu kabin koridoru, 120 kabin ve yaklaşık 250 uyuyan yolcu. Yangın paneli, koridor boyunca 90 saniyelik sürede ardışık olarak üç duman dedektörünün (7-042, 7-044, 7-046 — 12 metre aralıklı) aktive olduğunu gösteriyor ve bu, tek dedektör arızası yerine koridor boyunca duman göçünü düşündürüyor. Ancak aynı bölge son 72 saatte altı yanlış alarm yaşadı — tümü iki gün önce HVAC ekibinin tamamladığı dönüş hava kanalı yalıtım değişikliği sonrası HVAC kanalı yoğuşmasına atfedildi. Başmühendis "%99 yanlış alarm — aynı dedektörler, aynı desen" diyor. Ancak köprüye yeni ulaşan bilgi var: bir kabin stüardı 15 dakika önce kabin 9147 yakınında "elektriksel bir şey — sıcak kablolama gibi" kokusu bildirmiş — bu rapor temizlik amirinde kalmış ve iletişim kopukluğu nedeniyle köprüye ulaşmamış. Kabin 9147, dedektörler 7-044 ve 7-046 arasında. Termal kamerayla gelen yangın devriyesi dedektör başlarında normal sıcaklık bildiriyor AMA kabin 9147 kapısı dokunulduğunda ılık ve kapı tabanında el feneriyle bakıldığında hafif bir buğu tespit ediliyor. Altı eğitimli itfaiyeciden oluşan yangın ekibi BA donanımıyla hazır bekliyor. Emniyet Zabiti Bölge 7\'nin derhal tahliyesini (250 uyuyan yolcu) öneriyor, ancak Otel Müdürü 02:30\'da acil alarmlar çalarken dar koridorlarda yaşlı yolcuları (bu Akdeniz rotasında ortalama yaş 68) tahliye etmenin düşme, kalp krizi ve kalabalık ezilme yaralanmaları riskini uyarıyor.',
                'your_position'       => 'Köprüüstü, komuta. Emniyet Zabiti mevcut, Başmühendis makine dairesinden telefonda, Otel Müdürü dahili telefonda, yangın devriyesi olay yerinde, yangın ekibi hazır bekliyor.',
                'available_resources'  => 'Bölge izolasyonlu yangın algılama paneli, olay yerinde termal kameralı yangın devriyesi, BA donanımlı yangın ekibi (6 itfaiyeci), Güverte 9 koridor CCTV kameraları, HVAC bölge izolasyonu için yangın damperleri, Bölge 7 yağmurlama sistemi, CO2 ve su sisli taşınabilir söndürücüler, gemi yangın güvenlik planı, PA sistemi (tüm bölgeler ve bölge seçmeli), Otel Müdürü ve kabin stüart ekibi, tıbbi ekip hazır, VDR kaydı.',
                'current_conditions'   => 'Seyirde, gece (02:30), sakin hava, Bölge 7\'de 250 uyuyan yolcu, 72 saatte 6 yanlış alarm (HVAC yoğuşma), ardışık 3 dedektör, kabin 9147 yakınında elektriksel koku (15 dk önce), kabin kapısı ılık, kapı tabanında hafif buğu, yangın ekibi hazır.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан круизного лайнера (4 500 пассажиров), ночь 02:30 в Восточном Средиземноморье. Пожарная сигнализация зоны 7 — палуба 9, каютный коридор (120 кают, ~250 спящих). Три датчика сработали последовательно за 90 секунд. За 72 часа — 6 ложных тревог из-за конденсата HVAC после замены изоляции. Стармех: «99% ложная». НО: стюард 15 минут назад сообщил о запахе «горячей проводки» у каюты 9147 — доклад задержался. Дверь каюты 9147 тёплая на ощупь, у основания — лёгкая дымка. Пожарная партия в готовности. Офицер безопасности хочет эвакуацию (250 человек), отель-директор предупреждает о рисках ночной эвакуации пожилых.',
                'your_position'       => 'Мостик, командование. Офицер безопасности рядом, стармех и отель-директор на связи, пожарный патруль на месте.',
                'available_resources'  => 'Панель ПС с зональной изоляцией, тепловизор у патруля, пожарная партия (6 чел., СИЗОД), CCTV, пожарные заслонки HVAC, дренчерная система, план пожарной безопасности, PA (зональная), мед. группа.',
                'current_conditions'   => 'Море, ночь, штиль, 250 спящих в зоне 7, 6 ложных тревог за 72 ч, 3 датчика последовательно, запах проводки и тёплая дверь каюты 9147, пожарная партия готова.',
            ],
            'az' => [
                'situation'           => 'Şərqi Aralıq dənizində 4.500 sərnişinli kruiz gəmisinin kapitanısınız, gecə 02:30. Zona 7-də yanğın siqnalı — göyərtə 9, kabin koridoru (120 kabin, ~250 yatan sərnişin). 3 detektor 90 saniyədə ardıcıl işə düşüb. 72 saatda 6 yanlış həyəcan (HVAC kondensasiya). Baş mühəndis: "99% yanlış". AMMA: stüard 15 dəq əvvəl kabin 9147 yaxınlığında "elektrik qoxusu" bildirmişdi — xəbər gecikib. Kabin qapısı ilıqdır, altında zəif duman var. Yanğın komandası hazırdır. Təhlükəsizlik Zabiti evakuasiya istəyir, Otel Direktoru yaşlı sərnişinlərin gecə evakuasiya risklərindən xəbərdarlıq edir.',
                'your_position'       => 'Körpüüstü, komanda. Təhlükəsizlik Zabiti yanında, baş mühəndis və Otel Direktoru əlaqədə, yanğın patrulu hadisə yerində.',
                'available_resources'  => 'Yanğın paneli (zonal izolyasiya), termal kamera, yanğın komandası (6 nəfər, tənəffüs aparatı), CCTV, HVAC klapanları, drencher sistemi, yanğın planı, PA sistemi, tibbi komanda.',
                'current_conditions'   => 'Dənizdə, gecə, sakit, zona 7-də 250 yatan, 72 saatda 6 yanlış həyəcan, 3 detektor ardıcıl, elektrik qoxusu və isti qapı kabin 9147, yanğın komandası hazır.',
            ],
        ],
        'decision_prompt'      => 'Describe your immediate actions and decision-making process. How do you distinguish between the HVAC condensation false alarm pattern and a potential real fire behind cabin 9147? What is your evacuation decision for Zone 7, how do you balance the competing risks of fire versus evacuation injuries to elderly passengers, and what technical investigation steps do you direct?',
        'decision_prompt_i18n' => [
            'tr' => 'Acil eylemlerinizi ve karar alma sürecinizi açıklayın. HVAC yoğuşma yanlış alarm düzeni ile kabin 9147 arkasındaki potansiyel gerçek yangını nasıl ayırt edersiniz? Bölge 7 için tahliye kararınız nedir, yangın ile yaşlı yolcuların tahliye yaralanmaları arasındaki çatışan riskleri nasıl dengelersiniz ve hangi teknik soruşturma adımlarını yönlendirirsiniz?',
            'ru' => 'Опишите немедленные действия и процесс принятия решений. Как отличить ложную тревогу от конденсата HVAC и возможный реальный пожар за каютой 9147? Решение об эвакуации зоны 7, баланс рисков пожара и травм при ночной эвакуации, технические шаги расследования.',
            'az' => 'Dərhal hərəkətlərinizi və qərar prosesini təsvir edin. HVAC kondensasiya yanlış həyəcanını kabin 9147 arxasındakı mümkün yanğından necə ayırırsınız? Zona 7 evakuasiya qərarı, yanğın və yaşlı sərnişin evakuasiya zədələnmələri riskinin balansı, texniki araşdırma addımları.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'fire_alarm_assessment',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Dismisses the alarm as another false alarm based on Chief Engineer\'s assessment without investigating the new evidence (steward report, warm door, haze). Or alternatively, fails to differentiate at all and treats it identically to the previous false alarms.',
                    '2' => 'Acknowledges the steward report but is swayed by the six previous false alarms and the Chief Engineer\'s confidence. Delays investigation to "see if another detector activates." Does not prioritise the cabin 9147 evidence.',
                    '3' => 'Correctly identifies that this alarm is different from the previous six: the steward report of electrical smell, warm cabin door, and visible haze are new data points not present in the false alarm pattern. Directs fire patrol to investigate cabin 9147 specifically. Treats the alarm as potentially real until proven otherwise.',
                    '4' => 'Thorough alarm assessment: analyses the alarm pattern critically — while the sequential detector activation matches the condensation pattern, three additional factors change the risk profile: (1) steward\'s independent report of electrical smell at a specific cabin location, (2) warm door indicating heat source behind it, (3) visible haze at door base distinct from overhead condensation. Recognises that these combined indicators are inconsistent with HVAC condensation and consistent with a cabin fire (possibly electrical — overloaded socket, charging device, cabin electrical fault). Treats as real fire. Immediately escalates to fire emergency procedures.',
                    '5' => 'Expert fire alarm analysis: rapid systematic differentiation — notes that the condensation false alarms showed detector activation without any corroborating physical signs (no smoke, no heat, no smell), whereas this alarm has three independent corroborating indicators (olfactory report, tactile heat on door, visual haze). Identifies that the 15-minute delay in the steward report means the fire has potentially been developing unreported, which makes the warm door particularly concerning — a cabin fire with 15+ minutes of development can be approaching flashover. Recognises the critical danger of "alarm fatigue" — the six previous false alarms have created a complacency bias that must be actively countered. Immediately declares fire emergency and escalates to the highest response level. Orders HVAC isolation for Zone 7 to prevent smoke spread, recognising that the HVAC system could be feeding oxygen to a developing fire and distributing smoke through the return air ducts.',
                ],
            ],
            [
                'axis'   => 'evacuation_decision',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Either refuses to evacuate based on false alarm history (putting 250 passengers at risk from potential fire) or orders full ship-wide alarm without any targeted approach (creating unnecessary panic for 4,250 other passengers).',
                    '2' => 'Delays evacuation decision waiting for more information while a potentially developing fire continues. Does not establish any interim protective measures for passengers near cabin 9147.',
                    '3' => 'Decides on targeted Zone 7 evacuation: recognises that the evidence of a potential fire outweighs the evacuation injury risk, but implements it in a controlled manner — uses zone-selective PA rather than general alarm, directs Hotel Director to deploy cabin stewards for controlled, assisted evacuation of Deck 9, ensures medical team is positioned at evacuation routes.',
                    '4' => 'Balanced evacuation management: implements a phased approach — immediate evacuation of cabins closest to 9147 (priority zone of 20-30 cabins) using cabin stewards for door-to-door notification rather than PA alarm (reducing panic), simultaneously prepares for full Zone 7 evacuation if fire is confirmed, positions medical team at evacuation route with wheelchair and mobility assistance, pre-identifies the muster area for displaced passengers (a lounge on Deck 10), Hotel Director coordinates crew at evacuation routes to assist elderly passengers, fire team enters cabin 9147 to confirm or deny fire while evacuation of adjacent cabins proceeds.',
                    '5' => 'Expert evacuation decision: implements immediate, phased, controlled evacuation recognising that a 15-minute-old potential cabin fire leaves no room for delay — Phase 1: steward-assisted door-to-door evacuation of 20 cabins nearest to 9147 beginning immediately (no PA alarm, personal contact, assistance for mobility-impaired), Phase 2: zone-selective PA for remainder of Deck 9 Zone 7 corridor triggered if fire team confirms fire or if smoke becomes visible, Phase 3: adjacent zones placed on standby alert, fire boundaries established per fire safety plan to contain any spread. Concurrently: fire team makes entry to cabin 9147 for assessment and firefighting, HVAC fire dampers closed for Zone 7 to prevent smoke migration, drencher system armed for activation, medical team deployed with stretchers and cardiac equipment at evacuation collection point, Hotel Director ensures all displaced passengers accounted for and provided with blankets and support in pre-identified lounge, entire response timeline documented on VDR and bridge log.',
                ],
            ],
            [
                'axis'   => 'technical_investigation_protocol',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'No structured investigation. Either resets the alarm and waits, or sends fire patrol without specific instructions. Does not investigate the root cause of the alarm or the steward report.',
                    '2' => 'Sends fire patrol to look at detectors again (same as previous false alarm responses) without specific focus on cabin 9147 or the new evidence. Does not request HVAC isolation or additional technical investigation.',
                    '3' => 'Directs fire patrol to specifically investigate cabin 9147: check door temperature with thermal camera, attempt to assess smoke density, report on any visible fire indicators. Requests HVAC team to isolate Zone 7 ventilation. Fire team prepared for cabin entry.',
                    '4' => 'Systematic technical investigation: fire patrol directed to thermal scan cabin 9147 door and surrounding bulkheads, assess the haze for colour and density (white steam vs. grey/brown smoke), check adjacent cabins 9145 and 9149 for heat or smoke migration. HVAC Zone 7 fire dampers ordered closed immediately to stop air supply and smoke distribution. Fire team briefed for cabin entry — one team to enter 9147 with extinguisher and thermal camera, backup team at corridor access. Chief Engineer directed to check electrical distribution board for Deck 9 Zone 7 for any tripped breakers or overload indicators. CCTV reviewed for Deck 9 corridor.',
                    '5' => 'Expert technical protocol: comprehensive multi-layer investigation initiated simultaneously — fire patrol: detailed thermal scan of cabin 9147 (door, bulkheads, overhead), haze characterisation (condensation is clear/white with no smell, fire smoke is grey/brown with particulate smell), cabin occupant status check (knocking, are passengers inside?). HVAC: immediate fire damper closure Zone 7, shutdown of Zone 7 air handling unit to stop oxygen supply, check return air duct for smoke (the HVAC system could be both the false alarm cause AND the pathway for real smoke). Electrical: Chief Engineer checks Deck 9 Zone 7 electrical distribution panel for overloads, reviews cabin 9147 electrical load (connected equipment in cabin management system if available). Fire team: makes entry to cabin 9147 with thermal camera, breathing apparatus, and extinguisher — team leader reports conditions on entry (visibility, temperature, smoke layer height). Bridge: checks cabin 9147 passenger manifest — are occupants inside? If so, this is a rescue as well as firefighting. Reviews CCTV for any visual of smoke in corridor. All findings reported to bridge for integrated assessment. Standby MAYDAY preparation if fire confirmed and developing.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Dismissed alarm as false based on previous pattern without investigating the new corroborating evidence',  'severity' => 'critical'],
            ['flag' => 'No investigation of cabin 9147 despite steward report, warm door, and visible haze',                     'severity' => 'critical'],
            ['flag' => 'No HVAC fire damper closure for Zone 7 to prevent smoke spread and oxygen supply',                       'severity' => 'critical'],
            ['flag' => 'No evacuation or protective action for passengers in the immediate vicinity of cabin 9147',              'severity' => 'critical'],
            ['flag' => 'No check on cabin 9147 occupants — possible passengers inside a developing fire',                        'severity' => 'major'],
            ['flag' => 'No recognition of alarm fatigue bias from six previous false alarms affecting decision-making',           'severity' => 'major'],
        ],
        'expected_references_json' => [
            'SOLAS Chapter II-2 — Fire protection, fire detection, and fire extinction',
            'FSS Code — International Code for Fire Safety Systems (Chapter 9: fire detection)',
            'Company fire safety plan and fire emergency procedures',
            'IMO MSC.1/Circ.1430 — Revised guidelines for the design and approval of fire safety systems',
            'STCW Code Section A-VI/3 — Advanced fire fighting',
            'IMO A.1050(27) — Revised guidelines on evacuation analysis for passenger ships',
        ],
        'red_flags_json' => [
            'Accepting Chief Engineer\'s "99% false alarm" assessment without independent investigation of the new evidence',
            'Resetting fire alarm and returning to normal status with steward report of electrical smell and warm cabin door',
            'Refusing to evacuate passengers near a potentially developing fire based on previous false alarm pattern',
            'Not closing HVAC fire dampers while investigating — allowing potential fire to receive oxygen and smoke to spread',
            'Not checking whether passengers are inside cabin 9147 during investigation',
            'Allowing alarm fatigue from previous false alarms to delay response to genuine fire indicators',
        ],
    ],

    // ══════════════════════════════════════════════════════════════
    // SLOT 4 — RISK_MGMT — Crowd management + muster drill failure + multilingual breakdown
    // ══════════════════════════════════════════════════════════════
    'PASSENGER_S04_RISK_001' => [
        'briefing_json' => [
            'en' => [
                'situation'           => 'You are Master of a 6,000-passenger mega-cruise ship on Day 1 departure from Miami. The mandatory muster drill required by SOLAS III Regulation 19.3 must be completed before departure. The drill commenced at 16:00 for an 18:00 departure, but systematic failures have emerged across multiple stations. Problem 1: The PA system in Zones 3 and 4 (Decks 6-8 forward, approximately 1,500 passengers) has intermittent audio — the sound cuts out for 5-10 second intervals and passengers in these zones cannot hear muster instructions clearly. The AV technician reports a likely amplifier fault on the forward PA distribution loop and estimates a 2-hour repair. Problem 2: Muster Station B (rated capacity 800) has 950 passengers present due to cabin reassignments made after the muster list was printed — 120 passengers were moved from Deck 10 aft cabins to Deck 7 forward cabins due to a plumbing issue, but the muster list was not updated and their original Station E assignment was not changed to Station B. Problem 3: The crew muster team at Station D reports that four crew members (two hotel housekeeping staff and two deck cadets) cannot correctly demonstrate donning of lifejackets — these crew were transferred aboard from a sister ship just 6 hours before departure and missed the mandatory safety familiarisation because they were immediately assigned to embarkation duties. Problem 4: Multilingual announcements are being made in English and Spanish only, but the passenger manifest shows 400+ passengers are Chinese-speaking tour groups (three groups with group leaders) who have limited English proficiency — the ship has no Mandarin-speaking crew member available for PA announcements and the pre-recorded Mandarin safety video is not functional on the muster station screens in Zones 3 and 4 (linked to the same AV distribution issue). Problem 5: An elderly passenger (78 years old) has collapsed at Muster Station A — the medical team is responding and performing initial assessment (suspected vasovagal syncope from standing in the heat), and the muster count for Station A (1,100 passengers) is now disrupted as passengers have moved away from the area to give space to the medical team. The Miami terminal has assigned a hard departure slot at 18:00 — if you miss it, the next available berth departure window considering tide, traffic, and Coast Guard requirements is 22:00, resulting in a 4-hour delay with associated fuel costs, port charges, passenger compensation claims, and disruption to the first sea day programme.',
                'your_position'       => 'Bridge, overseeing muster drill via CCTV and radio reports. Safety Officer is drill coordinator on deck. Hotel Director managing passenger flow. Staff Captain on the passenger deck.',
                'available_resources'  => 'PA system (partially functional — Zones 3/4 degraded), CCTV at all muster stations, portable loud-hailers (6 available), muster team crew at each station with muster lists, Safety Officer as drill coordinator, Hotel Director, Staff Captain, passenger services team, medical team at Station A, AV technician working on PA repair, IT department, pre-printed multilingual safety cards (including Mandarin), portable PA speakers (battery-operated, 4 available), Chinese-speaking passenger group leaders (3 identified), company Operations Centre in Miami on phone.',
                'current_conditions'   => 'Miami terminal, daylight, hot weather (32°C, high humidity), 6,000 passengers including 400+ Mandarin-speaking, PA Zones 3/4 intermittent, Station B overcrowded by 150, 4 crew unfamiliarised, Mandarin announcements unavailable, medical emergency Station A disrupting count, departure slot 18:00 (next: 22:00), drill commenced 16:00.',
            ],
            'tr' => [
                'situation'           => 'Miami\'den 1. Gün kalkışı yapan 6.000 yolculu mega kruvaziyer gemisinin kaptanısınız. SOLAS III Kural 19.3 gereği zorunlu toplanma tatbikatı kalkıştan önce tamamlanmalı. Tatbikat 16:00\'da başladı (kalkış 18:00) ancak birden fazla istasyonda sistematik aksaklıklar ortaya çıktı. Sorun 1: Bölge 3 ve 4\'teki PA sistemi (Güverte 6-8 pruva, ~1.500 yolcu) kesintili ses veriyor — 5-10 saniyelik aralıklarla ses kesiliyor, yolcular talimatları net duyamıyor. AV teknisyeni pruva PA dağıtım hattında amplifikatör arızası bildiriyor, tahmini 2 saatlik tamir. Sorun 2: B Toplanma İstasyonu (800 kapasite) kabinlerin yeniden atanması nedeniyle 950 yolcuyla dolmuş — toplanma listesi güncellenmemiş. Sorun 3: D İstasyonundaki 4 mürettebat üyesi (2 housekeeping, 2 güverte stajyeri) can yeleği giyme gösterimi yapamıyor — 6 saat önce kardeş gemiden transfer edilmiş ve güvenlik alıştırmasını kaçırmış. Sorun 4: Duyurular sadece İngilizce ve İspanyolca yapılıyor ama 400+ yolcu Çince konuşan tur grubu — gemide Mandarin PA duyurusu yapacak mürettebat yok ve Bölge 3/4\'teki ekranlarda önceden kaydedilmiş Mandarin güvenlik videosu çalışmıyor. Sorun 5: A İstasyonunda 78 yaşında bir yolcu bayılmış — tıbbi ekip müdahale ediyor ve 1.100 yolculuk istasyonun sayımı bozulmuş. Miami terminali 18:00\'da kesin kalkış slotu atamış — kaçırırsanız gelgit, trafik ve Sahil Güvenlik gereksinimleri nedeniyle bir sonraki müsait pencere 22:00 (4 saatlik gecikme).',
                'your_position'       => 'Köprüüstü, CCTV ve telsiz raporlarıyla tatbikatı denetliyorsunuz. Emniyet Zabiti güvertede tatbikat koordinatörü. Otel Müdürü yolcu akışını yönetiyor. Baş Kaptan yolcu güvertesinde.',
                'available_resources'  => 'PA sistemi (kısmi), tüm istasyonlarda CCTV, 6 taşınabilir megafon, toplanma listeli istasyon ekipleri, Emniyet Zabiti, Otel Müdürü, Baş Kaptan, A İstasyonunda tıbbi ekip, AV teknisyeni, BT departmanı, Mandarin dahil çok dilli basılı güvenlik kartları, 4 pilli taşınabilir PA hoparlör, 3 tanımlanmış Çince konuşan yolcu grup lideri, Miami şirket Operasyon Merkezi telefonda.',
                'current_conditions'   => 'Miami terminali, gündüz, sıcak (32°C, yüksek nem), 6.000 yolcu (400+ Mandarin konuşan), PA Bölge 3/4 kesintili, B İstasyonu 150 kişi fazla, 4 mürettebat alıştırmasız, Mandarin duyuru yok, A İstasyonunda tıbbi acil sayımı bozuyor, kalkış slotu 18:00 (sonraki 22:00), tatbikat 16:00\'da başladı.',
            ],
            'ru' => [
                'situation'           => 'Вы капитан мега-лайнера (6 000 пассажиров), день 1, отход из Майами. Учебная тревога по SOLAS III/19.3 обязательна до отхода. Началась в 16:00 (отход 18:00), но выявились системные проблемы. (1) PA зон 3-4 (палубы 6-8, ~1 500 чел.) работает с перебоями — звук пропадает на 5-10 сек. (2) Станция B переполнена: 950 вместо 800 из-за несовпадения мустер-листа после перераспределения кают. (3) 4 члена экипажа на станции D не могут надеть жилет — переведены 6 ч назад, пропустили инструктаж. (4) Объявления только на EN/ES, а 400+ пассажиров — китайские группы без английского, мандаринское видео не работает. (5) На станции A упал пожилой пассажир (78 лет), счёт 1 100 чел. сбит. Слот отхода 18:00, следующий — 22:00.',
                'your_position'       => 'Мостик, контроль по CCTV и радио. Офицер безопасности — координатор, отель-директор управляет потоком, старший помощник на пассажирской палубе.',
                'available_resources'  => 'PA (частично), CCTV, 6 мегафонов, мустер-команды, 4 портативные колонки, печатные карточки безопасности (вкл. мандарин), 3 китайских гид-лидера, AV-техник, мед. группа, Ops-центр в Майами.',
                'current_conditions'   => 'Майами, день, 32°C, 6 000 пассажиров (400+ мандарин), PA зон 3-4 сбоит, станция B +150, 4 экипаж без инструктажа, медицина на станции A, слот 18:00.',
            ],
            'az' => [
                'situation'           => 'Mayamidən yola düşən 6.000 sərnişinli mega-kruiz gəmisinin kapitanısınız. SOLAS III/19.3 üzrə məcburi toplanma təlimi yola düşməzdən əvvəl tamamlanmalıdır. Təlim 16:00-da başlayıb (yola düşmə 18:00), amma sistemli problemlər aşkar olunub: (1) Zona 3-4 PA sistemi (göyərtə 6-8, ~1.500 sərnişin) fasilələrlə işləyir; (2) B stansiyası 950 nəfərlə dolu (tutum 800) — muster siyahısı yenilənməyib; (3) D stansiyasında 4 heyət üzvü xilasedici jilet geyinməyi bacarmır — 6 saat əvvəl transfer olunub, təlim keçirməyib; (4) Elanlar yalnız EN/ES — 400+ mandarin danışan sərnişin var, mandarin videosu işləmir; (5) A stansiyasında yaşlı sərnişin yıxılıb, 1.100 nəfərlik sayım pozulub. Yola düşmə slotu 18:00, növbəti 22:00.',
                'your_position'       => 'Körpüüstü, CCTV və radio ilə nəzarət. Təhlükəsizlik Zabiti koordinator, Otel Direktoru sərnişin axını, Baş Kapitan göyərtədə.',
                'available_resources'  => 'PA (qismən), CCTV, 6 meqafon, muster komandaları, 4 portativ dinamik, mandarin daxil çap olunmuş təhlükəsizlik kartları, 3 çinli qrup lideri, AV texnik, tibbi komanda, Mayami Ops mərkəzi.',
                'current_conditions'   => 'Mayami, gündüz, 32°C, 6.000 sərnişin (400+ mandarin), PA zona 3-4 fasiləli, B stansiyası +150, 4 heyət təlimsiz, A stansiyasında tibbi hadisə, slot 18:00.',
            ],
        ],
        'decision_prompt'      => 'How do you manage this muster drill situation to achieve SOLAS compliance while addressing the five identified problems? Describe your corrective actions for each issue, your decision on whether to delay departure, how you ensure all 6,000 passengers receive adequate safety briefing including the Mandarin-speaking groups, and your communication with the company Operations Centre regarding the departure slot.',
        'decision_prompt_i18n' => [
            'tr' => 'Beş tespit edilen sorunu ele alırken SOLAS uyumluluğunu sağlamak için bu toplanma tatbikatı durumunu nasıl yönetiyorsunuz? Her sorun için düzeltici eylemlerinizi, kalkışı geciktirme kararınızı, Mandarin konuşan gruplar dahil tüm 6.000 yolcunun yeterli güvenlik brifingini nasıl sağladığınızı ve kalkış slotu hakkında şirket Operasyon Merkezi ile iletişiminizi açıklayın.',
            'ru' => 'Как обеспечить соответствие SOLAS при пяти выявленных проблемах? Опишите корректирующие меры по каждому вопросу, решение о задержке отхода, обеспечение брифинга всех 6 000 пассажиров включая мандариноязычных, и связь с Ops-центром.',
            'az' => 'Beş problemi həll edərək SOLAS uyğunluğunu necə təmin edirsiniz? Hər problem üçün düzəldici tədbirləri, yola düşməni gecikdirmə qərarını, mandarin danışan qruplar daxil 6.000 sərnişinin təhlükəsizlik brifinqini və Ops mərkəzi ilə əlaqəni təsvir edin.',
        ],
        'evaluation_axes_json' => [
            [
                'axis'   => 'muster_drill_compliance',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Declares the muster drill "complete enough" despite the identified failures and proceeds to depart on schedule. Does not address the PA failure, overcrowding, untrained crew, or language gap. No understanding that SOLAS III/19.3 requires the drill to be completed satisfactorily.',
                    '2' => 'Attempts to address some issues superficially — orders crew to "sort out" the overcrowding and tells the untrained crew to "watch a video" — but does not verify that corrective actions achieve actual SOLAS compliance. Proceeds to depart hoping problems are resolved.',
                    '3' => 'Addresses each compliance issue systematically: deploys portable PA for Zones 3/4, redistributes Station B passengers per corrected muster list, requires the four crew to complete safety familiarisation before departure, arranges Mandarin briefing through group leaders with printed materials, re-counts Station A after medical incident resolved. Accepts that departure may be delayed if drill requirements are not met.',
                    '4' => 'Thorough compliance management: PA issue — deploys 4 portable battery speakers and 6 loud-hailers to Zones 3/4 with crew members providing live safety briefings to compensate for intermittent PA, AV technician continues repair as backup. Station B — immediately corrects the muster list, redistributes 150 excess passengers to Station E with crew escorts, verifies head count at both stations. Crew training — 4 crew members pulled from current duties immediately, Safety Officer or delegate conducts personal safety familiarisation and lifejacket demonstration, verified by competency check before drill can be considered complete. Mandarin — engages 3 Chinese group leaders as interpreters at their respective muster stations, distributes Mandarin safety cards, crew member conducts demonstration with group leaders translating, verifies comprehension. Station A — medical team completes patient assessment, Safety Officer re-musters Station A with systematic head count. Only certifies drill as complete when all issues verified resolved.',
                    '5' => 'Expert SOLAS compliance: recognises that the drill must meet the intent of SOLAS III Reg 19.3 — every passenger must understand their muster station, route, lifejacket donning, and emergency procedures. Implements comprehensive corrective actions for each issue with verification: PA — portable speakers plus crew-led live briefings in small groups of 50 for Zones 3/4 passengers (actually superior to PA-only delivery), with each group confirmed as briefed. Station B — muster list corrected, passengers redistributed, and systematic root-cause analysis initiated (why were cabin changes not reflected in muster list? process failure reported to Safety Officer for corrective action in SMS). Crew — four members undergo immediate personalised safety familiarisation per STCW A-V/2 with practical demonstration and assessment — signs off their familiarisation records before they return to duty. Mandarin — three group leaders formally briefed as safety assistants for their groups, Mandarin safety cards distributed to all 400+ passengers individually, crew demonstrates with group leaders interpreting, each group\'s comprehension verified by asking passengers to demonstrate lifejacket donning. Station A — re-muster with name-by-name roll call to ensure accurate count (not just head count). Entire drill documented with evidence of compliance for each station. Departs ONLY when satisfied all requirements met — advises company Operations that 18:00 slot is not achievable if drill cannot be completed, and that SOLAS compliance is non-negotiable regardless of commercial consequences.',
                ],
            ],
            [
                'axis'   => 'crowd_management_safety',
                'weight' => 0.30,
                'rubric_levels' => [
                    '1' => 'No awareness of crowd safety risks during the muster drill. Does not address the overcrowding at Station B, the heat conditions (32°C), or the medical emergency impact on crowd management. No consideration of 6,000 passengers standing in hot conditions.',
                    '2' => 'Aware of the overcrowding and heat but only addresses them reactively. Allows 950 passengers to remain at Station B without redistribution. Does not monitor passenger welfare during the extended drill period.',
                    '3' => 'Active crowd management: addresses Station B overcrowding by redistributing passengers, monitors heat stress conditions (32°C, high humidity) and directs hotel team to distribute water, manages the medical emergency area at Station A to prevent crowd interference, adjusts drill pace to minimise passenger standing time.',
                    '4' => 'Proactive crowd safety: Station B overcrowding resolved immediately with crew-escorted passenger movement, heat mitigation implemented (water distribution, shade management, priority seating for elderly/disabled), medical emergency at Station A managed with crowd control (crew cordon, PA announcement to reassure passengers), CCTV monitoring of all stations for crowd density and distress indicators, crew positioned at potential bottleneck points, considers reducing drill duration for completed stations to release passengers from heat.',
                    '5' => 'Comprehensive crowd management: integrates all crowd safety factors into drill management — Station B resolved with controlled passenger redistribution (not a mass movement, but crew-escorted groups of 30-40 to prevent corridor congestion), heat stress protocol activated (water, medical team on roving patrol for heat-related illness, shortened standing time by processing stations in waves), Station A medical incident managed with compassion and professionalism (screens for patient privacy, PA reassurance, crew prevent crowding, muster count maintained by alternative method), CCTV actively monitored for all stations with dedicated bridge officer watching for crowd density warnings, special attention to vulnerable passengers (elderly, disabled, children, passengers with mobility issues — identified from passenger manifest), drill sequenced to minimise total standing time for each group, considers that 6,000 passengers in 32°C are themselves a medical risk and acts accordingly.',
                ],
            ],
            [
                'axis'   => 'regulatory_decision_authority',
                'weight' => 0.35,
                'rubric_levels' => [
                    '1' => 'Allows commercial pressure to determine the departure decision. Certifies drill as complete when it clearly is not. Does not exercise Master\'s authority on SOLAS compliance. Departs at 18:00 regardless of drill status.',
                    '2' => 'Hesitates between compliance and schedule. Asks company Operations to decide whether to delay rather than exercising own authority. Partially completes the drill and departs hoping to "finish during the safety video showing after dinner."',
                    '3' => 'Exercises Master\'s authority: informs company Operations that departure will be delayed if the drill cannot be completed satisfactorily, implements corrective actions with realistic timelines, does not depart until personally satisfied that SOLAS requirements are met, communicates the decision and rationale clearly.',
                    '4' => 'Strong regulatory authority: early assessment at 16:30 that 18:00 departure is unlikely given the five issues, immediately informs company Operations with specific timeline ("expect 19:00-19:30 completion based on current corrective action plan"), takes full ownership of the decision per ISM Code Master\'s authority, does not seek permission to delay — informs company of the delay and the reasons, coordinates with Miami terminal for revised slot, ensures USCG (flag state/port state) requirements are met, documents decision rationale.',
                    '5' => 'Exemplary regulatory leadership: recognises at the outset that these five simultaneous failures represent a systemic readiness issue that must be fully resolved regardless of schedule, communicates decisively with company Operations — "the vessel will depart when the muster drill is satisfactorily completed per SOLAS III Reg 19.3; I am exercising my authority under ISM Code Section 5 and will not compromise on passenger safety for 6,000 persons," provides detailed corrective action plan with realistic milestones, coordinates through ship agent for revised departure slot with terminal and USCG, manages passenger expectations through Hotel Director (PA announcement explaining brief delay for "completion of safety procedures" — honest without causing alarm), considers whether the systemic nature of these failures (PA failure, muster list error, crew familiarisation failure, language capability gap) indicates deeper readiness issues that should be addressed before sea, documents everything for company review and potential USCG inspection, ensures that the lesson is clear: SOLAS muster drill compliance is absolute, not subject to commercial negotiation.',
                ],
            ],
        ],
        'critical_omission_flags_json' => [
            ['flag' => 'Departing without satisfactorily completing the SOLAS III muster drill for all passengers',              'severity' => 'critical'],
            ['flag' => 'No corrective action for the 400+ Mandarin-speaking passengers who received no safety briefing',         'severity' => 'critical'],
            ['flag' => 'Allowing four unfamiliarised crew members to serve in safety roles without completing training',          'severity' => 'critical'],
            ['flag' => 'Not correcting the muster list and Station B overcrowding before certifying drill completion',            'severity' => 'major'],
            ['flag' => 'No alternative PA arrangements for 1,500 passengers in Zones 3/4 with degraded audio',                   'severity' => 'major'],
            ['flag' => 'Allowing commercial departure pressure to override SOLAS drill requirements with 6,000 passengers',       'severity' => 'critical'],
        ],
        'expected_references_json' => [
            'SOLAS Chapter III Regulation 19.3 — Muster drill requirements before departure',
            'MSC.1/Circ.1533 — Guidelines on the safety briefing and muster process',
            'ISM Code Section 5 — Master\'s responsibility and authority',
            'STCW Code A-V/2 — Mandatory minimum requirements for training of passenger ship personnel (crowd management)',
            'Company muster drill procedures and Safety Management System',
            'MLC 2006 — Maritime Labour Convention (crew training and familiarisation requirements)',
            'USCG NVIC 01-14 — Guidance on muster drill requirements for passenger vessels',
        ],
        'red_flags_json' => [
            'Departing from Miami without completing the muster drill for all 6,000 passengers as required by SOLAS',
            'Failing to provide any safety briefing to 400+ Mandarin-speaking passengers due to language barrier',
            'Allowing untrained crew to serve at muster stations without verifying their competency',
            'Certifying the muster drill as complete when Station B exceeds capacity and muster list is incorrect',
            'Accepting degraded PA in Zones 3/4 without deploying alternative means of communicating safety instructions',
            'Prioritising the 18:00 departure slot over SOLAS compliance with 6,000 passengers aboard',
        ],
    ],

];
